// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ApplicationsColumns holds the columns for the "applications" table.
	ApplicationsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "name", Type: field.TypeString},
		{Name: "application_default_personal_role", Type: field.TypeUUID, Nullable: true},
		{Name: "application_default_org_role", Type: field.TypeUUID, Nullable: true},
		{Name: "application_default_org_admin_role", Type: field.TypeUUID, Nullable: true},
	}
	// ApplicationsTable holds the schema information for the "applications" table.
	ApplicationsTable = &schema.Table{
		Name:       "applications",
		Columns:    ApplicationsColumns,
		PrimaryKey: []*schema.Column{ApplicationsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "applications_roles_default_personal_role",
				Columns:    []*schema.Column{ApplicationsColumns[5]},
				RefColumns: []*schema.Column{RolesColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "applications_roles_default_org_role",
				Columns:    []*schema.Column{ApplicationsColumns[6]},
				RefColumns: []*schema.Column{RolesColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "applications_roles_default_org_admin_role",
				Columns:    []*schema.Column{ApplicationsColumns[7]},
				RefColumns: []*schema.Column{RolesColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "application_name",
				Unique:  true,
				Columns: []*schema.Column{ApplicationsColumns[4]},
			},
		},
	}
	// BindingsColumns holds the columns for the "bindings" table.
	BindingsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"wechat", "qy_wechat", "wxid", "phone", "password", "email", "google", "unknown"}},
		{Name: "identity", Type: field.TypeString},
		{Name: "email", Type: field.TypeString, Nullable: true},
		{Name: "verified", Type: field.TypeBool, Default: false},
		{Name: "salt", Type: field.TypeString, Nullable: true},
		{Name: "application_id", Type: field.TypeUUID, Nullable: true},
		{Name: "user_id", Type: field.TypeString},
	}
	// BindingsTable holds the schema information for the "bindings" table.
	BindingsTable = &schema.Table{
		Name:       "bindings",
		Columns:    BindingsColumns,
		PrimaryKey: []*schema.Column{BindingsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "bindings_users_bindings",
				Columns:    []*schema.Column{BindingsColumns[10]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "binding_type_identity",
				Unique:  false,
				Columns: []*schema.Column{BindingsColumns[4], BindingsColumns[5]},
				Annotation: &entsql.IndexAnnotation{
					PrefixColumns: map[string]uint{
						BindingsColumns[5].Name: 10,
					},
				},
			},
			{
				Name:    "binding_user_id_type",
				Unique:  true,
				Columns: []*schema.Column{BindingsColumns[10], BindingsColumns[4]},
			},
		},
	}
	// BindingVerifiesColumns holds the columns for the "binding_verifies" table.
	BindingVerifiesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "user_id", Type: field.TypeString},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"wechat", "qy_wechat", "wxid", "phone", "password", "email", "google", "unknown"}},
		{Name: "identity", Type: field.TypeString},
		{Name: "code", Type: field.TypeString},
		{Name: "expires_at", Type: field.TypeTime},
		{Name: "verified_at", Type: field.TypeTime},
	}
	// BindingVerifiesTable holds the schema information for the "binding_verifies" table.
	BindingVerifiesTable = &schema.Table{
		Name:       "binding_verifies",
		Columns:    BindingVerifiesColumns,
		PrimaryKey: []*schema.Column{BindingVerifiesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "bindingverify_user_id_type_identity",
				Unique:  true,
				Columns: []*schema.Column{BindingVerifiesColumns[4], BindingVerifiesColumns[5], BindingVerifiesColumns[6]},
			},
		},
	}
	// DevicesColumns holds the columns for the "devices" table.
	DevicesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "organization_id", Type: field.TypeUUID, Nullable: true},
		{Name: "device_type", Type: field.TypeString},
		{Name: "device_id", Type: field.TypeString},
		{Name: "refresh_token", Type: field.TypeString},
		{Name: "refresh_token_expires_at", Type: field.TypeTime},
		{Name: "user_id", Type: field.TypeString},
	}
	// DevicesTable holds the schema information for the "devices" table.
	DevicesTable = &schema.Table{
		Name:       "devices",
		Columns:    DevicesColumns,
		PrimaryKey: []*schema.Column{DevicesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "devices_users_devices",
				Columns:    []*schema.Column{DevicesColumns[9]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "device_refresh_token",
				Unique:  true,
				Columns: []*schema.Column{DevicesColumns[7]},
			},
			{
				Name:    "device_user_id_device_type_device_id",
				Unique:  true,
				Columns: []*schema.Column{DevicesColumns[9], DevicesColumns[5], DevicesColumns[6]},
			},
		},
	}
	// MailVertifyCodesColumns holds the columns for the "mail_vertify_codes" table.
	MailVertifyCodesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"login", "unknown"}},
		{Name: "email", Type: field.TypeString},
		{Name: "code", Type: field.TypeString},
		{Name: "expires_at", Type: field.TypeTime},
	}
	// MailVertifyCodesTable holds the schema information for the "mail_vertify_codes" table.
	MailVertifyCodesTable = &schema.Table{
		Name:       "mail_vertify_codes",
		Columns:    MailVertifyCodesColumns,
		PrimaryKey: []*schema.Column{MailVertifyCodesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "mailvertifycode_type_email",
				Unique:  true,
				Columns: []*schema.Column{MailVertifyCodesColumns[4], MailVertifyCodesColumns[5]},
			},
		},
	}
	// OrganizationsColumns holds the columns for the "organizations" table.
	OrganizationsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "name", Type: field.TypeString},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"normal", "advanced", "premium", "trial", "unknown"}},
		{Name: "refresh_at", Type: field.TypeTime, Nullable: true},
		{Name: "expires_at", Type: field.TypeTime, Nullable: true},
		{Name: "permission_code", Type: field.TypeString, Default: "init_permission_code"},
		{Name: "logo_url", Type: field.TypeString, Default: ""},
		{Name: "application_id", Type: field.TypeUUID},
	}
	// OrganizationsTable holds the schema information for the "organizations" table.
	OrganizationsTable = &schema.Table{
		Name:       "organizations",
		Columns:    OrganizationsColumns,
		PrimaryKey: []*schema.Column{OrganizationsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "organizations_applications_organizations",
				Columns:    []*schema.Column{OrganizationsColumns[10]},
				RefColumns: []*schema.Column{ApplicationsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "organization_application_id_name",
				Unique:  true,
				Columns: []*schema.Column{OrganizationsColumns[10], OrganizationsColumns[4]},
			},
		},
	}
	// OrganizationApplicationsColumns holds the columns for the "organization_applications" table.
	OrganizationApplicationsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "name", Type: field.TypeString},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"normal", "advanced", "premium", "trial", "unknown"}},
		{Name: "trial_days", Type: field.TypeInt32, Nullable: true},
		{Name: "review_status", Type: field.TypeEnum, Enums: []string{"pending", "approved", "reject", "unknown"}},
		{Name: "review_comment", Type: field.TypeString, Size: 2000, Default: ""},
		{Name: "user_id", Type: field.TypeString},
		{Name: "brand_short_name", Type: field.TypeString},
		{Name: "primary_business", Type: field.TypeString, Size: 5000},
		{Name: "usage_scenario", Type: field.TypeString, Size: 5000},
		{Name: "referrer_name", Type: field.TypeString, Nullable: true},
		{Name: "discovery_way", Type: field.TypeString, Nullable: true},
		{Name: "org_role_name", Type: field.TypeString},
		{Name: "application_id", Type: field.TypeUUID},
	}
	// OrganizationApplicationsTable holds the schema information for the "organization_applications" table.
	OrganizationApplicationsTable = &schema.Table{
		Name:       "organization_applications",
		Columns:    OrganizationApplicationsColumns,
		PrimaryKey: []*schema.Column{OrganizationApplicationsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "organization_applications_applications_organization_application",
				Columns:    []*schema.Column{OrganizationApplicationsColumns[16]},
				RefColumns: []*schema.Column{ApplicationsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "organizationapplication_application_id_name",
				Unique:  true,
				Columns: []*schema.Column{OrganizationApplicationsColumns[16], OrganizationApplicationsColumns[4]},
			},
		},
	}
	// OrganizationRequestsColumns holds the columns for the "organization_requests" table.
	OrganizationRequestsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"creation", "join", "unknown"}},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"pending", "approved", "reject", "unknown"}},
		{Name: "user_id", Type: field.TypeString},
		{Name: "organization_id", Type: field.TypeUUID},
		{Name: "organization_name", Type: field.TypeString},
	}
	// OrganizationRequestsTable holds the schema information for the "organization_requests" table.
	OrganizationRequestsTable = &schema.Table{
		Name:       "organization_requests",
		Columns:    OrganizationRequestsColumns,
		PrimaryKey: []*schema.Column{OrganizationRequestsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "organizationrequest_organization_id",
				Unique:  false,
				Columns: []*schema.Column{OrganizationRequestsColumns[7]},
				Annotation: &entsql.IndexAnnotation{
					Prefix: 18,
				},
			},
		},
	}
	// OrganizationUsersColumns holds the columns for the "organization_users" table.
	OrganizationUsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "organization_id", Type: field.TypeUUID},
		{Name: "user_id", Type: field.TypeString},
		{Name: "organization_user_role", Type: field.TypeUUID, Nullable: true},
	}
	// OrganizationUsersTable holds the schema information for the "organization_users" table.
	OrganizationUsersTable = &schema.Table{
		Name:       "organization_users",
		Columns:    OrganizationUsersColumns,
		PrimaryKey: []*schema.Column{OrganizationUsersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "organization_users_organizations_organization",
				Columns:    []*schema.Column{OrganizationUsersColumns[4]},
				RefColumns: []*schema.Column{OrganizationsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "organization_users_users_user",
				Columns:    []*schema.Column{OrganizationUsersColumns[5]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "organization_users_roles_role",
				Columns:    []*schema.Column{OrganizationUsersColumns[6]},
				RefColumns: []*schema.Column{RolesColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "organizationuser_user_id_organization_id",
				Unique:  true,
				Columns: []*schema.Column{OrganizationUsersColumns[5], OrganizationUsersColumns[4]},
			},
		},
	}
	// PaymentsColumns holds the columns for the "payments" table.
	PaymentsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "out_trade_no", Type: field.TypeString},
		{Name: "channel", Type: field.TypeEnum, Enums: []string{"wechat", "stripe"}},
		{Name: "service", Type: field.TypeString},
		{Name: "amount", Type: field.TypeInt},
		{Name: "currency", Type: field.TypeString},
		{Name: "description", Type: field.TypeString},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"NOTPAY", "SUCCESS", "CLOSED", "REFUND", "FAILED"}},
		{Name: "paid_at", Type: field.TypeTime, Nullable: true},
		{Name: "payment_type", Type: field.TypeEnum, Enums: []string{"one_time", "subscription"}, Default: "one_time"},
		{Name: "wechat_platform", Type: field.TypeString, Nullable: true},
		{Name: "wechat_open_id", Type: field.TypeString, Nullable: true},
		{Name: "wechat_transaction_id", Type: field.TypeString, Nullable: true},
		{Name: "stripe_subscription_id", Type: field.TypeString, Nullable: true},
		{Name: "stripe_subscription_status", Type: field.TypeString, Nullable: true},
		{Name: "stripe_interval", Type: field.TypeString, Nullable: true},
		{Name: "stripe_cancel_at_period_end", Type: field.TypeBool, Default: false},
		{Name: "stripe_current_period_start", Type: field.TypeTime, Nullable: true},
		{Name: "stripe_current_period_end", Type: field.TypeTime, Nullable: true},
		{Name: "stripe_customer_id", Type: field.TypeString, Nullable: true},
		{Name: "stripe_customer_email", Type: field.TypeString, Nullable: true},
		{Name: "stripe_checkout_session_id", Type: field.TypeString, Nullable: true},
		{Name: "stripe_invoice_id", Type: field.TypeString, Nullable: true},
		{Name: "user_id", Type: field.TypeString},
	}
	// PaymentsTable holds the schema information for the "payments" table.
	PaymentsTable = &schema.Table{
		Name:       "payments",
		Columns:    PaymentsColumns,
		PrimaryKey: []*schema.Column{PaymentsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "payments_users_payments",
				Columns:    []*schema.Column{PaymentsColumns[25]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "payment_out_trade_no",
				Unique:  true,
				Columns: []*schema.Column{PaymentsColumns[3]},
			},
			{
				Name:    "payment_stripe_subscription_id",
				Unique:  false,
				Columns: []*schema.Column{PaymentsColumns[15]},
			},
			{
				Name:    "payment_stripe_customer_id",
				Unique:  false,
				Columns: []*schema.Column{PaymentsColumns[21]},
			},
			{
				Name:    "payment_stripe_checkout_session_id",
				Unique:  false,
				Columns: []*schema.Column{PaymentsColumns[23]},
			},
		},
	}
	// QyWechatUserIdsColumns holds the columns for the "qy_wechat_user_ids" table.
	QyWechatUserIdsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "qy_wechat_user_id", Type: field.TypeString, Nullable: true},
		{Name: "open_id", Type: field.TypeString, Nullable: true},
		{Name: "user_id", Type: field.TypeString},
	}
	// QyWechatUserIdsTable holds the schema information for the "qy_wechat_user_ids" table.
	QyWechatUserIdsTable = &schema.Table{
		Name:       "qy_wechat_user_ids",
		Columns:    QyWechatUserIdsColumns,
		PrimaryKey: []*schema.Column{QyWechatUserIdsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "qy_wechat_user_ids_users_qy_wechat_user_ids",
				Columns:    []*schema.Column{QyWechatUserIdsColumns[6]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "qywechatuserid_user_id",
				Unique:  true,
				Columns: []*schema.Column{QyWechatUserIdsColumns[6]},
			},
			{
				Name:    "qywechatuserid_qy_wechat_user_id",
				Unique:  true,
				Columns: []*schema.Column{QyWechatUserIdsColumns[4]},
			},
		},
	}
	// RolesColumns holds the columns for the "roles" table.
	RolesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "name", Type: field.TypeString},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"unknown", "personal", "organization"}},
		{Name: "application_id", Type: field.TypeUUID},
	}
	// RolesTable holds the schema information for the "roles" table.
	RolesTable = &schema.Table{
		Name:       "roles",
		Columns:    RolesColumns,
		PrimaryKey: []*schema.Column{RolesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "roles_applications_roles",
				Columns:    []*schema.Column{RolesColumns[6]},
				RefColumns: []*schema.Column{ApplicationsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "role_application_id_name",
				Unique:  true,
				Columns: []*schema.Column{RolesColumns[6], RolesColumns[4]},
			},
		},
	}
	// ScopesColumns holds the columns for the "scopes" table.
	ScopesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "name", Type: field.TypeString},
		{Name: "hidden_in_jwt", Type: field.TypeBool, Default: false},
		{Name: "role_id", Type: field.TypeUUID},
	}
	// ScopesTable holds the schema information for the "scopes" table.
	ScopesTable = &schema.Table{
		Name:       "scopes",
		Columns:    ScopesColumns,
		PrimaryKey: []*schema.Column{ScopesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "scopes_roles_scopes",
				Columns:    []*schema.Column{ScopesColumns[6]},
				RefColumns: []*schema.Column{RolesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "scope_role_id_name",
				Unique:  true,
				Columns: []*schema.Column{ScopesColumns[6], ScopesColumns[4]},
			},
		},
	}
	// StripeEventsColumns holds the columns for the "stripe_events" table.
	StripeEventsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "event_id", Type: field.TypeString, Unique: true},
		{Name: "event_type", Type: field.TypeString},
		{Name: "subscription_id", Type: field.TypeString, Nullable: true},
		{Name: "user_id", Type: field.TypeString, Nullable: true},
		{Name: "processed", Type: field.TypeBool, Default: false},
		{Name: "processed_at", Type: field.TypeTime, Nullable: true},
	}
	// StripeEventsTable holds the schema information for the "stripe_events" table.
	StripeEventsTable = &schema.Table{
		Name:       "stripe_events",
		Columns:    StripeEventsColumns,
		PrimaryKey: []*schema.Column{StripeEventsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "stripeevent_event_id",
				Unique:  true,
				Columns: []*schema.Column{StripeEventsColumns[2]},
			},
			{
				Name:    "stripeevent_event_type_processed",
				Unique:  false,
				Columns: []*schema.Column{StripeEventsColumns[3], StripeEventsColumns[6]},
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "name", Type: field.TypeString},
		{Name: "display_name", Type: field.TypeString, Nullable: true},
		{Name: "avatar", Type: field.TypeString, Nullable: true},
		{Name: "referral_channel", Type: field.TypeJSON, Nullable: true},
		{Name: "department", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "application_id", Type: field.TypeUUID},
		{Name: "user_personal_role", Type: field.TypeUUID, Nullable: true},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "users_applications_users",
				Columns:    []*schema.Column{UsersColumns[9]},
				RefColumns: []*schema.Column{ApplicationsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "users_roles_personal_role",
				Columns:    []*schema.Column{UsersColumns[10]},
				RefColumns: []*schema.Column{RolesColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "user_application_id_name",
				Unique:  true,
				Columns: []*schema.Column{UsersColumns[9], UsersColumns[4]},
			},
			{
				Name:    "user_name",
				Unique:  false,
				Columns: []*schema.Column{UsersColumns[4]},
			},
		},
	}
	// WechatOpenIdsColumns holds the columns for the "wechat_open_ids" table.
	WechatOpenIdsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "open_id", Type: field.TypeString},
		{Name: "platform", Type: field.TypeEnum, Enums: []string{"miniprogram", "unknown"}},
		{Name: "union_id", Type: field.TypeString, Nullable: true},
		{Name: "user_id", Type: field.TypeString},
	}
	// WechatOpenIdsTable holds the schema information for the "wechat_open_ids" table.
	WechatOpenIdsTable = &schema.Table{
		Name:       "wechat_open_ids",
		Columns:    WechatOpenIdsColumns,
		PrimaryKey: []*schema.Column{WechatOpenIdsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "wechat_open_ids_users_open_ids",
				Columns:    []*schema.Column{WechatOpenIdsColumns[7]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "wechatopenid_user_id_platform",
				Unique:  true,
				Columns: []*schema.Column{WechatOpenIdsColumns[7], WechatOpenIdsColumns[5]},
			},
			{
				Name:    "wechatopenid_user_id",
				Unique:  false,
				Columns: []*schema.Column{WechatOpenIdsColumns[7]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ApplicationsTable,
		BindingsTable,
		BindingVerifiesTable,
		DevicesTable,
		MailVertifyCodesTable,
		OrganizationsTable,
		OrganizationApplicationsTable,
		OrganizationRequestsTable,
		OrganizationUsersTable,
		PaymentsTable,
		QyWechatUserIdsTable,
		RolesTable,
		ScopesTable,
		StripeEventsTable,
		UsersTable,
		WechatOpenIdsTable,
	}
)

func init() {
	ApplicationsTable.ForeignKeys[0].RefTable = RolesTable
	ApplicationsTable.ForeignKeys[1].RefTable = RolesTable
	ApplicationsTable.ForeignKeys[2].RefTable = RolesTable
	BindingsTable.ForeignKeys[0].RefTable = UsersTable
	DevicesTable.ForeignKeys[0].RefTable = UsersTable
	OrganizationsTable.ForeignKeys[0].RefTable = ApplicationsTable
	OrganizationApplicationsTable.ForeignKeys[0].RefTable = ApplicationsTable
	OrganizationUsersTable.ForeignKeys[0].RefTable = OrganizationsTable
	OrganizationUsersTable.ForeignKeys[1].RefTable = UsersTable
	OrganizationUsersTable.ForeignKeys[2].RefTable = RolesTable
	PaymentsTable.ForeignKeys[0].RefTable = UsersTable
	QyWechatUserIdsTable.ForeignKeys[0].RefTable = UsersTable
	RolesTable.ForeignKeys[0].RefTable = ApplicationsTable
	ScopesTable.ForeignKeys[0].RefTable = RolesTable
	UsersTable.ForeignKeys[0].RefTable = ApplicationsTable
	UsersTable.ForeignKeys[1].RefTable = RolesTable
	WechatOpenIdsTable.ForeignKeys[0].RefTable = UsersTable
}
