-- Create "applications" table
CREATE TABLE "applications" ("id" uuid NOT NULL, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, "deleted_at" timestamptz NULL, "name" character varying NOT NULL, "application_default_personal_role" uuid NULL, "application_default_org_role" uuid NULL, "application_default_org_admin_role" uuid NULL, PRIMARY KEY ("id"));
-- Create index "application_name" to table: "applications"
CREATE UNIQUE INDEX "application_name" ON "applications" ("name");
-- Create "binding_verifies" table
CREATE TABLE "binding_verifies" ("id" uuid NOT NULL, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, "deleted_at" timestamptz NULL, "user_id" character varying NOT NULL, "type" character varying NOT NULL, "identity" character varying NOT NULL, "code" character varying NOT NULL, "expires_at" timestamptz NOT NULL, "verified_at" timestamptz NOT NULL, PRIMARY KEY ("id"));
-- Create index "bindingverify_user_id_type_identity" to table: "binding_verifies"
CREATE UNIQUE INDEX "bindingverify_user_id_type_identity" ON "binding_verifies" ("user_id", "type", "identity");
-- Create "bindings" table
CREATE TABLE "bindings" ("id" uuid NOT NULL, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, "deleted_at" timestamptz NULL, "type" character varying NOT NULL, "identity" character varying NOT NULL, "verified" boolean NOT NULL DEFAULT false, "salt" character varying NULL, "user_id" character varying NOT NULL, PRIMARY KEY ("id"));
-- Create index "binding_type_identity" to table: "bindings"
CREATE INDEX "binding_type_identity" ON "bindings" ("type", "identity");
-- Create index "binding_user_id_type" to table: "bindings"
CREATE UNIQUE INDEX "binding_user_id_type" ON "bindings" ("user_id", "type");
-- Create "devices" table
CREATE TABLE "devices" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, "deleted_at" timestamptz NULL, "device_type" character varying NOT NULL, "device_id" character varying NOT NULL, "refresh_token" character varying NOT NULL, "refresh_token_expires_at" timestamptz NOT NULL, "user_id" character varying NOT NULL, PRIMARY KEY ("id"));
-- Create index "device_refresh_token" to table: "devices"
CREATE UNIQUE INDEX "device_refresh_token" ON "devices" ("refresh_token");
-- Create index "device_user_id_device_type_device_id" to table: "devices"
CREATE UNIQUE INDEX "device_user_id_device_type_device_id" ON "devices" ("user_id", "device_type", "device_id");
-- Create "organization_requests" table
CREATE TABLE "organization_requests" ("id" uuid NOT NULL, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, "deleted_at" timestamptz NULL, "type" character varying NOT NULL, "status" character varying NOT NULL, "user_id" character varying NOT NULL, "organization_id" uuid NOT NULL, "organization_name" character varying NOT NULL, PRIMARY KEY ("id"));
-- Create "organization_users" table
CREATE TABLE "organization_users" ("id" uuid NOT NULL, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, "deleted_at" timestamptz NULL, "organization_id" uuid NOT NULL, "user_id" character varying NOT NULL, "organization_user_role" uuid NULL, PRIMARY KEY ("id"));
-- Create "organizations" table
CREATE TABLE "organizations" ("id" uuid NOT NULL, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, "deleted_at" timestamptz NULL, "name" character varying NOT NULL, "status" character varying NOT NULL, "expires_at" timestamptz NULL, "application_id" uuid NOT NULL, PRIMARY KEY ("id"));
-- Create index "organization_application_id_name" to table: "organizations"
CREATE UNIQUE INDEX "organization_application_id_name" ON "organizations" ("application_id", "name");
-- Create "roles" table
CREATE TABLE "roles" ("id" uuid NOT NULL, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, "deleted_at" timestamptz NULL, "name" character varying NOT NULL, "type" character varying NOT NULL, "application_id" uuid NOT NULL, PRIMARY KEY ("id"));
-- Create index "role_application_id_name" to table: "roles"
CREATE UNIQUE INDEX "role_application_id_name" ON "roles" ("application_id", "name");
-- Create "scopes" table
CREATE TABLE "scopes" ("id" uuid NOT NULL, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, "deleted_at" timestamptz NULL, "name" character varying NOT NULL, "hidden_in_jwt" boolean NOT NULL DEFAULT false, "role_id" uuid NOT NULL, PRIMARY KEY ("id"));
-- Create index "scope_role_id_name" to table: "scopes"
CREATE UNIQUE INDEX "scope_role_id_name" ON "scopes" ("role_id", "name");
-- Create "users" table
CREATE TABLE "users" ("id" character varying NOT NULL, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, "deleted_at" timestamptz NULL, "name" character varying NOT NULL, "display_name" character varying NULL, "avatar" character varying NULL, "referral_channel" jsonb NULL, "application_id" uuid NOT NULL, "user_personal_role" uuid NULL, PRIMARY KEY ("id"));
-- Create index "user_application_id_name" to table: "users"
CREATE UNIQUE INDEX "user_application_id_name" ON "users" ("application_id", "name");
-- Create index "user_name" to table: "users"
CREATE INDEX "user_name" ON "users" ("name");
-- Modify "applications" table
ALTER TABLE "applications" ADD CONSTRAINT "applications_roles_default_org_admin_role" FOREIGN KEY ("application_default_org_admin_role") REFERENCES "roles" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, ADD CONSTRAINT "applications_roles_default_org_role" FOREIGN KEY ("application_default_org_role") REFERENCES "roles" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, ADD CONSTRAINT "applications_roles_default_personal_role" FOREIGN KEY ("application_default_personal_role") REFERENCES "roles" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
-- Modify "bindings" table
ALTER TABLE "bindings" ADD CONSTRAINT "bindings_users_bindings" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
-- Modify "devices" table
ALTER TABLE "devices" ADD CONSTRAINT "devices_users_devices" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
-- Modify "organization_users" table
ALTER TABLE "organization_users" ADD CONSTRAINT "organization_users_organizations_organization" FOREIGN KEY ("organization_id") REFERENCES "organizations" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION, ADD CONSTRAINT "organization_users_roles_role" FOREIGN KEY ("organization_user_role") REFERENCES "roles" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, ADD CONSTRAINT "organization_users_users_user" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
-- Modify "organizations" table
ALTER TABLE "organizations" ADD CONSTRAINT "organizations_applications_organizations" FOREIGN KEY ("application_id") REFERENCES "applications" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
-- Modify "roles" table
ALTER TABLE "roles" ADD CONSTRAINT "roles_applications_roles" FOREIGN KEY ("application_id") REFERENCES "applications" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
-- Modify "scopes" table
ALTER TABLE "scopes" ADD CONSTRAINT "scopes_roles_scopes" FOREIGN KEY ("role_id") REFERENCES "roles" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
-- Modify "users" table
ALTER TABLE "users" ADD CONSTRAINT "users_applications_users" FOREIGN KEY ("application_id") REFERENCES "applications" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION, ADD CONSTRAINT "users_roles_personal_role" FOREIGN KEY ("user_personal_role") REFERENCES "roles" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
