-- Modify "payments" table
ALTER TABLE "payments" ADD COLUMN "payment_type" character varying NOT NULL DEFAULT 'one_time', ADD COLUMN "subscription_id" character varying NULL, ADD COLUMN "subscription_status" character varying NULL, ADD COLUMN "interval" character varying NULL, ADD COLUMN "current_period_start" timestamptz NULL, ADD COLUMN "current_period_end" timestamptz NULL, ADD COLUMN "customer_id" character varying NULL, ADD COLUMN "customer_email" character varying NULL, ADD COLUMN "checkout_session_id" character varying NULL;
-- Create index "payment_checkout_session_id" to table: "payments"
CREATE INDEX "payment_checkout_session_id" ON "payments" ("checkout_session_id");
-- Create index "payment_customer_id" to table: "payments"
CREATE INDEX "payment_customer_id" ON "payments" ("customer_id");
-- Create index "payment_subscription_id" to table: "payments"
CREATE INDEX "payment_subscription_id" ON "payments" ("subscription_id");
-- Create "stripe_events" table
CREATE TABLE "stripe_events" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "created_at" timestamptz NOT NULL,
  "event_id" character varying NOT NULL,
  "event_type" character varying NOT NULL,
  "processed" boolean NOT NULL DEFAULT false,
  "processed_at" timestamptz NULL,
  PRIMARY KEY ("id")
);
-- Create index "stripe_events_event_id_key" to table: "stripe_events"
CREATE UNIQUE INDEX "stripe_events_event_id_key" ON "stripe_events" ("event_id");
-- Create index "stripeevent_event_id" to table: "stripe_events"
CREATE UNIQUE INDEX "stripeevent_event_id" ON "stripe_events" ("event_id");
-- Create index "stripeevent_event_type_processed" to table: "stripe_events"
CREATE INDEX "stripeevent_event_type_processed" ON "stripe_events" ("event_type", "processed");
