// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"kiwi-user/internal/infrastructure/repository/ent/application"
	"kiwi-user/internal/infrastructure/repository/ent/organization"
	"kiwi-user/internal/infrastructure/repository/ent/organizationapplication"
	"kiwi-user/internal/infrastructure/repository/ent/predicate"
	"kiwi-user/internal/infrastructure/repository/ent/role"
	"kiwi-user/internal/infrastructure/repository/ent/user"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// ApplicationUpdate is the builder for updating Application entities.
type ApplicationUpdate struct {
	config
	hooks    []Hook
	mutation *ApplicationMutation
}

// Where appends a list predicates to the ApplicationUpdate builder.
func (au *ApplicationUpdate) Where(ps ...predicate.Application) *ApplicationUpdate {
	au.mutation.Where(ps...)
	return au
}

// SetUpdatedAt sets the "updated_at" field.
func (au *ApplicationUpdate) SetUpdatedAt(t time.Time) *ApplicationUpdate {
	au.mutation.SetUpdatedAt(t)
	return au
}

// SetDeletedAt sets the "deleted_at" field.
func (au *ApplicationUpdate) SetDeletedAt(t time.Time) *ApplicationUpdate {
	au.mutation.SetDeletedAt(t)
	return au
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (au *ApplicationUpdate) SetNillableDeletedAt(t *time.Time) *ApplicationUpdate {
	if t != nil {
		au.SetDeletedAt(*t)
	}
	return au
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (au *ApplicationUpdate) ClearDeletedAt() *ApplicationUpdate {
	au.mutation.ClearDeletedAt()
	return au
}

// SetName sets the "name" field.
func (au *ApplicationUpdate) SetName(s string) *ApplicationUpdate {
	au.mutation.SetName(s)
	return au
}

// SetNillableName sets the "name" field if the given value is not nil.
func (au *ApplicationUpdate) SetNillableName(s *string) *ApplicationUpdate {
	if s != nil {
		au.SetName(*s)
	}
	return au
}

// AddUserIDs adds the "users" edge to the User entity by IDs.
func (au *ApplicationUpdate) AddUserIDs(ids ...string) *ApplicationUpdate {
	au.mutation.AddUserIDs(ids...)
	return au
}

// AddUsers adds the "users" edges to the User entity.
func (au *ApplicationUpdate) AddUsers(u ...*User) *ApplicationUpdate {
	ids := make([]string, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return au.AddUserIDs(ids...)
}

// AddOrganizationIDs adds the "organizations" edge to the Organization entity by IDs.
func (au *ApplicationUpdate) AddOrganizationIDs(ids ...uuid.UUID) *ApplicationUpdate {
	au.mutation.AddOrganizationIDs(ids...)
	return au
}

// AddOrganizations adds the "organizations" edges to the Organization entity.
func (au *ApplicationUpdate) AddOrganizations(o ...*Organization) *ApplicationUpdate {
	ids := make([]uuid.UUID, len(o))
	for i := range o {
		ids[i] = o[i].ID
	}
	return au.AddOrganizationIDs(ids...)
}

// AddRoleIDs adds the "roles" edge to the Role entity by IDs.
func (au *ApplicationUpdate) AddRoleIDs(ids ...uuid.UUID) *ApplicationUpdate {
	au.mutation.AddRoleIDs(ids...)
	return au
}

// AddRoles adds the "roles" edges to the Role entity.
func (au *ApplicationUpdate) AddRoles(r ...*Role) *ApplicationUpdate {
	ids := make([]uuid.UUID, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return au.AddRoleIDs(ids...)
}

// SetDefaultPersonalRoleID sets the "default_personal_role" edge to the Role entity by ID.
func (au *ApplicationUpdate) SetDefaultPersonalRoleID(id uuid.UUID) *ApplicationUpdate {
	au.mutation.SetDefaultPersonalRoleID(id)
	return au
}

// SetNillableDefaultPersonalRoleID sets the "default_personal_role" edge to the Role entity by ID if the given value is not nil.
func (au *ApplicationUpdate) SetNillableDefaultPersonalRoleID(id *uuid.UUID) *ApplicationUpdate {
	if id != nil {
		au = au.SetDefaultPersonalRoleID(*id)
	}
	return au
}

// SetDefaultPersonalRole sets the "default_personal_role" edge to the Role entity.
func (au *ApplicationUpdate) SetDefaultPersonalRole(r *Role) *ApplicationUpdate {
	return au.SetDefaultPersonalRoleID(r.ID)
}

// SetDefaultOrgRoleID sets the "default_org_role" edge to the Role entity by ID.
func (au *ApplicationUpdate) SetDefaultOrgRoleID(id uuid.UUID) *ApplicationUpdate {
	au.mutation.SetDefaultOrgRoleID(id)
	return au
}

// SetNillableDefaultOrgRoleID sets the "default_org_role" edge to the Role entity by ID if the given value is not nil.
func (au *ApplicationUpdate) SetNillableDefaultOrgRoleID(id *uuid.UUID) *ApplicationUpdate {
	if id != nil {
		au = au.SetDefaultOrgRoleID(*id)
	}
	return au
}

// SetDefaultOrgRole sets the "default_org_role" edge to the Role entity.
func (au *ApplicationUpdate) SetDefaultOrgRole(r *Role) *ApplicationUpdate {
	return au.SetDefaultOrgRoleID(r.ID)
}

// SetDefaultOrgAdminRoleID sets the "default_org_admin_role" edge to the Role entity by ID.
func (au *ApplicationUpdate) SetDefaultOrgAdminRoleID(id uuid.UUID) *ApplicationUpdate {
	au.mutation.SetDefaultOrgAdminRoleID(id)
	return au
}

// SetNillableDefaultOrgAdminRoleID sets the "default_org_admin_role" edge to the Role entity by ID if the given value is not nil.
func (au *ApplicationUpdate) SetNillableDefaultOrgAdminRoleID(id *uuid.UUID) *ApplicationUpdate {
	if id != nil {
		au = au.SetDefaultOrgAdminRoleID(*id)
	}
	return au
}

// SetDefaultOrgAdminRole sets the "default_org_admin_role" edge to the Role entity.
func (au *ApplicationUpdate) SetDefaultOrgAdminRole(r *Role) *ApplicationUpdate {
	return au.SetDefaultOrgAdminRoleID(r.ID)
}

// AddOrganizationApplicationIDs adds the "organization_application" edge to the OrganizationApplication entity by IDs.
func (au *ApplicationUpdate) AddOrganizationApplicationIDs(ids ...uuid.UUID) *ApplicationUpdate {
	au.mutation.AddOrganizationApplicationIDs(ids...)
	return au
}

// AddOrganizationApplication adds the "organization_application" edges to the OrganizationApplication entity.
func (au *ApplicationUpdate) AddOrganizationApplication(o ...*OrganizationApplication) *ApplicationUpdate {
	ids := make([]uuid.UUID, len(o))
	for i := range o {
		ids[i] = o[i].ID
	}
	return au.AddOrganizationApplicationIDs(ids...)
}

// Mutation returns the ApplicationMutation object of the builder.
func (au *ApplicationUpdate) Mutation() *ApplicationMutation {
	return au.mutation
}

// ClearUsers clears all "users" edges to the User entity.
func (au *ApplicationUpdate) ClearUsers() *ApplicationUpdate {
	au.mutation.ClearUsers()
	return au
}

// RemoveUserIDs removes the "users" edge to User entities by IDs.
func (au *ApplicationUpdate) RemoveUserIDs(ids ...string) *ApplicationUpdate {
	au.mutation.RemoveUserIDs(ids...)
	return au
}

// RemoveUsers removes "users" edges to User entities.
func (au *ApplicationUpdate) RemoveUsers(u ...*User) *ApplicationUpdate {
	ids := make([]string, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return au.RemoveUserIDs(ids...)
}

// ClearOrganizations clears all "organizations" edges to the Organization entity.
func (au *ApplicationUpdate) ClearOrganizations() *ApplicationUpdate {
	au.mutation.ClearOrganizations()
	return au
}

// RemoveOrganizationIDs removes the "organizations" edge to Organization entities by IDs.
func (au *ApplicationUpdate) RemoveOrganizationIDs(ids ...uuid.UUID) *ApplicationUpdate {
	au.mutation.RemoveOrganizationIDs(ids...)
	return au
}

// RemoveOrganizations removes "organizations" edges to Organization entities.
func (au *ApplicationUpdate) RemoveOrganizations(o ...*Organization) *ApplicationUpdate {
	ids := make([]uuid.UUID, len(o))
	for i := range o {
		ids[i] = o[i].ID
	}
	return au.RemoveOrganizationIDs(ids...)
}

// ClearRoles clears all "roles" edges to the Role entity.
func (au *ApplicationUpdate) ClearRoles() *ApplicationUpdate {
	au.mutation.ClearRoles()
	return au
}

// RemoveRoleIDs removes the "roles" edge to Role entities by IDs.
func (au *ApplicationUpdate) RemoveRoleIDs(ids ...uuid.UUID) *ApplicationUpdate {
	au.mutation.RemoveRoleIDs(ids...)
	return au
}

// RemoveRoles removes "roles" edges to Role entities.
func (au *ApplicationUpdate) RemoveRoles(r ...*Role) *ApplicationUpdate {
	ids := make([]uuid.UUID, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return au.RemoveRoleIDs(ids...)
}

// ClearDefaultPersonalRole clears the "default_personal_role" edge to the Role entity.
func (au *ApplicationUpdate) ClearDefaultPersonalRole() *ApplicationUpdate {
	au.mutation.ClearDefaultPersonalRole()
	return au
}

// ClearDefaultOrgRole clears the "default_org_role" edge to the Role entity.
func (au *ApplicationUpdate) ClearDefaultOrgRole() *ApplicationUpdate {
	au.mutation.ClearDefaultOrgRole()
	return au
}

// ClearDefaultOrgAdminRole clears the "default_org_admin_role" edge to the Role entity.
func (au *ApplicationUpdate) ClearDefaultOrgAdminRole() *ApplicationUpdate {
	au.mutation.ClearDefaultOrgAdminRole()
	return au
}

// ClearOrganizationApplication clears all "organization_application" edges to the OrganizationApplication entity.
func (au *ApplicationUpdate) ClearOrganizationApplication() *ApplicationUpdate {
	au.mutation.ClearOrganizationApplication()
	return au
}

// RemoveOrganizationApplicationIDs removes the "organization_application" edge to OrganizationApplication entities by IDs.
func (au *ApplicationUpdate) RemoveOrganizationApplicationIDs(ids ...uuid.UUID) *ApplicationUpdate {
	au.mutation.RemoveOrganizationApplicationIDs(ids...)
	return au
}

// RemoveOrganizationApplication removes "organization_application" edges to OrganizationApplication entities.
func (au *ApplicationUpdate) RemoveOrganizationApplication(o ...*OrganizationApplication) *ApplicationUpdate {
	ids := make([]uuid.UUID, len(o))
	for i := range o {
		ids[i] = o[i].ID
	}
	return au.RemoveOrganizationApplicationIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (au *ApplicationUpdate) Save(ctx context.Context) (int, error) {
	au.defaults()
	return withHooks(ctx, au.sqlSave, au.mutation, au.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (au *ApplicationUpdate) SaveX(ctx context.Context) int {
	affected, err := au.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (au *ApplicationUpdate) Exec(ctx context.Context) error {
	_, err := au.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (au *ApplicationUpdate) ExecX(ctx context.Context) {
	if err := au.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (au *ApplicationUpdate) defaults() {
	if _, ok := au.mutation.UpdatedAt(); !ok {
		v := application.UpdateDefaultUpdatedAt()
		au.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (au *ApplicationUpdate) check() error {
	if v, ok := au.mutation.Name(); ok {
		if err := application.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Application.name": %w`, err)}
		}
	}
	return nil
}

func (au *ApplicationUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := au.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(application.Table, application.Columns, sqlgraph.NewFieldSpec(application.FieldID, field.TypeUUID))
	if ps := au.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := au.mutation.UpdatedAt(); ok {
		_spec.SetField(application.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := au.mutation.DeletedAt(); ok {
		_spec.SetField(application.FieldDeletedAt, field.TypeTime, value)
	}
	if au.mutation.DeletedAtCleared() {
		_spec.ClearField(application.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := au.mutation.Name(); ok {
		_spec.SetField(application.FieldName, field.TypeString, value)
	}
	if au.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   application.UsersTable,
			Columns: []string{application.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := au.mutation.RemovedUsersIDs(); len(nodes) > 0 && !au.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   application.UsersTable,
			Columns: []string{application.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := au.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   application.UsersTable,
			Columns: []string{application.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if au.mutation.OrganizationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   application.OrganizationsTable,
			Columns: []string{application.OrganizationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := au.mutation.RemovedOrganizationsIDs(); len(nodes) > 0 && !au.mutation.OrganizationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   application.OrganizationsTable,
			Columns: []string{application.OrganizationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := au.mutation.OrganizationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   application.OrganizationsTable,
			Columns: []string{application.OrganizationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if au.mutation.RolesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   application.RolesTable,
			Columns: []string{application.RolesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := au.mutation.RemovedRolesIDs(); len(nodes) > 0 && !au.mutation.RolesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   application.RolesTable,
			Columns: []string{application.RolesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := au.mutation.RolesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   application.RolesTable,
			Columns: []string{application.RolesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if au.mutation.DefaultPersonalRoleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   application.DefaultPersonalRoleTable,
			Columns: []string{application.DefaultPersonalRoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := au.mutation.DefaultPersonalRoleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   application.DefaultPersonalRoleTable,
			Columns: []string{application.DefaultPersonalRoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if au.mutation.DefaultOrgRoleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   application.DefaultOrgRoleTable,
			Columns: []string{application.DefaultOrgRoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := au.mutation.DefaultOrgRoleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   application.DefaultOrgRoleTable,
			Columns: []string{application.DefaultOrgRoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if au.mutation.DefaultOrgAdminRoleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   application.DefaultOrgAdminRoleTable,
			Columns: []string{application.DefaultOrgAdminRoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := au.mutation.DefaultOrgAdminRoleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   application.DefaultOrgAdminRoleTable,
			Columns: []string{application.DefaultOrgAdminRoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if au.mutation.OrganizationApplicationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   application.OrganizationApplicationTable,
			Columns: []string{application.OrganizationApplicationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organizationapplication.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := au.mutation.RemovedOrganizationApplicationIDs(); len(nodes) > 0 && !au.mutation.OrganizationApplicationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   application.OrganizationApplicationTable,
			Columns: []string{application.OrganizationApplicationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organizationapplication.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := au.mutation.OrganizationApplicationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   application.OrganizationApplicationTable,
			Columns: []string{application.OrganizationApplicationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organizationapplication.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, au.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{application.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	au.mutation.done = true
	return n, nil
}

// ApplicationUpdateOne is the builder for updating a single Application entity.
type ApplicationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ApplicationMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (auo *ApplicationUpdateOne) SetUpdatedAt(t time.Time) *ApplicationUpdateOne {
	auo.mutation.SetUpdatedAt(t)
	return auo
}

// SetDeletedAt sets the "deleted_at" field.
func (auo *ApplicationUpdateOne) SetDeletedAt(t time.Time) *ApplicationUpdateOne {
	auo.mutation.SetDeletedAt(t)
	return auo
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (auo *ApplicationUpdateOne) SetNillableDeletedAt(t *time.Time) *ApplicationUpdateOne {
	if t != nil {
		auo.SetDeletedAt(*t)
	}
	return auo
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (auo *ApplicationUpdateOne) ClearDeletedAt() *ApplicationUpdateOne {
	auo.mutation.ClearDeletedAt()
	return auo
}

// SetName sets the "name" field.
func (auo *ApplicationUpdateOne) SetName(s string) *ApplicationUpdateOne {
	auo.mutation.SetName(s)
	return auo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (auo *ApplicationUpdateOne) SetNillableName(s *string) *ApplicationUpdateOne {
	if s != nil {
		auo.SetName(*s)
	}
	return auo
}

// AddUserIDs adds the "users" edge to the User entity by IDs.
func (auo *ApplicationUpdateOne) AddUserIDs(ids ...string) *ApplicationUpdateOne {
	auo.mutation.AddUserIDs(ids...)
	return auo
}

// AddUsers adds the "users" edges to the User entity.
func (auo *ApplicationUpdateOne) AddUsers(u ...*User) *ApplicationUpdateOne {
	ids := make([]string, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return auo.AddUserIDs(ids...)
}

// AddOrganizationIDs adds the "organizations" edge to the Organization entity by IDs.
func (auo *ApplicationUpdateOne) AddOrganizationIDs(ids ...uuid.UUID) *ApplicationUpdateOne {
	auo.mutation.AddOrganizationIDs(ids...)
	return auo
}

// AddOrganizations adds the "organizations" edges to the Organization entity.
func (auo *ApplicationUpdateOne) AddOrganizations(o ...*Organization) *ApplicationUpdateOne {
	ids := make([]uuid.UUID, len(o))
	for i := range o {
		ids[i] = o[i].ID
	}
	return auo.AddOrganizationIDs(ids...)
}

// AddRoleIDs adds the "roles" edge to the Role entity by IDs.
func (auo *ApplicationUpdateOne) AddRoleIDs(ids ...uuid.UUID) *ApplicationUpdateOne {
	auo.mutation.AddRoleIDs(ids...)
	return auo
}

// AddRoles adds the "roles" edges to the Role entity.
func (auo *ApplicationUpdateOne) AddRoles(r ...*Role) *ApplicationUpdateOne {
	ids := make([]uuid.UUID, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return auo.AddRoleIDs(ids...)
}

// SetDefaultPersonalRoleID sets the "default_personal_role" edge to the Role entity by ID.
func (auo *ApplicationUpdateOne) SetDefaultPersonalRoleID(id uuid.UUID) *ApplicationUpdateOne {
	auo.mutation.SetDefaultPersonalRoleID(id)
	return auo
}

// SetNillableDefaultPersonalRoleID sets the "default_personal_role" edge to the Role entity by ID if the given value is not nil.
func (auo *ApplicationUpdateOne) SetNillableDefaultPersonalRoleID(id *uuid.UUID) *ApplicationUpdateOne {
	if id != nil {
		auo = auo.SetDefaultPersonalRoleID(*id)
	}
	return auo
}

// SetDefaultPersonalRole sets the "default_personal_role" edge to the Role entity.
func (auo *ApplicationUpdateOne) SetDefaultPersonalRole(r *Role) *ApplicationUpdateOne {
	return auo.SetDefaultPersonalRoleID(r.ID)
}

// SetDefaultOrgRoleID sets the "default_org_role" edge to the Role entity by ID.
func (auo *ApplicationUpdateOne) SetDefaultOrgRoleID(id uuid.UUID) *ApplicationUpdateOne {
	auo.mutation.SetDefaultOrgRoleID(id)
	return auo
}

// SetNillableDefaultOrgRoleID sets the "default_org_role" edge to the Role entity by ID if the given value is not nil.
func (auo *ApplicationUpdateOne) SetNillableDefaultOrgRoleID(id *uuid.UUID) *ApplicationUpdateOne {
	if id != nil {
		auo = auo.SetDefaultOrgRoleID(*id)
	}
	return auo
}

// SetDefaultOrgRole sets the "default_org_role" edge to the Role entity.
func (auo *ApplicationUpdateOne) SetDefaultOrgRole(r *Role) *ApplicationUpdateOne {
	return auo.SetDefaultOrgRoleID(r.ID)
}

// SetDefaultOrgAdminRoleID sets the "default_org_admin_role" edge to the Role entity by ID.
func (auo *ApplicationUpdateOne) SetDefaultOrgAdminRoleID(id uuid.UUID) *ApplicationUpdateOne {
	auo.mutation.SetDefaultOrgAdminRoleID(id)
	return auo
}

// SetNillableDefaultOrgAdminRoleID sets the "default_org_admin_role" edge to the Role entity by ID if the given value is not nil.
func (auo *ApplicationUpdateOne) SetNillableDefaultOrgAdminRoleID(id *uuid.UUID) *ApplicationUpdateOne {
	if id != nil {
		auo = auo.SetDefaultOrgAdminRoleID(*id)
	}
	return auo
}

// SetDefaultOrgAdminRole sets the "default_org_admin_role" edge to the Role entity.
func (auo *ApplicationUpdateOne) SetDefaultOrgAdminRole(r *Role) *ApplicationUpdateOne {
	return auo.SetDefaultOrgAdminRoleID(r.ID)
}

// AddOrganizationApplicationIDs adds the "organization_application" edge to the OrganizationApplication entity by IDs.
func (auo *ApplicationUpdateOne) AddOrganizationApplicationIDs(ids ...uuid.UUID) *ApplicationUpdateOne {
	auo.mutation.AddOrganizationApplicationIDs(ids...)
	return auo
}

// AddOrganizationApplication adds the "organization_application" edges to the OrganizationApplication entity.
func (auo *ApplicationUpdateOne) AddOrganizationApplication(o ...*OrganizationApplication) *ApplicationUpdateOne {
	ids := make([]uuid.UUID, len(o))
	for i := range o {
		ids[i] = o[i].ID
	}
	return auo.AddOrganizationApplicationIDs(ids...)
}

// Mutation returns the ApplicationMutation object of the builder.
func (auo *ApplicationUpdateOne) Mutation() *ApplicationMutation {
	return auo.mutation
}

// ClearUsers clears all "users" edges to the User entity.
func (auo *ApplicationUpdateOne) ClearUsers() *ApplicationUpdateOne {
	auo.mutation.ClearUsers()
	return auo
}

// RemoveUserIDs removes the "users" edge to User entities by IDs.
func (auo *ApplicationUpdateOne) RemoveUserIDs(ids ...string) *ApplicationUpdateOne {
	auo.mutation.RemoveUserIDs(ids...)
	return auo
}

// RemoveUsers removes "users" edges to User entities.
func (auo *ApplicationUpdateOne) RemoveUsers(u ...*User) *ApplicationUpdateOne {
	ids := make([]string, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return auo.RemoveUserIDs(ids...)
}

// ClearOrganizations clears all "organizations" edges to the Organization entity.
func (auo *ApplicationUpdateOne) ClearOrganizations() *ApplicationUpdateOne {
	auo.mutation.ClearOrganizations()
	return auo
}

// RemoveOrganizationIDs removes the "organizations" edge to Organization entities by IDs.
func (auo *ApplicationUpdateOne) RemoveOrganizationIDs(ids ...uuid.UUID) *ApplicationUpdateOne {
	auo.mutation.RemoveOrganizationIDs(ids...)
	return auo
}

// RemoveOrganizations removes "organizations" edges to Organization entities.
func (auo *ApplicationUpdateOne) RemoveOrganizations(o ...*Organization) *ApplicationUpdateOne {
	ids := make([]uuid.UUID, len(o))
	for i := range o {
		ids[i] = o[i].ID
	}
	return auo.RemoveOrganizationIDs(ids...)
}

// ClearRoles clears all "roles" edges to the Role entity.
func (auo *ApplicationUpdateOne) ClearRoles() *ApplicationUpdateOne {
	auo.mutation.ClearRoles()
	return auo
}

// RemoveRoleIDs removes the "roles" edge to Role entities by IDs.
func (auo *ApplicationUpdateOne) RemoveRoleIDs(ids ...uuid.UUID) *ApplicationUpdateOne {
	auo.mutation.RemoveRoleIDs(ids...)
	return auo
}

// RemoveRoles removes "roles" edges to Role entities.
func (auo *ApplicationUpdateOne) RemoveRoles(r ...*Role) *ApplicationUpdateOne {
	ids := make([]uuid.UUID, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return auo.RemoveRoleIDs(ids...)
}

// ClearDefaultPersonalRole clears the "default_personal_role" edge to the Role entity.
func (auo *ApplicationUpdateOne) ClearDefaultPersonalRole() *ApplicationUpdateOne {
	auo.mutation.ClearDefaultPersonalRole()
	return auo
}

// ClearDefaultOrgRole clears the "default_org_role" edge to the Role entity.
func (auo *ApplicationUpdateOne) ClearDefaultOrgRole() *ApplicationUpdateOne {
	auo.mutation.ClearDefaultOrgRole()
	return auo
}

// ClearDefaultOrgAdminRole clears the "default_org_admin_role" edge to the Role entity.
func (auo *ApplicationUpdateOne) ClearDefaultOrgAdminRole() *ApplicationUpdateOne {
	auo.mutation.ClearDefaultOrgAdminRole()
	return auo
}

// ClearOrganizationApplication clears all "organization_application" edges to the OrganizationApplication entity.
func (auo *ApplicationUpdateOne) ClearOrganizationApplication() *ApplicationUpdateOne {
	auo.mutation.ClearOrganizationApplication()
	return auo
}

// RemoveOrganizationApplicationIDs removes the "organization_application" edge to OrganizationApplication entities by IDs.
func (auo *ApplicationUpdateOne) RemoveOrganizationApplicationIDs(ids ...uuid.UUID) *ApplicationUpdateOne {
	auo.mutation.RemoveOrganizationApplicationIDs(ids...)
	return auo
}

// RemoveOrganizationApplication removes "organization_application" edges to OrganizationApplication entities.
func (auo *ApplicationUpdateOne) RemoveOrganizationApplication(o ...*OrganizationApplication) *ApplicationUpdateOne {
	ids := make([]uuid.UUID, len(o))
	for i := range o {
		ids[i] = o[i].ID
	}
	return auo.RemoveOrganizationApplicationIDs(ids...)
}

// Where appends a list predicates to the ApplicationUpdate builder.
func (auo *ApplicationUpdateOne) Where(ps ...predicate.Application) *ApplicationUpdateOne {
	auo.mutation.Where(ps...)
	return auo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (auo *ApplicationUpdateOne) Select(field string, fields ...string) *ApplicationUpdateOne {
	auo.fields = append([]string{field}, fields...)
	return auo
}

// Save executes the query and returns the updated Application entity.
func (auo *ApplicationUpdateOne) Save(ctx context.Context) (*Application, error) {
	auo.defaults()
	return withHooks(ctx, auo.sqlSave, auo.mutation, auo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (auo *ApplicationUpdateOne) SaveX(ctx context.Context) *Application {
	node, err := auo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (auo *ApplicationUpdateOne) Exec(ctx context.Context) error {
	_, err := auo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (auo *ApplicationUpdateOne) ExecX(ctx context.Context) {
	if err := auo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (auo *ApplicationUpdateOne) defaults() {
	if _, ok := auo.mutation.UpdatedAt(); !ok {
		v := application.UpdateDefaultUpdatedAt()
		auo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (auo *ApplicationUpdateOne) check() error {
	if v, ok := auo.mutation.Name(); ok {
		if err := application.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Application.name": %w`, err)}
		}
	}
	return nil
}

func (auo *ApplicationUpdateOne) sqlSave(ctx context.Context) (_node *Application, err error) {
	if err := auo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(application.Table, application.Columns, sqlgraph.NewFieldSpec(application.FieldID, field.TypeUUID))
	id, ok := auo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Application.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := auo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, application.FieldID)
		for _, f := range fields {
			if !application.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != application.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := auo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := auo.mutation.UpdatedAt(); ok {
		_spec.SetField(application.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := auo.mutation.DeletedAt(); ok {
		_spec.SetField(application.FieldDeletedAt, field.TypeTime, value)
	}
	if auo.mutation.DeletedAtCleared() {
		_spec.ClearField(application.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := auo.mutation.Name(); ok {
		_spec.SetField(application.FieldName, field.TypeString, value)
	}
	if auo.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   application.UsersTable,
			Columns: []string{application.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := auo.mutation.RemovedUsersIDs(); len(nodes) > 0 && !auo.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   application.UsersTable,
			Columns: []string{application.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := auo.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   application.UsersTable,
			Columns: []string{application.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if auo.mutation.OrganizationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   application.OrganizationsTable,
			Columns: []string{application.OrganizationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := auo.mutation.RemovedOrganizationsIDs(); len(nodes) > 0 && !auo.mutation.OrganizationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   application.OrganizationsTable,
			Columns: []string{application.OrganizationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := auo.mutation.OrganizationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   application.OrganizationsTable,
			Columns: []string{application.OrganizationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if auo.mutation.RolesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   application.RolesTable,
			Columns: []string{application.RolesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := auo.mutation.RemovedRolesIDs(); len(nodes) > 0 && !auo.mutation.RolesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   application.RolesTable,
			Columns: []string{application.RolesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := auo.mutation.RolesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   application.RolesTable,
			Columns: []string{application.RolesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if auo.mutation.DefaultPersonalRoleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   application.DefaultPersonalRoleTable,
			Columns: []string{application.DefaultPersonalRoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := auo.mutation.DefaultPersonalRoleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   application.DefaultPersonalRoleTable,
			Columns: []string{application.DefaultPersonalRoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if auo.mutation.DefaultOrgRoleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   application.DefaultOrgRoleTable,
			Columns: []string{application.DefaultOrgRoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := auo.mutation.DefaultOrgRoleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   application.DefaultOrgRoleTable,
			Columns: []string{application.DefaultOrgRoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if auo.mutation.DefaultOrgAdminRoleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   application.DefaultOrgAdminRoleTable,
			Columns: []string{application.DefaultOrgAdminRoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := auo.mutation.DefaultOrgAdminRoleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   application.DefaultOrgAdminRoleTable,
			Columns: []string{application.DefaultOrgAdminRoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if auo.mutation.OrganizationApplicationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   application.OrganizationApplicationTable,
			Columns: []string{application.OrganizationApplicationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organizationapplication.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := auo.mutation.RemovedOrganizationApplicationIDs(); len(nodes) > 0 && !auo.mutation.OrganizationApplicationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   application.OrganizationApplicationTable,
			Columns: []string{application.OrganizationApplicationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organizationapplication.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := auo.mutation.OrganizationApplicationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   application.OrganizationApplicationTable,
			Columns: []string{application.OrganizationApplicationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organizationapplication.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Application{config: auo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, auo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{application.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	auo.mutation.done = true
	return _node, nil
}
