// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"kiwi-user/internal/infrastructure/repository/ent/application"
	"kiwi-user/internal/infrastructure/repository/ent/role"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// Application is the model entity for the Application schema.
type Application struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt time.Time `json:"deleted_at,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ApplicationQuery when eager-loading is set.
	Edges                              ApplicationEdges `json:"edges"`
	application_default_personal_role  *uuid.UUID
	application_default_org_role       *uuid.UUID
	application_default_org_admin_role *uuid.UUID
	selectValues                       sql.SelectValues
}

// ApplicationEdges holds the relations/edges for other nodes in the graph.
type ApplicationEdges struct {
	// Users holds the value of the users edge.
	Users []*User `json:"users,omitempty"`
	// Organizations holds the value of the organizations edge.
	Organizations []*Organization `json:"organizations,omitempty"`
	// Roles holds the value of the roles edge.
	Roles []*Role `json:"roles,omitempty"`
	// DefaultPersonalRole holds the value of the default_personal_role edge.
	DefaultPersonalRole *Role `json:"default_personal_role,omitempty"`
	// DefaultOrgRole holds the value of the default_org_role edge.
	DefaultOrgRole *Role `json:"default_org_role,omitempty"`
	// DefaultOrgAdminRole holds the value of the default_org_admin_role edge.
	DefaultOrgAdminRole *Role `json:"default_org_admin_role,omitempty"`
	// OrganizationApplication holds the value of the organization_application edge.
	OrganizationApplication []*OrganizationApplication `json:"organization_application,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [7]bool
}

// UsersOrErr returns the Users value or an error if the edge
// was not loaded in eager-loading.
func (e ApplicationEdges) UsersOrErr() ([]*User, error) {
	if e.loadedTypes[0] {
		return e.Users, nil
	}
	return nil, &NotLoadedError{edge: "users"}
}

// OrganizationsOrErr returns the Organizations value or an error if the edge
// was not loaded in eager-loading.
func (e ApplicationEdges) OrganizationsOrErr() ([]*Organization, error) {
	if e.loadedTypes[1] {
		return e.Organizations, nil
	}
	return nil, &NotLoadedError{edge: "organizations"}
}

// RolesOrErr returns the Roles value or an error if the edge
// was not loaded in eager-loading.
func (e ApplicationEdges) RolesOrErr() ([]*Role, error) {
	if e.loadedTypes[2] {
		return e.Roles, nil
	}
	return nil, &NotLoadedError{edge: "roles"}
}

// DefaultPersonalRoleOrErr returns the DefaultPersonalRole value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ApplicationEdges) DefaultPersonalRoleOrErr() (*Role, error) {
	if e.DefaultPersonalRole != nil {
		return e.DefaultPersonalRole, nil
	} else if e.loadedTypes[3] {
		return nil, &NotFoundError{label: role.Label}
	}
	return nil, &NotLoadedError{edge: "default_personal_role"}
}

// DefaultOrgRoleOrErr returns the DefaultOrgRole value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ApplicationEdges) DefaultOrgRoleOrErr() (*Role, error) {
	if e.DefaultOrgRole != nil {
		return e.DefaultOrgRole, nil
	} else if e.loadedTypes[4] {
		return nil, &NotFoundError{label: role.Label}
	}
	return nil, &NotLoadedError{edge: "default_org_role"}
}

// DefaultOrgAdminRoleOrErr returns the DefaultOrgAdminRole value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ApplicationEdges) DefaultOrgAdminRoleOrErr() (*Role, error) {
	if e.DefaultOrgAdminRole != nil {
		return e.DefaultOrgAdminRole, nil
	} else if e.loadedTypes[5] {
		return nil, &NotFoundError{label: role.Label}
	}
	return nil, &NotLoadedError{edge: "default_org_admin_role"}
}

// OrganizationApplicationOrErr returns the OrganizationApplication value or an error if the edge
// was not loaded in eager-loading.
func (e ApplicationEdges) OrganizationApplicationOrErr() ([]*OrganizationApplication, error) {
	if e.loadedTypes[6] {
		return e.OrganizationApplication, nil
	}
	return nil, &NotLoadedError{edge: "organization_application"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Application) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case application.FieldName:
			values[i] = new(sql.NullString)
		case application.FieldCreatedAt, application.FieldUpdatedAt, application.FieldDeletedAt:
			values[i] = new(sql.NullTime)
		case application.FieldID:
			values[i] = new(uuid.UUID)
		case application.ForeignKeys[0]: // application_default_personal_role
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case application.ForeignKeys[1]: // application_default_org_role
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case application.ForeignKeys[2]: // application_default_org_admin_role
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Application fields.
func (a *Application) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case application.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				a.ID = *value
			}
		case application.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				a.CreatedAt = value.Time
			}
		case application.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				a.UpdatedAt = value.Time
			}
		case application.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				a.DeletedAt = value.Time
			}
		case application.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				a.Name = value.String
			}
		case application.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field application_default_personal_role", values[i])
			} else if value.Valid {
				a.application_default_personal_role = new(uuid.UUID)
				*a.application_default_personal_role = *value.S.(*uuid.UUID)
			}
		case application.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field application_default_org_role", values[i])
			} else if value.Valid {
				a.application_default_org_role = new(uuid.UUID)
				*a.application_default_org_role = *value.S.(*uuid.UUID)
			}
		case application.ForeignKeys[2]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field application_default_org_admin_role", values[i])
			} else if value.Valid {
				a.application_default_org_admin_role = new(uuid.UUID)
				*a.application_default_org_admin_role = *value.S.(*uuid.UUID)
			}
		default:
			a.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Application.
// This includes values selected through modifiers, order, etc.
func (a *Application) Value(name string) (ent.Value, error) {
	return a.selectValues.Get(name)
}

// QueryUsers queries the "users" edge of the Application entity.
func (a *Application) QueryUsers() *UserQuery {
	return NewApplicationClient(a.config).QueryUsers(a)
}

// QueryOrganizations queries the "organizations" edge of the Application entity.
func (a *Application) QueryOrganizations() *OrganizationQuery {
	return NewApplicationClient(a.config).QueryOrganizations(a)
}

// QueryRoles queries the "roles" edge of the Application entity.
func (a *Application) QueryRoles() *RoleQuery {
	return NewApplicationClient(a.config).QueryRoles(a)
}

// QueryDefaultPersonalRole queries the "default_personal_role" edge of the Application entity.
func (a *Application) QueryDefaultPersonalRole() *RoleQuery {
	return NewApplicationClient(a.config).QueryDefaultPersonalRole(a)
}

// QueryDefaultOrgRole queries the "default_org_role" edge of the Application entity.
func (a *Application) QueryDefaultOrgRole() *RoleQuery {
	return NewApplicationClient(a.config).QueryDefaultOrgRole(a)
}

// QueryDefaultOrgAdminRole queries the "default_org_admin_role" edge of the Application entity.
func (a *Application) QueryDefaultOrgAdminRole() *RoleQuery {
	return NewApplicationClient(a.config).QueryDefaultOrgAdminRole(a)
}

// QueryOrganizationApplication queries the "organization_application" edge of the Application entity.
func (a *Application) QueryOrganizationApplication() *OrganizationApplicationQuery {
	return NewApplicationClient(a.config).QueryOrganizationApplication(a)
}

// Update returns a builder for updating this Application.
// Note that you need to call Application.Unwrap() before calling this method if this Application
// was returned from a transaction, and the transaction was committed or rolled back.
func (a *Application) Update() *ApplicationUpdateOne {
	return NewApplicationClient(a.config).UpdateOne(a)
}

// Unwrap unwraps the Application entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (a *Application) Unwrap() *Application {
	_tx, ok := a.config.driver.(*txDriver)
	if !ok {
		panic("ent: Application is not a transactional entity")
	}
	a.config.driver = _tx.drv
	return a
}

// String implements the fmt.Stringer.
func (a *Application) String() string {
	var builder strings.Builder
	builder.WriteString("Application(")
	builder.WriteString(fmt.Sprintf("id=%v, ", a.ID))
	builder.WriteString("created_at=")
	builder.WriteString(a.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(a.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("deleted_at=")
	builder.WriteString(a.DeletedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(a.Name)
	builder.WriteByte(')')
	return builder.String()
}

// Applications is a parsable slice of Application.
type Applications []*Application
