// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"kiwi-user/internal/infrastructure/repository/ent/mailvertifycode"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// MailVertifyCode is the model entity for the MailVertifyCode schema.
type MailVertifyCode struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt time.Time `json:"deleted_at,omitempty"`
	// Type holds the value of the "type" field.
	Type mailvertifycode.Type `json:"type,omitempty"`
	// Email holds the value of the "email" field.
	Email string `json:"email,omitempty"`
	// Code holds the value of the "code" field.
	Code string `json:"code,omitempty"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt    time.Time `json:"expires_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*MailVertifyCode) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case mailvertifycode.FieldType, mailvertifycode.FieldEmail, mailvertifycode.FieldCode:
			values[i] = new(sql.NullString)
		case mailvertifycode.FieldCreatedAt, mailvertifycode.FieldUpdatedAt, mailvertifycode.FieldDeletedAt, mailvertifycode.FieldExpiresAt:
			values[i] = new(sql.NullTime)
		case mailvertifycode.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the MailVertifyCode fields.
func (mvc *MailVertifyCode) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case mailvertifycode.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				mvc.ID = *value
			}
		case mailvertifycode.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				mvc.CreatedAt = value.Time
			}
		case mailvertifycode.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				mvc.UpdatedAt = value.Time
			}
		case mailvertifycode.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				mvc.DeletedAt = value.Time
			}
		case mailvertifycode.FieldType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				mvc.Type = mailvertifycode.Type(value.String)
			}
		case mailvertifycode.FieldEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field email", values[i])
			} else if value.Valid {
				mvc.Email = value.String
			}
		case mailvertifycode.FieldCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field code", values[i])
			} else if value.Valid {
				mvc.Code = value.String
			}
		case mailvertifycode.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				mvc.ExpiresAt = value.Time
			}
		default:
			mvc.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the MailVertifyCode.
// This includes values selected through modifiers, order, etc.
func (mvc *MailVertifyCode) Value(name string) (ent.Value, error) {
	return mvc.selectValues.Get(name)
}

// Update returns a builder for updating this MailVertifyCode.
// Note that you need to call MailVertifyCode.Unwrap() before calling this method if this MailVertifyCode
// was returned from a transaction, and the transaction was committed or rolled back.
func (mvc *MailVertifyCode) Update() *MailVertifyCodeUpdateOne {
	return NewMailVertifyCodeClient(mvc.config).UpdateOne(mvc)
}

// Unwrap unwraps the MailVertifyCode entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (mvc *MailVertifyCode) Unwrap() *MailVertifyCode {
	_tx, ok := mvc.config.driver.(*txDriver)
	if !ok {
		panic("ent: MailVertifyCode is not a transactional entity")
	}
	mvc.config.driver = _tx.drv
	return mvc
}

// String implements the fmt.Stringer.
func (mvc *MailVertifyCode) String() string {
	var builder strings.Builder
	builder.WriteString("MailVertifyCode(")
	builder.WriteString(fmt.Sprintf("id=%v, ", mvc.ID))
	builder.WriteString("created_at=")
	builder.WriteString(mvc.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(mvc.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("deleted_at=")
	builder.WriteString(mvc.DeletedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("type=")
	builder.WriteString(fmt.Sprintf("%v", mvc.Type))
	builder.WriteString(", ")
	builder.WriteString("email=")
	builder.WriteString(mvc.Email)
	builder.WriteString(", ")
	builder.WriteString("code=")
	builder.WriteString(mvc.Code)
	builder.WriteString(", ")
	builder.WriteString("expires_at=")
	builder.WriteString(mvc.ExpiresAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// MailVertifyCodes is a parsable slice of MailVertifyCode.
type MailVertifyCodes []*MailVertifyCode
