// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"kiwi-user/internal/infrastructure/repository/ent/application"
	"kiwi-user/internal/infrastructure/repository/ent/organizationapplication"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// OrganizationApplication is the model entity for the OrganizationApplication schema.
type OrganizationApplication struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt time.Time `json:"deleted_at,omitempty"`
	// ApplicationID holds the value of the "application_id" field.
	ApplicationID uuid.UUID `json:"application_id,omitempty"`
	// 企业名称
	Name string `json:"name,omitempty"`
	// Status holds the value of the "status" field.
	Status organizationapplication.Status `json:"status,omitempty"`
	// 试用天数
	TrialDays int32 `json:"trial_days,omitempty"`
	// ReviewStatus holds the value of the "review_status" field.
	ReviewStatus organizationapplication.ReviewStatus `json:"review_status,omitempty"`
	// 审核描述
	ReviewComment string `json:"review_comment,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID string `json:"user_id,omitempty"`
	// 企业简称
	BrandShortName string `json:"brand_short_name,omitempty"`
	// 主营业务
	PrimaryBusiness string `json:"primary_business,omitempty"`
	// 使用诉求
	UsageScenario string `json:"usage_scenario,omitempty"`
	// 推荐人
	ReferrerName string `json:"referrer_name,omitempty"`
	// 发现途径
	DiscoveryWay string `json:"discovery_way,omitempty"`
	// 组织角色名称
	OrgRoleName string `json:"org_role_name,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the OrganizationApplicationQuery when eager-loading is set.
	Edges        OrganizationApplicationEdges `json:"edges"`
	selectValues sql.SelectValues
}

// OrganizationApplicationEdges holds the relations/edges for other nodes in the graph.
type OrganizationApplicationEdges struct {
	// Application holds the value of the application edge.
	Application *Application `json:"application,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ApplicationOrErr returns the Application value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e OrganizationApplicationEdges) ApplicationOrErr() (*Application, error) {
	if e.Application != nil {
		return e.Application, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: application.Label}
	}
	return nil, &NotLoadedError{edge: "application"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*OrganizationApplication) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case organizationapplication.FieldTrialDays:
			values[i] = new(sql.NullInt64)
		case organizationapplication.FieldName, organizationapplication.FieldStatus, organizationapplication.FieldReviewStatus, organizationapplication.FieldReviewComment, organizationapplication.FieldUserID, organizationapplication.FieldBrandShortName, organizationapplication.FieldPrimaryBusiness, organizationapplication.FieldUsageScenario, organizationapplication.FieldReferrerName, organizationapplication.FieldDiscoveryWay, organizationapplication.FieldOrgRoleName:
			values[i] = new(sql.NullString)
		case organizationapplication.FieldCreatedAt, organizationapplication.FieldUpdatedAt, organizationapplication.FieldDeletedAt:
			values[i] = new(sql.NullTime)
		case organizationapplication.FieldID, organizationapplication.FieldApplicationID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the OrganizationApplication fields.
func (oa *OrganizationApplication) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case organizationapplication.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				oa.ID = *value
			}
		case organizationapplication.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				oa.CreatedAt = value.Time
			}
		case organizationapplication.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				oa.UpdatedAt = value.Time
			}
		case organizationapplication.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				oa.DeletedAt = value.Time
			}
		case organizationapplication.FieldApplicationID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field application_id", values[i])
			} else if value != nil {
				oa.ApplicationID = *value
			}
		case organizationapplication.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				oa.Name = value.String
			}
		case organizationapplication.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				oa.Status = organizationapplication.Status(value.String)
			}
		case organizationapplication.FieldTrialDays:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field trial_days", values[i])
			} else if value.Valid {
				oa.TrialDays = int32(value.Int64)
			}
		case organizationapplication.FieldReviewStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field review_status", values[i])
			} else if value.Valid {
				oa.ReviewStatus = organizationapplication.ReviewStatus(value.String)
			}
		case organizationapplication.FieldReviewComment:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field review_comment", values[i])
			} else if value.Valid {
				oa.ReviewComment = value.String
			}
		case organizationapplication.FieldUserID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				oa.UserID = value.String
			}
		case organizationapplication.FieldBrandShortName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field brand_short_name", values[i])
			} else if value.Valid {
				oa.BrandShortName = value.String
			}
		case organizationapplication.FieldPrimaryBusiness:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field primary_business", values[i])
			} else if value.Valid {
				oa.PrimaryBusiness = value.String
			}
		case organizationapplication.FieldUsageScenario:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field usage_scenario", values[i])
			} else if value.Valid {
				oa.UsageScenario = value.String
			}
		case organizationapplication.FieldReferrerName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field referrer_name", values[i])
			} else if value.Valid {
				oa.ReferrerName = value.String
			}
		case organizationapplication.FieldDiscoveryWay:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field discovery_way", values[i])
			} else if value.Valid {
				oa.DiscoveryWay = value.String
			}
		case organizationapplication.FieldOrgRoleName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field org_role_name", values[i])
			} else if value.Valid {
				oa.OrgRoleName = value.String
			}
		default:
			oa.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the OrganizationApplication.
// This includes values selected through modifiers, order, etc.
func (oa *OrganizationApplication) Value(name string) (ent.Value, error) {
	return oa.selectValues.Get(name)
}

// QueryApplication queries the "application" edge of the OrganizationApplication entity.
func (oa *OrganizationApplication) QueryApplication() *ApplicationQuery {
	return NewOrganizationApplicationClient(oa.config).QueryApplication(oa)
}

// Update returns a builder for updating this OrganizationApplication.
// Note that you need to call OrganizationApplication.Unwrap() before calling this method if this OrganizationApplication
// was returned from a transaction, and the transaction was committed or rolled back.
func (oa *OrganizationApplication) Update() *OrganizationApplicationUpdateOne {
	return NewOrganizationApplicationClient(oa.config).UpdateOne(oa)
}

// Unwrap unwraps the OrganizationApplication entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (oa *OrganizationApplication) Unwrap() *OrganizationApplication {
	_tx, ok := oa.config.driver.(*txDriver)
	if !ok {
		panic("ent: OrganizationApplication is not a transactional entity")
	}
	oa.config.driver = _tx.drv
	return oa
}

// String implements the fmt.Stringer.
func (oa *OrganizationApplication) String() string {
	var builder strings.Builder
	builder.WriteString("OrganizationApplication(")
	builder.WriteString(fmt.Sprintf("id=%v, ", oa.ID))
	builder.WriteString("created_at=")
	builder.WriteString(oa.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(oa.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("deleted_at=")
	builder.WriteString(oa.DeletedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("application_id=")
	builder.WriteString(fmt.Sprintf("%v", oa.ApplicationID))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(oa.Name)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", oa.Status))
	builder.WriteString(", ")
	builder.WriteString("trial_days=")
	builder.WriteString(fmt.Sprintf("%v", oa.TrialDays))
	builder.WriteString(", ")
	builder.WriteString("review_status=")
	builder.WriteString(fmt.Sprintf("%v", oa.ReviewStatus))
	builder.WriteString(", ")
	builder.WriteString("review_comment=")
	builder.WriteString(oa.ReviewComment)
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(oa.UserID)
	builder.WriteString(", ")
	builder.WriteString("brand_short_name=")
	builder.WriteString(oa.BrandShortName)
	builder.WriteString(", ")
	builder.WriteString("primary_business=")
	builder.WriteString(oa.PrimaryBusiness)
	builder.WriteString(", ")
	builder.WriteString("usage_scenario=")
	builder.WriteString(oa.UsageScenario)
	builder.WriteString(", ")
	builder.WriteString("referrer_name=")
	builder.WriteString(oa.ReferrerName)
	builder.WriteString(", ")
	builder.WriteString("discovery_way=")
	builder.WriteString(oa.DiscoveryWay)
	builder.WriteString(", ")
	builder.WriteString("org_role_name=")
	builder.WriteString(oa.OrgRoleName)
	builder.WriteByte(')')
	return builder.String()
}

// OrganizationApplications is a parsable slice of OrganizationApplication.
type OrganizationApplications []*OrganizationApplication
