// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"kiwi-user/internal/infrastructure/repository/ent/organization"
	"kiwi-user/internal/infrastructure/repository/ent/organizationuser"
	"kiwi-user/internal/infrastructure/repository/ent/predicate"
	"kiwi-user/internal/infrastructure/repository/ent/role"
	"kiwi-user/internal/infrastructure/repository/ent/user"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// OrganizationUserUpdate is the builder for updating OrganizationUser entities.
type OrganizationUserUpdate struct {
	config
	hooks    []Hook
	mutation *OrganizationUserMutation
}

// Where appends a list predicates to the OrganizationUserUpdate builder.
func (ouu *OrganizationUserUpdate) Where(ps ...predicate.OrganizationUser) *OrganizationUserUpdate {
	ouu.mutation.Where(ps...)
	return ouu
}

// SetUpdatedAt sets the "updated_at" field.
func (ouu *OrganizationUserUpdate) SetUpdatedAt(t time.Time) *OrganizationUserUpdate {
	ouu.mutation.SetUpdatedAt(t)
	return ouu
}

// SetDeletedAt sets the "deleted_at" field.
func (ouu *OrganizationUserUpdate) SetDeletedAt(t time.Time) *OrganizationUserUpdate {
	ouu.mutation.SetDeletedAt(t)
	return ouu
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (ouu *OrganizationUserUpdate) SetNillableDeletedAt(t *time.Time) *OrganizationUserUpdate {
	if t != nil {
		ouu.SetDeletedAt(*t)
	}
	return ouu
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (ouu *OrganizationUserUpdate) ClearDeletedAt() *OrganizationUserUpdate {
	ouu.mutation.ClearDeletedAt()
	return ouu
}

// SetOrganizationID sets the "organization_id" field.
func (ouu *OrganizationUserUpdate) SetOrganizationID(u uuid.UUID) *OrganizationUserUpdate {
	ouu.mutation.SetOrganizationID(u)
	return ouu
}

// SetNillableOrganizationID sets the "organization_id" field if the given value is not nil.
func (ouu *OrganizationUserUpdate) SetNillableOrganizationID(u *uuid.UUID) *OrganizationUserUpdate {
	if u != nil {
		ouu.SetOrganizationID(*u)
	}
	return ouu
}

// SetUserID sets the "user_id" field.
func (ouu *OrganizationUserUpdate) SetUserID(s string) *OrganizationUserUpdate {
	ouu.mutation.SetUserID(s)
	return ouu
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (ouu *OrganizationUserUpdate) SetNillableUserID(s *string) *OrganizationUserUpdate {
	if s != nil {
		ouu.SetUserID(*s)
	}
	return ouu
}

// SetOrganization sets the "organization" edge to the Organization entity.
func (ouu *OrganizationUserUpdate) SetOrganization(o *Organization) *OrganizationUserUpdate {
	return ouu.SetOrganizationID(o.ID)
}

// SetUser sets the "user" edge to the User entity.
func (ouu *OrganizationUserUpdate) SetUser(u *User) *OrganizationUserUpdate {
	return ouu.SetUserID(u.ID)
}

// SetRoleID sets the "role" edge to the Role entity by ID.
func (ouu *OrganizationUserUpdate) SetRoleID(id uuid.UUID) *OrganizationUserUpdate {
	ouu.mutation.SetRoleID(id)
	return ouu
}

// SetNillableRoleID sets the "role" edge to the Role entity by ID if the given value is not nil.
func (ouu *OrganizationUserUpdate) SetNillableRoleID(id *uuid.UUID) *OrganizationUserUpdate {
	if id != nil {
		ouu = ouu.SetRoleID(*id)
	}
	return ouu
}

// SetRole sets the "role" edge to the Role entity.
func (ouu *OrganizationUserUpdate) SetRole(r *Role) *OrganizationUserUpdate {
	return ouu.SetRoleID(r.ID)
}

// Mutation returns the OrganizationUserMutation object of the builder.
func (ouu *OrganizationUserUpdate) Mutation() *OrganizationUserMutation {
	return ouu.mutation
}

// ClearOrganization clears the "organization" edge to the Organization entity.
func (ouu *OrganizationUserUpdate) ClearOrganization() *OrganizationUserUpdate {
	ouu.mutation.ClearOrganization()
	return ouu
}

// ClearUser clears the "user" edge to the User entity.
func (ouu *OrganizationUserUpdate) ClearUser() *OrganizationUserUpdate {
	ouu.mutation.ClearUser()
	return ouu
}

// ClearRole clears the "role" edge to the Role entity.
func (ouu *OrganizationUserUpdate) ClearRole() *OrganizationUserUpdate {
	ouu.mutation.ClearRole()
	return ouu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (ouu *OrganizationUserUpdate) Save(ctx context.Context) (int, error) {
	ouu.defaults()
	return withHooks(ctx, ouu.sqlSave, ouu.mutation, ouu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ouu *OrganizationUserUpdate) SaveX(ctx context.Context) int {
	affected, err := ouu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ouu *OrganizationUserUpdate) Exec(ctx context.Context) error {
	_, err := ouu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ouu *OrganizationUserUpdate) ExecX(ctx context.Context) {
	if err := ouu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ouu *OrganizationUserUpdate) defaults() {
	if _, ok := ouu.mutation.UpdatedAt(); !ok {
		v := organizationuser.UpdateDefaultUpdatedAt()
		ouu.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ouu *OrganizationUserUpdate) check() error {
	if ouu.mutation.OrganizationCleared() && len(ouu.mutation.OrganizationIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "OrganizationUser.organization"`)
	}
	if ouu.mutation.UserCleared() && len(ouu.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "OrganizationUser.user"`)
	}
	return nil
}

func (ouu *OrganizationUserUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := ouu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(organizationuser.Table, organizationuser.Columns, sqlgraph.NewFieldSpec(organizationuser.FieldID, field.TypeUUID))
	if ps := ouu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ouu.mutation.UpdatedAt(); ok {
		_spec.SetField(organizationuser.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := ouu.mutation.DeletedAt(); ok {
		_spec.SetField(organizationuser.FieldDeletedAt, field.TypeTime, value)
	}
	if ouu.mutation.DeletedAtCleared() {
		_spec.ClearField(organizationuser.FieldDeletedAt, field.TypeTime)
	}
	if ouu.mutation.OrganizationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   organizationuser.OrganizationTable,
			Columns: []string{organizationuser.OrganizationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ouu.mutation.OrganizationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   organizationuser.OrganizationTable,
			Columns: []string{organizationuser.OrganizationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if ouu.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   organizationuser.UserTable,
			Columns: []string{organizationuser.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ouu.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   organizationuser.UserTable,
			Columns: []string{organizationuser.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if ouu.mutation.RoleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   organizationuser.RoleTable,
			Columns: []string{organizationuser.RoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ouu.mutation.RoleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   organizationuser.RoleTable,
			Columns: []string{organizationuser.RoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, ouu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{organizationuser.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	ouu.mutation.done = true
	return n, nil
}

// OrganizationUserUpdateOne is the builder for updating a single OrganizationUser entity.
type OrganizationUserUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OrganizationUserMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (ouuo *OrganizationUserUpdateOne) SetUpdatedAt(t time.Time) *OrganizationUserUpdateOne {
	ouuo.mutation.SetUpdatedAt(t)
	return ouuo
}

// SetDeletedAt sets the "deleted_at" field.
func (ouuo *OrganizationUserUpdateOne) SetDeletedAt(t time.Time) *OrganizationUserUpdateOne {
	ouuo.mutation.SetDeletedAt(t)
	return ouuo
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (ouuo *OrganizationUserUpdateOne) SetNillableDeletedAt(t *time.Time) *OrganizationUserUpdateOne {
	if t != nil {
		ouuo.SetDeletedAt(*t)
	}
	return ouuo
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (ouuo *OrganizationUserUpdateOne) ClearDeletedAt() *OrganizationUserUpdateOne {
	ouuo.mutation.ClearDeletedAt()
	return ouuo
}

// SetOrganizationID sets the "organization_id" field.
func (ouuo *OrganizationUserUpdateOne) SetOrganizationID(u uuid.UUID) *OrganizationUserUpdateOne {
	ouuo.mutation.SetOrganizationID(u)
	return ouuo
}

// SetNillableOrganizationID sets the "organization_id" field if the given value is not nil.
func (ouuo *OrganizationUserUpdateOne) SetNillableOrganizationID(u *uuid.UUID) *OrganizationUserUpdateOne {
	if u != nil {
		ouuo.SetOrganizationID(*u)
	}
	return ouuo
}

// SetUserID sets the "user_id" field.
func (ouuo *OrganizationUserUpdateOne) SetUserID(s string) *OrganizationUserUpdateOne {
	ouuo.mutation.SetUserID(s)
	return ouuo
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (ouuo *OrganizationUserUpdateOne) SetNillableUserID(s *string) *OrganizationUserUpdateOne {
	if s != nil {
		ouuo.SetUserID(*s)
	}
	return ouuo
}

// SetOrganization sets the "organization" edge to the Organization entity.
func (ouuo *OrganizationUserUpdateOne) SetOrganization(o *Organization) *OrganizationUserUpdateOne {
	return ouuo.SetOrganizationID(o.ID)
}

// SetUser sets the "user" edge to the User entity.
func (ouuo *OrganizationUserUpdateOne) SetUser(u *User) *OrganizationUserUpdateOne {
	return ouuo.SetUserID(u.ID)
}

// SetRoleID sets the "role" edge to the Role entity by ID.
func (ouuo *OrganizationUserUpdateOne) SetRoleID(id uuid.UUID) *OrganizationUserUpdateOne {
	ouuo.mutation.SetRoleID(id)
	return ouuo
}

// SetNillableRoleID sets the "role" edge to the Role entity by ID if the given value is not nil.
func (ouuo *OrganizationUserUpdateOne) SetNillableRoleID(id *uuid.UUID) *OrganizationUserUpdateOne {
	if id != nil {
		ouuo = ouuo.SetRoleID(*id)
	}
	return ouuo
}

// SetRole sets the "role" edge to the Role entity.
func (ouuo *OrganizationUserUpdateOne) SetRole(r *Role) *OrganizationUserUpdateOne {
	return ouuo.SetRoleID(r.ID)
}

// Mutation returns the OrganizationUserMutation object of the builder.
func (ouuo *OrganizationUserUpdateOne) Mutation() *OrganizationUserMutation {
	return ouuo.mutation
}

// ClearOrganization clears the "organization" edge to the Organization entity.
func (ouuo *OrganizationUserUpdateOne) ClearOrganization() *OrganizationUserUpdateOne {
	ouuo.mutation.ClearOrganization()
	return ouuo
}

// ClearUser clears the "user" edge to the User entity.
func (ouuo *OrganizationUserUpdateOne) ClearUser() *OrganizationUserUpdateOne {
	ouuo.mutation.ClearUser()
	return ouuo
}

// ClearRole clears the "role" edge to the Role entity.
func (ouuo *OrganizationUserUpdateOne) ClearRole() *OrganizationUserUpdateOne {
	ouuo.mutation.ClearRole()
	return ouuo
}

// Where appends a list predicates to the OrganizationUserUpdate builder.
func (ouuo *OrganizationUserUpdateOne) Where(ps ...predicate.OrganizationUser) *OrganizationUserUpdateOne {
	ouuo.mutation.Where(ps...)
	return ouuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (ouuo *OrganizationUserUpdateOne) Select(field string, fields ...string) *OrganizationUserUpdateOne {
	ouuo.fields = append([]string{field}, fields...)
	return ouuo
}

// Save executes the query and returns the updated OrganizationUser entity.
func (ouuo *OrganizationUserUpdateOne) Save(ctx context.Context) (*OrganizationUser, error) {
	ouuo.defaults()
	return withHooks(ctx, ouuo.sqlSave, ouuo.mutation, ouuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ouuo *OrganizationUserUpdateOne) SaveX(ctx context.Context) *OrganizationUser {
	node, err := ouuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (ouuo *OrganizationUserUpdateOne) Exec(ctx context.Context) error {
	_, err := ouuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ouuo *OrganizationUserUpdateOne) ExecX(ctx context.Context) {
	if err := ouuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ouuo *OrganizationUserUpdateOne) defaults() {
	if _, ok := ouuo.mutation.UpdatedAt(); !ok {
		v := organizationuser.UpdateDefaultUpdatedAt()
		ouuo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ouuo *OrganizationUserUpdateOne) check() error {
	if ouuo.mutation.OrganizationCleared() && len(ouuo.mutation.OrganizationIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "OrganizationUser.organization"`)
	}
	if ouuo.mutation.UserCleared() && len(ouuo.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "OrganizationUser.user"`)
	}
	return nil
}

func (ouuo *OrganizationUserUpdateOne) sqlSave(ctx context.Context) (_node *OrganizationUser, err error) {
	if err := ouuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(organizationuser.Table, organizationuser.Columns, sqlgraph.NewFieldSpec(organizationuser.FieldID, field.TypeUUID))
	id, ok := ouuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "OrganizationUser.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := ouuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, organizationuser.FieldID)
		for _, f := range fields {
			if !organizationuser.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != organizationuser.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := ouuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ouuo.mutation.UpdatedAt(); ok {
		_spec.SetField(organizationuser.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := ouuo.mutation.DeletedAt(); ok {
		_spec.SetField(organizationuser.FieldDeletedAt, field.TypeTime, value)
	}
	if ouuo.mutation.DeletedAtCleared() {
		_spec.ClearField(organizationuser.FieldDeletedAt, field.TypeTime)
	}
	if ouuo.mutation.OrganizationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   organizationuser.OrganizationTable,
			Columns: []string{organizationuser.OrganizationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ouuo.mutation.OrganizationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   organizationuser.OrganizationTable,
			Columns: []string{organizationuser.OrganizationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if ouuo.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   organizationuser.UserTable,
			Columns: []string{organizationuser.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ouuo.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   organizationuser.UserTable,
			Columns: []string{organizationuser.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if ouuo.mutation.RoleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   organizationuser.RoleTable,
			Columns: []string{organizationuser.RoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ouuo.mutation.RoleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   organizationuser.RoleTable,
			Columns: []string{organizationuser.RoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &OrganizationUser{config: ouuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, ouuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{organizationuser.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	ouuo.mutation.done = true
	return _node, nil
}
