// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"kiwi-user/internal/infrastructure/repository/ent/organization"
	"kiwi-user/internal/infrastructure/repository/ent/organizationuser"
	"kiwi-user/internal/infrastructure/repository/ent/role"
	"kiwi-user/internal/infrastructure/repository/ent/user"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// OrganizationUserCreate is the builder for creating a OrganizationUser entity.
type OrganizationUserCreate struct {
	config
	mutation *OrganizationUserMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (ouc *OrganizationUserCreate) SetCreatedAt(t time.Time) *OrganizationUserCreate {
	ouc.mutation.SetCreatedAt(t)
	return ouc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (ouc *OrganizationUserCreate) SetNillableCreatedAt(t *time.Time) *OrganizationUserCreate {
	if t != nil {
		ouc.SetCreatedAt(*t)
	}
	return ouc
}

// SetUpdatedAt sets the "updated_at" field.
func (ouc *OrganizationUserCreate) SetUpdatedAt(t time.Time) *OrganizationUserCreate {
	ouc.mutation.SetUpdatedAt(t)
	return ouc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (ouc *OrganizationUserCreate) SetNillableUpdatedAt(t *time.Time) *OrganizationUserCreate {
	if t != nil {
		ouc.SetUpdatedAt(*t)
	}
	return ouc
}

// SetDeletedAt sets the "deleted_at" field.
func (ouc *OrganizationUserCreate) SetDeletedAt(t time.Time) *OrganizationUserCreate {
	ouc.mutation.SetDeletedAt(t)
	return ouc
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (ouc *OrganizationUserCreate) SetNillableDeletedAt(t *time.Time) *OrganizationUserCreate {
	if t != nil {
		ouc.SetDeletedAt(*t)
	}
	return ouc
}

// SetOrganizationID sets the "organization_id" field.
func (ouc *OrganizationUserCreate) SetOrganizationID(u uuid.UUID) *OrganizationUserCreate {
	ouc.mutation.SetOrganizationID(u)
	return ouc
}

// SetUserID sets the "user_id" field.
func (ouc *OrganizationUserCreate) SetUserID(s string) *OrganizationUserCreate {
	ouc.mutation.SetUserID(s)
	return ouc
}

// SetID sets the "id" field.
func (ouc *OrganizationUserCreate) SetID(u uuid.UUID) *OrganizationUserCreate {
	ouc.mutation.SetID(u)
	return ouc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (ouc *OrganizationUserCreate) SetNillableID(u *uuid.UUID) *OrganizationUserCreate {
	if u != nil {
		ouc.SetID(*u)
	}
	return ouc
}

// SetOrganization sets the "organization" edge to the Organization entity.
func (ouc *OrganizationUserCreate) SetOrganization(o *Organization) *OrganizationUserCreate {
	return ouc.SetOrganizationID(o.ID)
}

// SetUser sets the "user" edge to the User entity.
func (ouc *OrganizationUserCreate) SetUser(u *User) *OrganizationUserCreate {
	return ouc.SetUserID(u.ID)
}

// SetRoleID sets the "role" edge to the Role entity by ID.
func (ouc *OrganizationUserCreate) SetRoleID(id uuid.UUID) *OrganizationUserCreate {
	ouc.mutation.SetRoleID(id)
	return ouc
}

// SetNillableRoleID sets the "role" edge to the Role entity by ID if the given value is not nil.
func (ouc *OrganizationUserCreate) SetNillableRoleID(id *uuid.UUID) *OrganizationUserCreate {
	if id != nil {
		ouc = ouc.SetRoleID(*id)
	}
	return ouc
}

// SetRole sets the "role" edge to the Role entity.
func (ouc *OrganizationUserCreate) SetRole(r *Role) *OrganizationUserCreate {
	return ouc.SetRoleID(r.ID)
}

// Mutation returns the OrganizationUserMutation object of the builder.
func (ouc *OrganizationUserCreate) Mutation() *OrganizationUserMutation {
	return ouc.mutation
}

// Save creates the OrganizationUser in the database.
func (ouc *OrganizationUserCreate) Save(ctx context.Context) (*OrganizationUser, error) {
	ouc.defaults()
	return withHooks(ctx, ouc.sqlSave, ouc.mutation, ouc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (ouc *OrganizationUserCreate) SaveX(ctx context.Context) *OrganizationUser {
	v, err := ouc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ouc *OrganizationUserCreate) Exec(ctx context.Context) error {
	_, err := ouc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ouc *OrganizationUserCreate) ExecX(ctx context.Context) {
	if err := ouc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ouc *OrganizationUserCreate) defaults() {
	if _, ok := ouc.mutation.CreatedAt(); !ok {
		v := organizationuser.DefaultCreatedAt()
		ouc.mutation.SetCreatedAt(v)
	}
	if _, ok := ouc.mutation.UpdatedAt(); !ok {
		v := organizationuser.DefaultUpdatedAt()
		ouc.mutation.SetUpdatedAt(v)
	}
	if _, ok := ouc.mutation.ID(); !ok {
		v := organizationuser.DefaultID()
		ouc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ouc *OrganizationUserCreate) check() error {
	if _, ok := ouc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "OrganizationUser.created_at"`)}
	}
	if _, ok := ouc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "OrganizationUser.updated_at"`)}
	}
	if _, ok := ouc.mutation.OrganizationID(); !ok {
		return &ValidationError{Name: "organization_id", err: errors.New(`ent: missing required field "OrganizationUser.organization_id"`)}
	}
	if _, ok := ouc.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "OrganizationUser.user_id"`)}
	}
	if len(ouc.mutation.OrganizationIDs()) == 0 {
		return &ValidationError{Name: "organization", err: errors.New(`ent: missing required edge "OrganizationUser.organization"`)}
	}
	if len(ouc.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "OrganizationUser.user"`)}
	}
	return nil
}

func (ouc *OrganizationUserCreate) sqlSave(ctx context.Context) (*OrganizationUser, error) {
	if err := ouc.check(); err != nil {
		return nil, err
	}
	_node, _spec := ouc.createSpec()
	if err := sqlgraph.CreateNode(ctx, ouc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	ouc.mutation.id = &_node.ID
	ouc.mutation.done = true
	return _node, nil
}

func (ouc *OrganizationUserCreate) createSpec() (*OrganizationUser, *sqlgraph.CreateSpec) {
	var (
		_node = &OrganizationUser{config: ouc.config}
		_spec = sqlgraph.NewCreateSpec(organizationuser.Table, sqlgraph.NewFieldSpec(organizationuser.FieldID, field.TypeUUID))
	)
	if id, ok := ouc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := ouc.mutation.CreatedAt(); ok {
		_spec.SetField(organizationuser.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := ouc.mutation.UpdatedAt(); ok {
		_spec.SetField(organizationuser.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := ouc.mutation.DeletedAt(); ok {
		_spec.SetField(organizationuser.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = value
	}
	if nodes := ouc.mutation.OrganizationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   organizationuser.OrganizationTable,
			Columns: []string{organizationuser.OrganizationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.OrganizationID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := ouc.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   organizationuser.UserTable,
			Columns: []string{organizationuser.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := ouc.mutation.RoleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   organizationuser.RoleTable,
			Columns: []string{organizationuser.RoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.organization_user_role = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OrganizationUserCreateBulk is the builder for creating many OrganizationUser entities in bulk.
type OrganizationUserCreateBulk struct {
	config
	err      error
	builders []*OrganizationUserCreate
}

// Save creates the OrganizationUser entities in the database.
func (oucb *OrganizationUserCreateBulk) Save(ctx context.Context) ([]*OrganizationUser, error) {
	if oucb.err != nil {
		return nil, oucb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(oucb.builders))
	nodes := make([]*OrganizationUser, len(oucb.builders))
	mutators := make([]Mutator, len(oucb.builders))
	for i := range oucb.builders {
		func(i int, root context.Context) {
			builder := oucb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OrganizationUserMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, oucb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, oucb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, oucb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (oucb *OrganizationUserCreateBulk) SaveX(ctx context.Context) []*OrganizationUser {
	v, err := oucb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (oucb *OrganizationUserCreateBulk) Exec(ctx context.Context) error {
	_, err := oucb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (oucb *OrganizationUserCreateBulk) ExecX(ctx context.Context) {
	if err := oucb.Exec(ctx); err != nil {
		panic(err)
	}
}
