// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"kiwi-user/internal/infrastructure/repository/ent/application"
	"kiwi-user/internal/infrastructure/repository/ent/organizationapplication"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// OrganizationApplicationCreate is the builder for creating a OrganizationApplication entity.
type OrganizationApplicationCreate struct {
	config
	mutation *OrganizationApplicationMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (oac *OrganizationApplicationCreate) SetCreatedAt(t time.Time) *OrganizationApplicationCreate {
	oac.mutation.SetCreatedAt(t)
	return oac
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (oac *OrganizationApplicationCreate) SetNillableCreatedAt(t *time.Time) *OrganizationApplicationCreate {
	if t != nil {
		oac.SetCreatedAt(*t)
	}
	return oac
}

// SetUpdatedAt sets the "updated_at" field.
func (oac *OrganizationApplicationCreate) SetUpdatedAt(t time.Time) *OrganizationApplicationCreate {
	oac.mutation.SetUpdatedAt(t)
	return oac
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (oac *OrganizationApplicationCreate) SetNillableUpdatedAt(t *time.Time) *OrganizationApplicationCreate {
	if t != nil {
		oac.SetUpdatedAt(*t)
	}
	return oac
}

// SetDeletedAt sets the "deleted_at" field.
func (oac *OrganizationApplicationCreate) SetDeletedAt(t time.Time) *OrganizationApplicationCreate {
	oac.mutation.SetDeletedAt(t)
	return oac
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (oac *OrganizationApplicationCreate) SetNillableDeletedAt(t *time.Time) *OrganizationApplicationCreate {
	if t != nil {
		oac.SetDeletedAt(*t)
	}
	return oac
}

// SetApplicationID sets the "application_id" field.
func (oac *OrganizationApplicationCreate) SetApplicationID(u uuid.UUID) *OrganizationApplicationCreate {
	oac.mutation.SetApplicationID(u)
	return oac
}

// SetName sets the "name" field.
func (oac *OrganizationApplicationCreate) SetName(s string) *OrganizationApplicationCreate {
	oac.mutation.SetName(s)
	return oac
}

// SetStatus sets the "status" field.
func (oac *OrganizationApplicationCreate) SetStatus(o organizationapplication.Status) *OrganizationApplicationCreate {
	oac.mutation.SetStatus(o)
	return oac
}

// SetTrialDays sets the "trial_days" field.
func (oac *OrganizationApplicationCreate) SetTrialDays(i int32) *OrganizationApplicationCreate {
	oac.mutation.SetTrialDays(i)
	return oac
}

// SetNillableTrialDays sets the "trial_days" field if the given value is not nil.
func (oac *OrganizationApplicationCreate) SetNillableTrialDays(i *int32) *OrganizationApplicationCreate {
	if i != nil {
		oac.SetTrialDays(*i)
	}
	return oac
}

// SetReviewStatus sets the "review_status" field.
func (oac *OrganizationApplicationCreate) SetReviewStatus(os organizationapplication.ReviewStatus) *OrganizationApplicationCreate {
	oac.mutation.SetReviewStatus(os)
	return oac
}

// SetReviewComment sets the "review_comment" field.
func (oac *OrganizationApplicationCreate) SetReviewComment(s string) *OrganizationApplicationCreate {
	oac.mutation.SetReviewComment(s)
	return oac
}

// SetNillableReviewComment sets the "review_comment" field if the given value is not nil.
func (oac *OrganizationApplicationCreate) SetNillableReviewComment(s *string) *OrganizationApplicationCreate {
	if s != nil {
		oac.SetReviewComment(*s)
	}
	return oac
}

// SetUserID sets the "user_id" field.
func (oac *OrganizationApplicationCreate) SetUserID(s string) *OrganizationApplicationCreate {
	oac.mutation.SetUserID(s)
	return oac
}

// SetBrandShortName sets the "brand_short_name" field.
func (oac *OrganizationApplicationCreate) SetBrandShortName(s string) *OrganizationApplicationCreate {
	oac.mutation.SetBrandShortName(s)
	return oac
}

// SetPrimaryBusiness sets the "primary_business" field.
func (oac *OrganizationApplicationCreate) SetPrimaryBusiness(s string) *OrganizationApplicationCreate {
	oac.mutation.SetPrimaryBusiness(s)
	return oac
}

// SetUsageScenario sets the "usage_scenario" field.
func (oac *OrganizationApplicationCreate) SetUsageScenario(s string) *OrganizationApplicationCreate {
	oac.mutation.SetUsageScenario(s)
	return oac
}

// SetReferrerName sets the "referrer_name" field.
func (oac *OrganizationApplicationCreate) SetReferrerName(s string) *OrganizationApplicationCreate {
	oac.mutation.SetReferrerName(s)
	return oac
}

// SetNillableReferrerName sets the "referrer_name" field if the given value is not nil.
func (oac *OrganizationApplicationCreate) SetNillableReferrerName(s *string) *OrganizationApplicationCreate {
	if s != nil {
		oac.SetReferrerName(*s)
	}
	return oac
}

// SetDiscoveryWay sets the "discovery_way" field.
func (oac *OrganizationApplicationCreate) SetDiscoveryWay(s string) *OrganizationApplicationCreate {
	oac.mutation.SetDiscoveryWay(s)
	return oac
}

// SetNillableDiscoveryWay sets the "discovery_way" field if the given value is not nil.
func (oac *OrganizationApplicationCreate) SetNillableDiscoveryWay(s *string) *OrganizationApplicationCreate {
	if s != nil {
		oac.SetDiscoveryWay(*s)
	}
	return oac
}

// SetOrgRoleName sets the "org_role_name" field.
func (oac *OrganizationApplicationCreate) SetOrgRoleName(s string) *OrganizationApplicationCreate {
	oac.mutation.SetOrgRoleName(s)
	return oac
}

// SetID sets the "id" field.
func (oac *OrganizationApplicationCreate) SetID(u uuid.UUID) *OrganizationApplicationCreate {
	oac.mutation.SetID(u)
	return oac
}

// SetNillableID sets the "id" field if the given value is not nil.
func (oac *OrganizationApplicationCreate) SetNillableID(u *uuid.UUID) *OrganizationApplicationCreate {
	if u != nil {
		oac.SetID(*u)
	}
	return oac
}

// SetApplication sets the "application" edge to the Application entity.
func (oac *OrganizationApplicationCreate) SetApplication(a *Application) *OrganizationApplicationCreate {
	return oac.SetApplicationID(a.ID)
}

// Mutation returns the OrganizationApplicationMutation object of the builder.
func (oac *OrganizationApplicationCreate) Mutation() *OrganizationApplicationMutation {
	return oac.mutation
}

// Save creates the OrganizationApplication in the database.
func (oac *OrganizationApplicationCreate) Save(ctx context.Context) (*OrganizationApplication, error) {
	oac.defaults()
	return withHooks(ctx, oac.sqlSave, oac.mutation, oac.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (oac *OrganizationApplicationCreate) SaveX(ctx context.Context) *OrganizationApplication {
	v, err := oac.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (oac *OrganizationApplicationCreate) Exec(ctx context.Context) error {
	_, err := oac.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (oac *OrganizationApplicationCreate) ExecX(ctx context.Context) {
	if err := oac.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (oac *OrganizationApplicationCreate) defaults() {
	if _, ok := oac.mutation.CreatedAt(); !ok {
		v := organizationapplication.DefaultCreatedAt()
		oac.mutation.SetCreatedAt(v)
	}
	if _, ok := oac.mutation.UpdatedAt(); !ok {
		v := organizationapplication.DefaultUpdatedAt()
		oac.mutation.SetUpdatedAt(v)
	}
	if _, ok := oac.mutation.ReviewComment(); !ok {
		v := organizationapplication.DefaultReviewComment
		oac.mutation.SetReviewComment(v)
	}
	if _, ok := oac.mutation.ID(); !ok {
		v := organizationapplication.DefaultID()
		oac.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (oac *OrganizationApplicationCreate) check() error {
	if _, ok := oac.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "OrganizationApplication.created_at"`)}
	}
	if _, ok := oac.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "OrganizationApplication.updated_at"`)}
	}
	if _, ok := oac.mutation.ApplicationID(); !ok {
		return &ValidationError{Name: "application_id", err: errors.New(`ent: missing required field "OrganizationApplication.application_id"`)}
	}
	if _, ok := oac.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "OrganizationApplication.name"`)}
	}
	if v, ok := oac.mutation.Name(); ok {
		if err := organizationapplication.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "OrganizationApplication.name": %w`, err)}
		}
	}
	if _, ok := oac.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "OrganizationApplication.status"`)}
	}
	if v, ok := oac.mutation.Status(); ok {
		if err := organizationapplication.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "OrganizationApplication.status": %w`, err)}
		}
	}
	if _, ok := oac.mutation.ReviewStatus(); !ok {
		return &ValidationError{Name: "review_status", err: errors.New(`ent: missing required field "OrganizationApplication.review_status"`)}
	}
	if v, ok := oac.mutation.ReviewStatus(); ok {
		if err := organizationapplication.ReviewStatusValidator(v); err != nil {
			return &ValidationError{Name: "review_status", err: fmt.Errorf(`ent: validator failed for field "OrganizationApplication.review_status": %w`, err)}
		}
	}
	if _, ok := oac.mutation.ReviewComment(); !ok {
		return &ValidationError{Name: "review_comment", err: errors.New(`ent: missing required field "OrganizationApplication.review_comment"`)}
	}
	if v, ok := oac.mutation.ReviewComment(); ok {
		if err := organizationapplication.ReviewCommentValidator(v); err != nil {
			return &ValidationError{Name: "review_comment", err: fmt.Errorf(`ent: validator failed for field "OrganizationApplication.review_comment": %w`, err)}
		}
	}
	if _, ok := oac.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "OrganizationApplication.user_id"`)}
	}
	if v, ok := oac.mutation.UserID(); ok {
		if err := organizationapplication.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "OrganizationApplication.user_id": %w`, err)}
		}
	}
	if _, ok := oac.mutation.BrandShortName(); !ok {
		return &ValidationError{Name: "brand_short_name", err: errors.New(`ent: missing required field "OrganizationApplication.brand_short_name"`)}
	}
	if v, ok := oac.mutation.BrandShortName(); ok {
		if err := organizationapplication.BrandShortNameValidator(v); err != nil {
			return &ValidationError{Name: "brand_short_name", err: fmt.Errorf(`ent: validator failed for field "OrganizationApplication.brand_short_name": %w`, err)}
		}
	}
	if _, ok := oac.mutation.PrimaryBusiness(); !ok {
		return &ValidationError{Name: "primary_business", err: errors.New(`ent: missing required field "OrganizationApplication.primary_business"`)}
	}
	if v, ok := oac.mutation.PrimaryBusiness(); ok {
		if err := organizationapplication.PrimaryBusinessValidator(v); err != nil {
			return &ValidationError{Name: "primary_business", err: fmt.Errorf(`ent: validator failed for field "OrganizationApplication.primary_business": %w`, err)}
		}
	}
	if _, ok := oac.mutation.UsageScenario(); !ok {
		return &ValidationError{Name: "usage_scenario", err: errors.New(`ent: missing required field "OrganizationApplication.usage_scenario"`)}
	}
	if v, ok := oac.mutation.UsageScenario(); ok {
		if err := organizationapplication.UsageScenarioValidator(v); err != nil {
			return &ValidationError{Name: "usage_scenario", err: fmt.Errorf(`ent: validator failed for field "OrganizationApplication.usage_scenario": %w`, err)}
		}
	}
	if _, ok := oac.mutation.OrgRoleName(); !ok {
		return &ValidationError{Name: "org_role_name", err: errors.New(`ent: missing required field "OrganizationApplication.org_role_name"`)}
	}
	if v, ok := oac.mutation.OrgRoleName(); ok {
		if err := organizationapplication.OrgRoleNameValidator(v); err != nil {
			return &ValidationError{Name: "org_role_name", err: fmt.Errorf(`ent: validator failed for field "OrganizationApplication.org_role_name": %w`, err)}
		}
	}
	if len(oac.mutation.ApplicationIDs()) == 0 {
		return &ValidationError{Name: "application", err: errors.New(`ent: missing required edge "OrganizationApplication.application"`)}
	}
	return nil
}

func (oac *OrganizationApplicationCreate) sqlSave(ctx context.Context) (*OrganizationApplication, error) {
	if err := oac.check(); err != nil {
		return nil, err
	}
	_node, _spec := oac.createSpec()
	if err := sqlgraph.CreateNode(ctx, oac.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	oac.mutation.id = &_node.ID
	oac.mutation.done = true
	return _node, nil
}

func (oac *OrganizationApplicationCreate) createSpec() (*OrganizationApplication, *sqlgraph.CreateSpec) {
	var (
		_node = &OrganizationApplication{config: oac.config}
		_spec = sqlgraph.NewCreateSpec(organizationapplication.Table, sqlgraph.NewFieldSpec(organizationapplication.FieldID, field.TypeUUID))
	)
	if id, ok := oac.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := oac.mutation.CreatedAt(); ok {
		_spec.SetField(organizationapplication.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := oac.mutation.UpdatedAt(); ok {
		_spec.SetField(organizationapplication.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := oac.mutation.DeletedAt(); ok {
		_spec.SetField(organizationapplication.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = value
	}
	if value, ok := oac.mutation.Name(); ok {
		_spec.SetField(organizationapplication.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := oac.mutation.Status(); ok {
		_spec.SetField(organizationapplication.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := oac.mutation.TrialDays(); ok {
		_spec.SetField(organizationapplication.FieldTrialDays, field.TypeInt32, value)
		_node.TrialDays = value
	}
	if value, ok := oac.mutation.ReviewStatus(); ok {
		_spec.SetField(organizationapplication.FieldReviewStatus, field.TypeEnum, value)
		_node.ReviewStatus = value
	}
	if value, ok := oac.mutation.ReviewComment(); ok {
		_spec.SetField(organizationapplication.FieldReviewComment, field.TypeString, value)
		_node.ReviewComment = value
	}
	if value, ok := oac.mutation.UserID(); ok {
		_spec.SetField(organizationapplication.FieldUserID, field.TypeString, value)
		_node.UserID = value
	}
	if value, ok := oac.mutation.BrandShortName(); ok {
		_spec.SetField(organizationapplication.FieldBrandShortName, field.TypeString, value)
		_node.BrandShortName = value
	}
	if value, ok := oac.mutation.PrimaryBusiness(); ok {
		_spec.SetField(organizationapplication.FieldPrimaryBusiness, field.TypeString, value)
		_node.PrimaryBusiness = value
	}
	if value, ok := oac.mutation.UsageScenario(); ok {
		_spec.SetField(organizationapplication.FieldUsageScenario, field.TypeString, value)
		_node.UsageScenario = value
	}
	if value, ok := oac.mutation.ReferrerName(); ok {
		_spec.SetField(organizationapplication.FieldReferrerName, field.TypeString, value)
		_node.ReferrerName = value
	}
	if value, ok := oac.mutation.DiscoveryWay(); ok {
		_spec.SetField(organizationapplication.FieldDiscoveryWay, field.TypeString, value)
		_node.DiscoveryWay = value
	}
	if value, ok := oac.mutation.OrgRoleName(); ok {
		_spec.SetField(organizationapplication.FieldOrgRoleName, field.TypeString, value)
		_node.OrgRoleName = value
	}
	if nodes := oac.mutation.ApplicationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   organizationapplication.ApplicationTable,
			Columns: []string{organizationapplication.ApplicationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(application.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ApplicationID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OrganizationApplicationCreateBulk is the builder for creating many OrganizationApplication entities in bulk.
type OrganizationApplicationCreateBulk struct {
	config
	err      error
	builders []*OrganizationApplicationCreate
}

// Save creates the OrganizationApplication entities in the database.
func (oacb *OrganizationApplicationCreateBulk) Save(ctx context.Context) ([]*OrganizationApplication, error) {
	if oacb.err != nil {
		return nil, oacb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(oacb.builders))
	nodes := make([]*OrganizationApplication, len(oacb.builders))
	mutators := make([]Mutator, len(oacb.builders))
	for i := range oacb.builders {
		func(i int, root context.Context) {
			builder := oacb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OrganizationApplicationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, oacb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, oacb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, oacb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (oacb *OrganizationApplicationCreateBulk) SaveX(ctx context.Context) []*OrganizationApplication {
	v, err := oacb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (oacb *OrganizationApplicationCreateBulk) Exec(ctx context.Context) error {
	_, err := oacb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (oacb *OrganizationApplicationCreateBulk) ExecX(ctx context.Context) {
	if err := oacb.Exec(ctx); err != nil {
		panic(err)
	}
}
