// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"kiwi-user/internal/infrastructure/repository/ent/application"
	"kiwi-user/internal/infrastructure/repository/ent/organizationapplication"
	"kiwi-user/internal/infrastructure/repository/ent/predicate"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// OrganizationApplicationQuery is the builder for querying OrganizationApplication entities.
type OrganizationApplicationQuery struct {
	config
	ctx             *QueryContext
	order           []organizationapplication.OrderOption
	inters          []Interceptor
	predicates      []predicate.OrganizationApplication
	withApplication *ApplicationQuery
	modifiers       []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the OrganizationApplicationQuery builder.
func (oaq *OrganizationApplicationQuery) Where(ps ...predicate.OrganizationApplication) *OrganizationApplicationQuery {
	oaq.predicates = append(oaq.predicates, ps...)
	return oaq
}

// Limit the number of records to be returned by this query.
func (oaq *OrganizationApplicationQuery) Limit(limit int) *OrganizationApplicationQuery {
	oaq.ctx.Limit = &limit
	return oaq
}

// Offset to start from.
func (oaq *OrganizationApplicationQuery) Offset(offset int) *OrganizationApplicationQuery {
	oaq.ctx.Offset = &offset
	return oaq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (oaq *OrganizationApplicationQuery) Unique(unique bool) *OrganizationApplicationQuery {
	oaq.ctx.Unique = &unique
	return oaq
}

// Order specifies how the records should be ordered.
func (oaq *OrganizationApplicationQuery) Order(o ...organizationapplication.OrderOption) *OrganizationApplicationQuery {
	oaq.order = append(oaq.order, o...)
	return oaq
}

// QueryApplication chains the current query on the "application" edge.
func (oaq *OrganizationApplicationQuery) QueryApplication() *ApplicationQuery {
	query := (&ApplicationClient{config: oaq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := oaq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := oaq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(organizationapplication.Table, organizationapplication.FieldID, selector),
			sqlgraph.To(application.Table, application.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, organizationapplication.ApplicationTable, organizationapplication.ApplicationColumn),
		)
		fromU = sqlgraph.SetNeighbors(oaq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first OrganizationApplication entity from the query.
// Returns a *NotFoundError when no OrganizationApplication was found.
func (oaq *OrganizationApplicationQuery) First(ctx context.Context) (*OrganizationApplication, error) {
	nodes, err := oaq.Limit(1).All(setContextOp(ctx, oaq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{organizationapplication.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (oaq *OrganizationApplicationQuery) FirstX(ctx context.Context) *OrganizationApplication {
	node, err := oaq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first OrganizationApplication ID from the query.
// Returns a *NotFoundError when no OrganizationApplication ID was found.
func (oaq *OrganizationApplicationQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = oaq.Limit(1).IDs(setContextOp(ctx, oaq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{organizationapplication.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (oaq *OrganizationApplicationQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := oaq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single OrganizationApplication entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one OrganizationApplication entity is found.
// Returns a *NotFoundError when no OrganizationApplication entities are found.
func (oaq *OrganizationApplicationQuery) Only(ctx context.Context) (*OrganizationApplication, error) {
	nodes, err := oaq.Limit(2).All(setContextOp(ctx, oaq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{organizationapplication.Label}
	default:
		return nil, &NotSingularError{organizationapplication.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (oaq *OrganizationApplicationQuery) OnlyX(ctx context.Context) *OrganizationApplication {
	node, err := oaq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only OrganizationApplication ID in the query.
// Returns a *NotSingularError when more than one OrganizationApplication ID is found.
// Returns a *NotFoundError when no entities are found.
func (oaq *OrganizationApplicationQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = oaq.Limit(2).IDs(setContextOp(ctx, oaq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{organizationapplication.Label}
	default:
		err = &NotSingularError{organizationapplication.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (oaq *OrganizationApplicationQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := oaq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of OrganizationApplications.
func (oaq *OrganizationApplicationQuery) All(ctx context.Context) ([]*OrganizationApplication, error) {
	ctx = setContextOp(ctx, oaq.ctx, ent.OpQueryAll)
	if err := oaq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*OrganizationApplication, *OrganizationApplicationQuery]()
	return withInterceptors[[]*OrganizationApplication](ctx, oaq, qr, oaq.inters)
}

// AllX is like All, but panics if an error occurs.
func (oaq *OrganizationApplicationQuery) AllX(ctx context.Context) []*OrganizationApplication {
	nodes, err := oaq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of OrganizationApplication IDs.
func (oaq *OrganizationApplicationQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if oaq.ctx.Unique == nil && oaq.path != nil {
		oaq.Unique(true)
	}
	ctx = setContextOp(ctx, oaq.ctx, ent.OpQueryIDs)
	if err = oaq.Select(organizationapplication.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (oaq *OrganizationApplicationQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := oaq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (oaq *OrganizationApplicationQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, oaq.ctx, ent.OpQueryCount)
	if err := oaq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, oaq, querierCount[*OrganizationApplicationQuery](), oaq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (oaq *OrganizationApplicationQuery) CountX(ctx context.Context) int {
	count, err := oaq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (oaq *OrganizationApplicationQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, oaq.ctx, ent.OpQueryExist)
	switch _, err := oaq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (oaq *OrganizationApplicationQuery) ExistX(ctx context.Context) bool {
	exist, err := oaq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the OrganizationApplicationQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (oaq *OrganizationApplicationQuery) Clone() *OrganizationApplicationQuery {
	if oaq == nil {
		return nil
	}
	return &OrganizationApplicationQuery{
		config:          oaq.config,
		ctx:             oaq.ctx.Clone(),
		order:           append([]organizationapplication.OrderOption{}, oaq.order...),
		inters:          append([]Interceptor{}, oaq.inters...),
		predicates:      append([]predicate.OrganizationApplication{}, oaq.predicates...),
		withApplication: oaq.withApplication.Clone(),
		// clone intermediate query.
		sql:  oaq.sql.Clone(),
		path: oaq.path,
	}
}

// WithApplication tells the query-builder to eager-load the nodes that are connected to
// the "application" edge. The optional arguments are used to configure the query builder of the edge.
func (oaq *OrganizationApplicationQuery) WithApplication(opts ...func(*ApplicationQuery)) *OrganizationApplicationQuery {
	query := (&ApplicationClient{config: oaq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	oaq.withApplication = query
	return oaq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.OrganizationApplication.Query().
//		GroupBy(organizationapplication.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (oaq *OrganizationApplicationQuery) GroupBy(field string, fields ...string) *OrganizationApplicationGroupBy {
	oaq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &OrganizationApplicationGroupBy{build: oaq}
	grbuild.flds = &oaq.ctx.Fields
	grbuild.label = organizationapplication.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.OrganizationApplication.Query().
//		Select(organizationapplication.FieldCreatedAt).
//		Scan(ctx, &v)
func (oaq *OrganizationApplicationQuery) Select(fields ...string) *OrganizationApplicationSelect {
	oaq.ctx.Fields = append(oaq.ctx.Fields, fields...)
	sbuild := &OrganizationApplicationSelect{OrganizationApplicationQuery: oaq}
	sbuild.label = organizationapplication.Label
	sbuild.flds, sbuild.scan = &oaq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a OrganizationApplicationSelect configured with the given aggregations.
func (oaq *OrganizationApplicationQuery) Aggregate(fns ...AggregateFunc) *OrganizationApplicationSelect {
	return oaq.Select().Aggregate(fns...)
}

func (oaq *OrganizationApplicationQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range oaq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, oaq); err != nil {
				return err
			}
		}
	}
	for _, f := range oaq.ctx.Fields {
		if !organizationapplication.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if oaq.path != nil {
		prev, err := oaq.path(ctx)
		if err != nil {
			return err
		}
		oaq.sql = prev
	}
	return nil
}

func (oaq *OrganizationApplicationQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*OrganizationApplication, error) {
	var (
		nodes       = []*OrganizationApplication{}
		_spec       = oaq.querySpec()
		loadedTypes = [1]bool{
			oaq.withApplication != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*OrganizationApplication).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &OrganizationApplication{config: oaq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(oaq.modifiers) > 0 {
		_spec.Modifiers = oaq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, oaq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := oaq.withApplication; query != nil {
		if err := oaq.loadApplication(ctx, query, nodes, nil,
			func(n *OrganizationApplication, e *Application) { n.Edges.Application = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (oaq *OrganizationApplicationQuery) loadApplication(ctx context.Context, query *ApplicationQuery, nodes []*OrganizationApplication, init func(*OrganizationApplication), assign func(*OrganizationApplication, *Application)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*OrganizationApplication)
	for i := range nodes {
		fk := nodes[i].ApplicationID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(application.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "application_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (oaq *OrganizationApplicationQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := oaq.querySpec()
	if len(oaq.modifiers) > 0 {
		_spec.Modifiers = oaq.modifiers
	}
	_spec.Node.Columns = oaq.ctx.Fields
	if len(oaq.ctx.Fields) > 0 {
		_spec.Unique = oaq.ctx.Unique != nil && *oaq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, oaq.driver, _spec)
}

func (oaq *OrganizationApplicationQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(organizationapplication.Table, organizationapplication.Columns, sqlgraph.NewFieldSpec(organizationapplication.FieldID, field.TypeUUID))
	_spec.From = oaq.sql
	if unique := oaq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if oaq.path != nil {
		_spec.Unique = true
	}
	if fields := oaq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, organizationapplication.FieldID)
		for i := range fields {
			if fields[i] != organizationapplication.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if oaq.withApplication != nil {
			_spec.Node.AddColumnOnce(organizationapplication.FieldApplicationID)
		}
	}
	if ps := oaq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := oaq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := oaq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := oaq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (oaq *OrganizationApplicationQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(oaq.driver.Dialect())
	t1 := builder.Table(organizationapplication.Table)
	columns := oaq.ctx.Fields
	if len(columns) == 0 {
		columns = organizationapplication.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if oaq.sql != nil {
		selector = oaq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if oaq.ctx.Unique != nil && *oaq.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range oaq.modifiers {
		m(selector)
	}
	for _, p := range oaq.predicates {
		p(selector)
	}
	for _, p := range oaq.order {
		p(selector)
	}
	if offset := oaq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := oaq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (oaq *OrganizationApplicationQuery) ForUpdate(opts ...sql.LockOption) *OrganizationApplicationQuery {
	if oaq.driver.Dialect() == dialect.Postgres {
		oaq.Unique(false)
	}
	oaq.modifiers = append(oaq.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return oaq
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (oaq *OrganizationApplicationQuery) ForShare(opts ...sql.LockOption) *OrganizationApplicationQuery {
	if oaq.driver.Dialect() == dialect.Postgres {
		oaq.Unique(false)
	}
	oaq.modifiers = append(oaq.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return oaq
}

// OrganizationApplicationGroupBy is the group-by builder for OrganizationApplication entities.
type OrganizationApplicationGroupBy struct {
	selector
	build *OrganizationApplicationQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (oagb *OrganizationApplicationGroupBy) Aggregate(fns ...AggregateFunc) *OrganizationApplicationGroupBy {
	oagb.fns = append(oagb.fns, fns...)
	return oagb
}

// Scan applies the selector query and scans the result into the given value.
func (oagb *OrganizationApplicationGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, oagb.build.ctx, ent.OpQueryGroupBy)
	if err := oagb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*OrganizationApplicationQuery, *OrganizationApplicationGroupBy](ctx, oagb.build, oagb, oagb.build.inters, v)
}

func (oagb *OrganizationApplicationGroupBy) sqlScan(ctx context.Context, root *OrganizationApplicationQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(oagb.fns))
	for _, fn := range oagb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*oagb.flds)+len(oagb.fns))
		for _, f := range *oagb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*oagb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := oagb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// OrganizationApplicationSelect is the builder for selecting fields of OrganizationApplication entities.
type OrganizationApplicationSelect struct {
	*OrganizationApplicationQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (oas *OrganizationApplicationSelect) Aggregate(fns ...AggregateFunc) *OrganizationApplicationSelect {
	oas.fns = append(oas.fns, fns...)
	return oas
}

// Scan applies the selector query and scans the result into the given value.
func (oas *OrganizationApplicationSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, oas.ctx, ent.OpQuerySelect)
	if err := oas.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*OrganizationApplicationQuery, *OrganizationApplicationSelect](ctx, oas.OrganizationApplicationQuery, oas, oas.inters, v)
}

func (oas *OrganizationApplicationSelect) sqlScan(ctx context.Context, root *OrganizationApplicationQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(oas.fns))
	for _, fn := range oas.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*oas.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := oas.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
