// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"kiwi-user/internal/infrastructure/repository/ent/organizationrequest"
	"kiwi-user/internal/infrastructure/repository/ent/predicate"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// OrganizationRequestQuery is the builder for querying OrganizationRequest entities.
type OrganizationRequestQuery struct {
	config
	ctx        *QueryContext
	order      []organizationrequest.OrderOption
	inters     []Interceptor
	predicates []predicate.OrganizationRequest
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the OrganizationRequestQuery builder.
func (orq *OrganizationRequestQuery) Where(ps ...predicate.OrganizationRequest) *OrganizationRequestQuery {
	orq.predicates = append(orq.predicates, ps...)
	return orq
}

// Limit the number of records to be returned by this query.
func (orq *OrganizationRequestQuery) Limit(limit int) *OrganizationRequestQuery {
	orq.ctx.Limit = &limit
	return orq
}

// Offset to start from.
func (orq *OrganizationRequestQuery) Offset(offset int) *OrganizationRequestQuery {
	orq.ctx.Offset = &offset
	return orq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (orq *OrganizationRequestQuery) Unique(unique bool) *OrganizationRequestQuery {
	orq.ctx.Unique = &unique
	return orq
}

// Order specifies how the records should be ordered.
func (orq *OrganizationRequestQuery) Order(o ...organizationrequest.OrderOption) *OrganizationRequestQuery {
	orq.order = append(orq.order, o...)
	return orq
}

// First returns the first OrganizationRequest entity from the query.
// Returns a *NotFoundError when no OrganizationRequest was found.
func (orq *OrganizationRequestQuery) First(ctx context.Context) (*OrganizationRequest, error) {
	nodes, err := orq.Limit(1).All(setContextOp(ctx, orq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{organizationrequest.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (orq *OrganizationRequestQuery) FirstX(ctx context.Context) *OrganizationRequest {
	node, err := orq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first OrganizationRequest ID from the query.
// Returns a *NotFoundError when no OrganizationRequest ID was found.
func (orq *OrganizationRequestQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = orq.Limit(1).IDs(setContextOp(ctx, orq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{organizationrequest.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (orq *OrganizationRequestQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := orq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single OrganizationRequest entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one OrganizationRequest entity is found.
// Returns a *NotFoundError when no OrganizationRequest entities are found.
func (orq *OrganizationRequestQuery) Only(ctx context.Context) (*OrganizationRequest, error) {
	nodes, err := orq.Limit(2).All(setContextOp(ctx, orq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{organizationrequest.Label}
	default:
		return nil, &NotSingularError{organizationrequest.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (orq *OrganizationRequestQuery) OnlyX(ctx context.Context) *OrganizationRequest {
	node, err := orq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only OrganizationRequest ID in the query.
// Returns a *NotSingularError when more than one OrganizationRequest ID is found.
// Returns a *NotFoundError when no entities are found.
func (orq *OrganizationRequestQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = orq.Limit(2).IDs(setContextOp(ctx, orq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{organizationrequest.Label}
	default:
		err = &NotSingularError{organizationrequest.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (orq *OrganizationRequestQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := orq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of OrganizationRequests.
func (orq *OrganizationRequestQuery) All(ctx context.Context) ([]*OrganizationRequest, error) {
	ctx = setContextOp(ctx, orq.ctx, ent.OpQueryAll)
	if err := orq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*OrganizationRequest, *OrganizationRequestQuery]()
	return withInterceptors[[]*OrganizationRequest](ctx, orq, qr, orq.inters)
}

// AllX is like All, but panics if an error occurs.
func (orq *OrganizationRequestQuery) AllX(ctx context.Context) []*OrganizationRequest {
	nodes, err := orq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of OrganizationRequest IDs.
func (orq *OrganizationRequestQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if orq.ctx.Unique == nil && orq.path != nil {
		orq.Unique(true)
	}
	ctx = setContextOp(ctx, orq.ctx, ent.OpQueryIDs)
	if err = orq.Select(organizationrequest.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (orq *OrganizationRequestQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := orq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (orq *OrganizationRequestQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, orq.ctx, ent.OpQueryCount)
	if err := orq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, orq, querierCount[*OrganizationRequestQuery](), orq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (orq *OrganizationRequestQuery) CountX(ctx context.Context) int {
	count, err := orq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (orq *OrganizationRequestQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, orq.ctx, ent.OpQueryExist)
	switch _, err := orq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (orq *OrganizationRequestQuery) ExistX(ctx context.Context) bool {
	exist, err := orq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the OrganizationRequestQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (orq *OrganizationRequestQuery) Clone() *OrganizationRequestQuery {
	if orq == nil {
		return nil
	}
	return &OrganizationRequestQuery{
		config:     orq.config,
		ctx:        orq.ctx.Clone(),
		order:      append([]organizationrequest.OrderOption{}, orq.order...),
		inters:     append([]Interceptor{}, orq.inters...),
		predicates: append([]predicate.OrganizationRequest{}, orq.predicates...),
		// clone intermediate query.
		sql:  orq.sql.Clone(),
		path: orq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.OrganizationRequest.Query().
//		GroupBy(organizationrequest.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (orq *OrganizationRequestQuery) GroupBy(field string, fields ...string) *OrganizationRequestGroupBy {
	orq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &OrganizationRequestGroupBy{build: orq}
	grbuild.flds = &orq.ctx.Fields
	grbuild.label = organizationrequest.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.OrganizationRequest.Query().
//		Select(organizationrequest.FieldCreatedAt).
//		Scan(ctx, &v)
func (orq *OrganizationRequestQuery) Select(fields ...string) *OrganizationRequestSelect {
	orq.ctx.Fields = append(orq.ctx.Fields, fields...)
	sbuild := &OrganizationRequestSelect{OrganizationRequestQuery: orq}
	sbuild.label = organizationrequest.Label
	sbuild.flds, sbuild.scan = &orq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a OrganizationRequestSelect configured with the given aggregations.
func (orq *OrganizationRequestQuery) Aggregate(fns ...AggregateFunc) *OrganizationRequestSelect {
	return orq.Select().Aggregate(fns...)
}

func (orq *OrganizationRequestQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range orq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, orq); err != nil {
				return err
			}
		}
	}
	for _, f := range orq.ctx.Fields {
		if !organizationrequest.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if orq.path != nil {
		prev, err := orq.path(ctx)
		if err != nil {
			return err
		}
		orq.sql = prev
	}
	return nil
}

func (orq *OrganizationRequestQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*OrganizationRequest, error) {
	var (
		nodes = []*OrganizationRequest{}
		_spec = orq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*OrganizationRequest).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &OrganizationRequest{config: orq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	if len(orq.modifiers) > 0 {
		_spec.Modifiers = orq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, orq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (orq *OrganizationRequestQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := orq.querySpec()
	if len(orq.modifiers) > 0 {
		_spec.Modifiers = orq.modifiers
	}
	_spec.Node.Columns = orq.ctx.Fields
	if len(orq.ctx.Fields) > 0 {
		_spec.Unique = orq.ctx.Unique != nil && *orq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, orq.driver, _spec)
}

func (orq *OrganizationRequestQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(organizationrequest.Table, organizationrequest.Columns, sqlgraph.NewFieldSpec(organizationrequest.FieldID, field.TypeUUID))
	_spec.From = orq.sql
	if unique := orq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if orq.path != nil {
		_spec.Unique = true
	}
	if fields := orq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, organizationrequest.FieldID)
		for i := range fields {
			if fields[i] != organizationrequest.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := orq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := orq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := orq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := orq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (orq *OrganizationRequestQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(orq.driver.Dialect())
	t1 := builder.Table(organizationrequest.Table)
	columns := orq.ctx.Fields
	if len(columns) == 0 {
		columns = organizationrequest.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if orq.sql != nil {
		selector = orq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if orq.ctx.Unique != nil && *orq.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range orq.modifiers {
		m(selector)
	}
	for _, p := range orq.predicates {
		p(selector)
	}
	for _, p := range orq.order {
		p(selector)
	}
	if offset := orq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := orq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (orq *OrganizationRequestQuery) ForUpdate(opts ...sql.LockOption) *OrganizationRequestQuery {
	if orq.driver.Dialect() == dialect.Postgres {
		orq.Unique(false)
	}
	orq.modifiers = append(orq.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return orq
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (orq *OrganizationRequestQuery) ForShare(opts ...sql.LockOption) *OrganizationRequestQuery {
	if orq.driver.Dialect() == dialect.Postgres {
		orq.Unique(false)
	}
	orq.modifiers = append(orq.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return orq
}

// OrganizationRequestGroupBy is the group-by builder for OrganizationRequest entities.
type OrganizationRequestGroupBy struct {
	selector
	build *OrganizationRequestQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (orgb *OrganizationRequestGroupBy) Aggregate(fns ...AggregateFunc) *OrganizationRequestGroupBy {
	orgb.fns = append(orgb.fns, fns...)
	return orgb
}

// Scan applies the selector query and scans the result into the given value.
func (orgb *OrganizationRequestGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, orgb.build.ctx, ent.OpQueryGroupBy)
	if err := orgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*OrganizationRequestQuery, *OrganizationRequestGroupBy](ctx, orgb.build, orgb, orgb.build.inters, v)
}

func (orgb *OrganizationRequestGroupBy) sqlScan(ctx context.Context, root *OrganizationRequestQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(orgb.fns))
	for _, fn := range orgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*orgb.flds)+len(orgb.fns))
		for _, f := range *orgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*orgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := orgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// OrganizationRequestSelect is the builder for selecting fields of OrganizationRequest entities.
type OrganizationRequestSelect struct {
	*OrganizationRequestQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ors *OrganizationRequestSelect) Aggregate(fns ...AggregateFunc) *OrganizationRequestSelect {
	ors.fns = append(ors.fns, fns...)
	return ors
}

// Scan applies the selector query and scans the result into the given value.
func (ors *OrganizationRequestSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ors.ctx, ent.OpQuerySelect)
	if err := ors.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*OrganizationRequestQuery, *OrganizationRequestSelect](ctx, ors.OrganizationRequestQuery, ors, ors.inters, v)
}

func (ors *OrganizationRequestSelect) sqlScan(ctx context.Context, root *OrganizationRequestQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ors.fns))
	for _, fn := range ors.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ors.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ors.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
