// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"kiwi-user/internal/infrastructure/repository/ent/payment"
	"kiwi-user/internal/infrastructure/repository/ent/predicate"
	"kiwi-user/internal/infrastructure/repository/ent/user"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PaymentUpdate is the builder for updating Payment entities.
type PaymentUpdate struct {
	config
	hooks    []Hook
	mutation *PaymentMutation
}

// Where appends a list predicates to the PaymentUpdate builder.
func (pu *PaymentUpdate) Where(ps ...predicate.Payment) *PaymentUpdate {
	pu.mutation.Where(ps...)
	return pu
}

// SetUpdatedAt sets the "updated_at" field.
func (pu *PaymentUpdate) SetUpdatedAt(t time.Time) *PaymentUpdate {
	pu.mutation.SetUpdatedAt(t)
	return pu
}

// SetOutTradeNo sets the "out_trade_no" field.
func (pu *PaymentUpdate) SetOutTradeNo(s string) *PaymentUpdate {
	pu.mutation.SetOutTradeNo(s)
	return pu
}

// SetNillableOutTradeNo sets the "out_trade_no" field if the given value is not nil.
func (pu *PaymentUpdate) SetNillableOutTradeNo(s *string) *PaymentUpdate {
	if s != nil {
		pu.SetOutTradeNo(*s)
	}
	return pu
}

// SetUserID sets the "user_id" field.
func (pu *PaymentUpdate) SetUserID(s string) *PaymentUpdate {
	pu.mutation.SetUserID(s)
	return pu
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (pu *PaymentUpdate) SetNillableUserID(s *string) *PaymentUpdate {
	if s != nil {
		pu.SetUserID(*s)
	}
	return pu
}

// SetTransactionID sets the "transaction_id" field.
func (pu *PaymentUpdate) SetTransactionID(s string) *PaymentUpdate {
	pu.mutation.SetTransactionID(s)
	return pu
}

// SetNillableTransactionID sets the "transaction_id" field if the given value is not nil.
func (pu *PaymentUpdate) SetNillableTransactionID(s *string) *PaymentUpdate {
	if s != nil {
		pu.SetTransactionID(*s)
	}
	return pu
}

// ClearTransactionID clears the value of the "transaction_id" field.
func (pu *PaymentUpdate) ClearTransactionID() *PaymentUpdate {
	pu.mutation.ClearTransactionID()
	return pu
}

// SetOpenID sets the "open_id" field.
func (pu *PaymentUpdate) SetOpenID(s string) *PaymentUpdate {
	pu.mutation.SetOpenID(s)
	return pu
}

// SetNillableOpenID sets the "open_id" field if the given value is not nil.
func (pu *PaymentUpdate) SetNillableOpenID(s *string) *PaymentUpdate {
	if s != nil {
		pu.SetOpenID(*s)
	}
	return pu
}

// ClearOpenID clears the value of the "open_id" field.
func (pu *PaymentUpdate) ClearOpenID() *PaymentUpdate {
	pu.mutation.ClearOpenID()
	return pu
}

// SetChannel sets the "channel" field.
func (pu *PaymentUpdate) SetChannel(pa payment.Channel) *PaymentUpdate {
	pu.mutation.SetChannel(pa)
	return pu
}

// SetNillableChannel sets the "channel" field if the given value is not nil.
func (pu *PaymentUpdate) SetNillableChannel(pa *payment.Channel) *PaymentUpdate {
	if pa != nil {
		pu.SetChannel(*pa)
	}
	return pu
}

// SetPlatform sets the "platform" field.
func (pu *PaymentUpdate) SetPlatform(pa payment.Platform) *PaymentUpdate {
	pu.mutation.SetPlatform(pa)
	return pu
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (pu *PaymentUpdate) SetNillablePlatform(pa *payment.Platform) *PaymentUpdate {
	if pa != nil {
		pu.SetPlatform(*pa)
	}
	return pu
}

// SetService sets the "service" field.
func (pu *PaymentUpdate) SetService(s string) *PaymentUpdate {
	pu.mutation.SetService(s)
	return pu
}

// SetNillableService sets the "service" field if the given value is not nil.
func (pu *PaymentUpdate) SetNillableService(s *string) *PaymentUpdate {
	if s != nil {
		pu.SetService(*s)
	}
	return pu
}

// SetAmount sets the "amount" field.
func (pu *PaymentUpdate) SetAmount(i int) *PaymentUpdate {
	pu.mutation.ResetAmount()
	pu.mutation.SetAmount(i)
	return pu
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (pu *PaymentUpdate) SetNillableAmount(i *int) *PaymentUpdate {
	if i != nil {
		pu.SetAmount(*i)
	}
	return pu
}

// AddAmount adds i to the "amount" field.
func (pu *PaymentUpdate) AddAmount(i int) *PaymentUpdate {
	pu.mutation.AddAmount(i)
	return pu
}

// SetCurrency sets the "currency" field.
func (pu *PaymentUpdate) SetCurrency(s string) *PaymentUpdate {
	pu.mutation.SetCurrency(s)
	return pu
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (pu *PaymentUpdate) SetNillableCurrency(s *string) *PaymentUpdate {
	if s != nil {
		pu.SetCurrency(*s)
	}
	return pu
}

// SetDescription sets the "description" field.
func (pu *PaymentUpdate) SetDescription(s string) *PaymentUpdate {
	pu.mutation.SetDescription(s)
	return pu
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (pu *PaymentUpdate) SetNillableDescription(s *string) *PaymentUpdate {
	if s != nil {
		pu.SetDescription(*s)
	}
	return pu
}

// SetStatus sets the "status" field.
func (pu *PaymentUpdate) SetStatus(pa payment.Status) *PaymentUpdate {
	pu.mutation.SetStatus(pa)
	return pu
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (pu *PaymentUpdate) SetNillableStatus(pa *payment.Status) *PaymentUpdate {
	if pa != nil {
		pu.SetStatus(*pa)
	}
	return pu
}

// SetPaidAt sets the "paid_at" field.
func (pu *PaymentUpdate) SetPaidAt(t time.Time) *PaymentUpdate {
	pu.mutation.SetPaidAt(t)
	return pu
}

// SetNillablePaidAt sets the "paid_at" field if the given value is not nil.
func (pu *PaymentUpdate) SetNillablePaidAt(t *time.Time) *PaymentUpdate {
	if t != nil {
		pu.SetPaidAt(*t)
	}
	return pu
}

// ClearPaidAt clears the value of the "paid_at" field.
func (pu *PaymentUpdate) ClearPaidAt() *PaymentUpdate {
	pu.mutation.ClearPaidAt()
	return pu
}

// SetUser sets the "user" edge to the User entity.
func (pu *PaymentUpdate) SetUser(u *User) *PaymentUpdate {
	return pu.SetUserID(u.ID)
}

// Mutation returns the PaymentMutation object of the builder.
func (pu *PaymentUpdate) Mutation() *PaymentMutation {
	return pu.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (pu *PaymentUpdate) ClearUser() *PaymentUpdate {
	pu.mutation.ClearUser()
	return pu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (pu *PaymentUpdate) Save(ctx context.Context) (int, error) {
	pu.defaults()
	return withHooks(ctx, pu.sqlSave, pu.mutation, pu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (pu *PaymentUpdate) SaveX(ctx context.Context) int {
	affected, err := pu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (pu *PaymentUpdate) Exec(ctx context.Context) error {
	_, err := pu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pu *PaymentUpdate) ExecX(ctx context.Context) {
	if err := pu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (pu *PaymentUpdate) defaults() {
	if _, ok := pu.mutation.UpdatedAt(); !ok {
		v := payment.UpdateDefaultUpdatedAt()
		pu.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (pu *PaymentUpdate) check() error {
	if v, ok := pu.mutation.OutTradeNo(); ok {
		if err := payment.OutTradeNoValidator(v); err != nil {
			return &ValidationError{Name: "out_trade_no", err: fmt.Errorf(`ent: validator failed for field "Payment.out_trade_no": %w`, err)}
		}
	}
	if v, ok := pu.mutation.UserID(); ok {
		if err := payment.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "Payment.user_id": %w`, err)}
		}
	}
	if v, ok := pu.mutation.Channel(); ok {
		if err := payment.ChannelValidator(v); err != nil {
			return &ValidationError{Name: "channel", err: fmt.Errorf(`ent: validator failed for field "Payment.channel": %w`, err)}
		}
	}
	if v, ok := pu.mutation.Platform(); ok {
		if err := payment.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "Payment.platform": %w`, err)}
		}
	}
	if v, ok := pu.mutation.Service(); ok {
		if err := payment.ServiceValidator(v); err != nil {
			return &ValidationError{Name: "service", err: fmt.Errorf(`ent: validator failed for field "Payment.service": %w`, err)}
		}
	}
	if v, ok := pu.mutation.Amount(); ok {
		if err := payment.AmountValidator(v); err != nil {
			return &ValidationError{Name: "amount", err: fmt.Errorf(`ent: validator failed for field "Payment.amount": %w`, err)}
		}
	}
	if v, ok := pu.mutation.Currency(); ok {
		if err := payment.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "Payment.currency": %w`, err)}
		}
	}
	if v, ok := pu.mutation.Description(); ok {
		if err := payment.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "Payment.description": %w`, err)}
		}
	}
	if v, ok := pu.mutation.Status(); ok {
		if err := payment.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Payment.status": %w`, err)}
		}
	}
	if pu.mutation.UserCleared() && len(pu.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Payment.user"`)
	}
	return nil
}

func (pu *PaymentUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := pu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(payment.Table, payment.Columns, sqlgraph.NewFieldSpec(payment.FieldID, field.TypeInt))
	if ps := pu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := pu.mutation.UpdatedAt(); ok {
		_spec.SetField(payment.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := pu.mutation.OutTradeNo(); ok {
		_spec.SetField(payment.FieldOutTradeNo, field.TypeString, value)
	}
	if value, ok := pu.mutation.TransactionID(); ok {
		_spec.SetField(payment.FieldTransactionID, field.TypeString, value)
	}
	if pu.mutation.TransactionIDCleared() {
		_spec.ClearField(payment.FieldTransactionID, field.TypeString)
	}
	if value, ok := pu.mutation.OpenID(); ok {
		_spec.SetField(payment.FieldOpenID, field.TypeString, value)
	}
	if pu.mutation.OpenIDCleared() {
		_spec.ClearField(payment.FieldOpenID, field.TypeString)
	}
	if value, ok := pu.mutation.Channel(); ok {
		_spec.SetField(payment.FieldChannel, field.TypeEnum, value)
	}
	if value, ok := pu.mutation.Platform(); ok {
		_spec.SetField(payment.FieldPlatform, field.TypeEnum, value)
	}
	if value, ok := pu.mutation.Service(); ok {
		_spec.SetField(payment.FieldService, field.TypeString, value)
	}
	if value, ok := pu.mutation.Amount(); ok {
		_spec.SetField(payment.FieldAmount, field.TypeInt, value)
	}
	if value, ok := pu.mutation.AddedAmount(); ok {
		_spec.AddField(payment.FieldAmount, field.TypeInt, value)
	}
	if value, ok := pu.mutation.Currency(); ok {
		_spec.SetField(payment.FieldCurrency, field.TypeString, value)
	}
	if value, ok := pu.mutation.Description(); ok {
		_spec.SetField(payment.FieldDescription, field.TypeString, value)
	}
	if value, ok := pu.mutation.Status(); ok {
		_spec.SetField(payment.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := pu.mutation.PaidAt(); ok {
		_spec.SetField(payment.FieldPaidAt, field.TypeTime, value)
	}
	if pu.mutation.PaidAtCleared() {
		_spec.ClearField(payment.FieldPaidAt, field.TypeTime)
	}
	if pu.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   payment.UserTable,
			Columns: []string{payment.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pu.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   payment.UserTable,
			Columns: []string{payment.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, pu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{payment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	pu.mutation.done = true
	return n, nil
}

// PaymentUpdateOne is the builder for updating a single Payment entity.
type PaymentUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PaymentMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (puo *PaymentUpdateOne) SetUpdatedAt(t time.Time) *PaymentUpdateOne {
	puo.mutation.SetUpdatedAt(t)
	return puo
}

// SetOutTradeNo sets the "out_trade_no" field.
func (puo *PaymentUpdateOne) SetOutTradeNo(s string) *PaymentUpdateOne {
	puo.mutation.SetOutTradeNo(s)
	return puo
}

// SetNillableOutTradeNo sets the "out_trade_no" field if the given value is not nil.
func (puo *PaymentUpdateOne) SetNillableOutTradeNo(s *string) *PaymentUpdateOne {
	if s != nil {
		puo.SetOutTradeNo(*s)
	}
	return puo
}

// SetUserID sets the "user_id" field.
func (puo *PaymentUpdateOne) SetUserID(s string) *PaymentUpdateOne {
	puo.mutation.SetUserID(s)
	return puo
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (puo *PaymentUpdateOne) SetNillableUserID(s *string) *PaymentUpdateOne {
	if s != nil {
		puo.SetUserID(*s)
	}
	return puo
}

// SetTransactionID sets the "transaction_id" field.
func (puo *PaymentUpdateOne) SetTransactionID(s string) *PaymentUpdateOne {
	puo.mutation.SetTransactionID(s)
	return puo
}

// SetNillableTransactionID sets the "transaction_id" field if the given value is not nil.
func (puo *PaymentUpdateOne) SetNillableTransactionID(s *string) *PaymentUpdateOne {
	if s != nil {
		puo.SetTransactionID(*s)
	}
	return puo
}

// ClearTransactionID clears the value of the "transaction_id" field.
func (puo *PaymentUpdateOne) ClearTransactionID() *PaymentUpdateOne {
	puo.mutation.ClearTransactionID()
	return puo
}

// SetOpenID sets the "open_id" field.
func (puo *PaymentUpdateOne) SetOpenID(s string) *PaymentUpdateOne {
	puo.mutation.SetOpenID(s)
	return puo
}

// SetNillableOpenID sets the "open_id" field if the given value is not nil.
func (puo *PaymentUpdateOne) SetNillableOpenID(s *string) *PaymentUpdateOne {
	if s != nil {
		puo.SetOpenID(*s)
	}
	return puo
}

// ClearOpenID clears the value of the "open_id" field.
func (puo *PaymentUpdateOne) ClearOpenID() *PaymentUpdateOne {
	puo.mutation.ClearOpenID()
	return puo
}

// SetChannel sets the "channel" field.
func (puo *PaymentUpdateOne) SetChannel(pa payment.Channel) *PaymentUpdateOne {
	puo.mutation.SetChannel(pa)
	return puo
}

// SetNillableChannel sets the "channel" field if the given value is not nil.
func (puo *PaymentUpdateOne) SetNillableChannel(pa *payment.Channel) *PaymentUpdateOne {
	if pa != nil {
		puo.SetChannel(*pa)
	}
	return puo
}

// SetPlatform sets the "platform" field.
func (puo *PaymentUpdateOne) SetPlatform(pa payment.Platform) *PaymentUpdateOne {
	puo.mutation.SetPlatform(pa)
	return puo
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (puo *PaymentUpdateOne) SetNillablePlatform(pa *payment.Platform) *PaymentUpdateOne {
	if pa != nil {
		puo.SetPlatform(*pa)
	}
	return puo
}

// SetService sets the "service" field.
func (puo *PaymentUpdateOne) SetService(s string) *PaymentUpdateOne {
	puo.mutation.SetService(s)
	return puo
}

// SetNillableService sets the "service" field if the given value is not nil.
func (puo *PaymentUpdateOne) SetNillableService(s *string) *PaymentUpdateOne {
	if s != nil {
		puo.SetService(*s)
	}
	return puo
}

// SetAmount sets the "amount" field.
func (puo *PaymentUpdateOne) SetAmount(i int) *PaymentUpdateOne {
	puo.mutation.ResetAmount()
	puo.mutation.SetAmount(i)
	return puo
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (puo *PaymentUpdateOne) SetNillableAmount(i *int) *PaymentUpdateOne {
	if i != nil {
		puo.SetAmount(*i)
	}
	return puo
}

// AddAmount adds i to the "amount" field.
func (puo *PaymentUpdateOne) AddAmount(i int) *PaymentUpdateOne {
	puo.mutation.AddAmount(i)
	return puo
}

// SetCurrency sets the "currency" field.
func (puo *PaymentUpdateOne) SetCurrency(s string) *PaymentUpdateOne {
	puo.mutation.SetCurrency(s)
	return puo
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (puo *PaymentUpdateOne) SetNillableCurrency(s *string) *PaymentUpdateOne {
	if s != nil {
		puo.SetCurrency(*s)
	}
	return puo
}

// SetDescription sets the "description" field.
func (puo *PaymentUpdateOne) SetDescription(s string) *PaymentUpdateOne {
	puo.mutation.SetDescription(s)
	return puo
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (puo *PaymentUpdateOne) SetNillableDescription(s *string) *PaymentUpdateOne {
	if s != nil {
		puo.SetDescription(*s)
	}
	return puo
}

// SetStatus sets the "status" field.
func (puo *PaymentUpdateOne) SetStatus(pa payment.Status) *PaymentUpdateOne {
	puo.mutation.SetStatus(pa)
	return puo
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (puo *PaymentUpdateOne) SetNillableStatus(pa *payment.Status) *PaymentUpdateOne {
	if pa != nil {
		puo.SetStatus(*pa)
	}
	return puo
}

// SetPaidAt sets the "paid_at" field.
func (puo *PaymentUpdateOne) SetPaidAt(t time.Time) *PaymentUpdateOne {
	puo.mutation.SetPaidAt(t)
	return puo
}

// SetNillablePaidAt sets the "paid_at" field if the given value is not nil.
func (puo *PaymentUpdateOne) SetNillablePaidAt(t *time.Time) *PaymentUpdateOne {
	if t != nil {
		puo.SetPaidAt(*t)
	}
	return puo
}

// ClearPaidAt clears the value of the "paid_at" field.
func (puo *PaymentUpdateOne) ClearPaidAt() *PaymentUpdateOne {
	puo.mutation.ClearPaidAt()
	return puo
}

// SetUser sets the "user" edge to the User entity.
func (puo *PaymentUpdateOne) SetUser(u *User) *PaymentUpdateOne {
	return puo.SetUserID(u.ID)
}

// Mutation returns the PaymentMutation object of the builder.
func (puo *PaymentUpdateOne) Mutation() *PaymentMutation {
	return puo.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (puo *PaymentUpdateOne) ClearUser() *PaymentUpdateOne {
	puo.mutation.ClearUser()
	return puo
}

// Where appends a list predicates to the PaymentUpdate builder.
func (puo *PaymentUpdateOne) Where(ps ...predicate.Payment) *PaymentUpdateOne {
	puo.mutation.Where(ps...)
	return puo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (puo *PaymentUpdateOne) Select(field string, fields ...string) *PaymentUpdateOne {
	puo.fields = append([]string{field}, fields...)
	return puo
}

// Save executes the query and returns the updated Payment entity.
func (puo *PaymentUpdateOne) Save(ctx context.Context) (*Payment, error) {
	puo.defaults()
	return withHooks(ctx, puo.sqlSave, puo.mutation, puo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (puo *PaymentUpdateOne) SaveX(ctx context.Context) *Payment {
	node, err := puo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (puo *PaymentUpdateOne) Exec(ctx context.Context) error {
	_, err := puo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (puo *PaymentUpdateOne) ExecX(ctx context.Context) {
	if err := puo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (puo *PaymentUpdateOne) defaults() {
	if _, ok := puo.mutation.UpdatedAt(); !ok {
		v := payment.UpdateDefaultUpdatedAt()
		puo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (puo *PaymentUpdateOne) check() error {
	if v, ok := puo.mutation.OutTradeNo(); ok {
		if err := payment.OutTradeNoValidator(v); err != nil {
			return &ValidationError{Name: "out_trade_no", err: fmt.Errorf(`ent: validator failed for field "Payment.out_trade_no": %w`, err)}
		}
	}
	if v, ok := puo.mutation.UserID(); ok {
		if err := payment.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "Payment.user_id": %w`, err)}
		}
	}
	if v, ok := puo.mutation.Channel(); ok {
		if err := payment.ChannelValidator(v); err != nil {
			return &ValidationError{Name: "channel", err: fmt.Errorf(`ent: validator failed for field "Payment.channel": %w`, err)}
		}
	}
	if v, ok := puo.mutation.Platform(); ok {
		if err := payment.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "Payment.platform": %w`, err)}
		}
	}
	if v, ok := puo.mutation.Service(); ok {
		if err := payment.ServiceValidator(v); err != nil {
			return &ValidationError{Name: "service", err: fmt.Errorf(`ent: validator failed for field "Payment.service": %w`, err)}
		}
	}
	if v, ok := puo.mutation.Amount(); ok {
		if err := payment.AmountValidator(v); err != nil {
			return &ValidationError{Name: "amount", err: fmt.Errorf(`ent: validator failed for field "Payment.amount": %w`, err)}
		}
	}
	if v, ok := puo.mutation.Currency(); ok {
		if err := payment.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "Payment.currency": %w`, err)}
		}
	}
	if v, ok := puo.mutation.Description(); ok {
		if err := payment.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "Payment.description": %w`, err)}
		}
	}
	if v, ok := puo.mutation.Status(); ok {
		if err := payment.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Payment.status": %w`, err)}
		}
	}
	if puo.mutation.UserCleared() && len(puo.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Payment.user"`)
	}
	return nil
}

func (puo *PaymentUpdateOne) sqlSave(ctx context.Context) (_node *Payment, err error) {
	if err := puo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(payment.Table, payment.Columns, sqlgraph.NewFieldSpec(payment.FieldID, field.TypeInt))
	id, ok := puo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Payment.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := puo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, payment.FieldID)
		for _, f := range fields {
			if !payment.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != payment.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := puo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := puo.mutation.UpdatedAt(); ok {
		_spec.SetField(payment.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := puo.mutation.OutTradeNo(); ok {
		_spec.SetField(payment.FieldOutTradeNo, field.TypeString, value)
	}
	if value, ok := puo.mutation.TransactionID(); ok {
		_spec.SetField(payment.FieldTransactionID, field.TypeString, value)
	}
	if puo.mutation.TransactionIDCleared() {
		_spec.ClearField(payment.FieldTransactionID, field.TypeString)
	}
	if value, ok := puo.mutation.OpenID(); ok {
		_spec.SetField(payment.FieldOpenID, field.TypeString, value)
	}
	if puo.mutation.OpenIDCleared() {
		_spec.ClearField(payment.FieldOpenID, field.TypeString)
	}
	if value, ok := puo.mutation.Channel(); ok {
		_spec.SetField(payment.FieldChannel, field.TypeEnum, value)
	}
	if value, ok := puo.mutation.Platform(); ok {
		_spec.SetField(payment.FieldPlatform, field.TypeEnum, value)
	}
	if value, ok := puo.mutation.Service(); ok {
		_spec.SetField(payment.FieldService, field.TypeString, value)
	}
	if value, ok := puo.mutation.Amount(); ok {
		_spec.SetField(payment.FieldAmount, field.TypeInt, value)
	}
	if value, ok := puo.mutation.AddedAmount(); ok {
		_spec.AddField(payment.FieldAmount, field.TypeInt, value)
	}
	if value, ok := puo.mutation.Currency(); ok {
		_spec.SetField(payment.FieldCurrency, field.TypeString, value)
	}
	if value, ok := puo.mutation.Description(); ok {
		_spec.SetField(payment.FieldDescription, field.TypeString, value)
	}
	if value, ok := puo.mutation.Status(); ok {
		_spec.SetField(payment.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := puo.mutation.PaidAt(); ok {
		_spec.SetField(payment.FieldPaidAt, field.TypeTime, value)
	}
	if puo.mutation.PaidAtCleared() {
		_spec.ClearField(payment.FieldPaidAt, field.TypeTime)
	}
	if puo.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   payment.UserTable,
			Columns: []string{payment.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := puo.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   payment.UserTable,
			Columns: []string{payment.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Payment{config: puo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, puo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{payment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	puo.mutation.done = true
	return _node, nil
}
