// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"kiwi-user/internal/infrastructure/repository/ent/payment"
	"kiwi-user/internal/infrastructure/repository/ent/predicate"
	"kiwi-user/internal/infrastructure/repository/ent/user"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PaymentUpdate is the builder for updating Payment entities.
type PaymentUpdate struct {
	config
	hooks    []Hook
	mutation *PaymentMutation
}

// Where appends a list predicates to the PaymentUpdate builder.
func (pu *PaymentUpdate) Where(ps ...predicate.Payment) *PaymentUpdate {
	pu.mutation.Where(ps...)
	return pu
}

// SetUpdatedAt sets the "updated_at" field.
func (pu *PaymentUpdate) SetUpdatedAt(t time.Time) *PaymentUpdate {
	pu.mutation.SetUpdatedAt(t)
	return pu
}

// SetOutTradeNo sets the "out_trade_no" field.
func (pu *PaymentUpdate) SetOutTradeNo(s string) *PaymentUpdate {
	pu.mutation.SetOutTradeNo(s)
	return pu
}

// SetNillableOutTradeNo sets the "out_trade_no" field if the given value is not nil.
func (pu *PaymentUpdate) SetNillableOutTradeNo(s *string) *PaymentUpdate {
	if s != nil {
		pu.SetOutTradeNo(*s)
	}
	return pu
}

// SetUserID sets the "user_id" field.
func (pu *PaymentUpdate) SetUserID(s string) *PaymentUpdate {
	pu.mutation.SetUserID(s)
	return pu
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (pu *PaymentUpdate) SetNillableUserID(s *string) *PaymentUpdate {
	if s != nil {
		pu.SetUserID(*s)
	}
	return pu
}

// SetChannel sets the "channel" field.
func (pu *PaymentUpdate) SetChannel(pa payment.Channel) *PaymentUpdate {
	pu.mutation.SetChannel(pa)
	return pu
}

// SetNillableChannel sets the "channel" field if the given value is not nil.
func (pu *PaymentUpdate) SetNillableChannel(pa *payment.Channel) *PaymentUpdate {
	if pa != nil {
		pu.SetChannel(*pa)
	}
	return pu
}

// SetService sets the "service" field.
func (pu *PaymentUpdate) SetService(s string) *PaymentUpdate {
	pu.mutation.SetService(s)
	return pu
}

// SetNillableService sets the "service" field if the given value is not nil.
func (pu *PaymentUpdate) SetNillableService(s *string) *PaymentUpdate {
	if s != nil {
		pu.SetService(*s)
	}
	return pu
}

// SetAmount sets the "amount" field.
func (pu *PaymentUpdate) SetAmount(i int) *PaymentUpdate {
	pu.mutation.ResetAmount()
	pu.mutation.SetAmount(i)
	return pu
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (pu *PaymentUpdate) SetNillableAmount(i *int) *PaymentUpdate {
	if i != nil {
		pu.SetAmount(*i)
	}
	return pu
}

// AddAmount adds i to the "amount" field.
func (pu *PaymentUpdate) AddAmount(i int) *PaymentUpdate {
	pu.mutation.AddAmount(i)
	return pu
}

// SetCurrency sets the "currency" field.
func (pu *PaymentUpdate) SetCurrency(s string) *PaymentUpdate {
	pu.mutation.SetCurrency(s)
	return pu
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (pu *PaymentUpdate) SetNillableCurrency(s *string) *PaymentUpdate {
	if s != nil {
		pu.SetCurrency(*s)
	}
	return pu
}

// SetDescription sets the "description" field.
func (pu *PaymentUpdate) SetDescription(s string) *PaymentUpdate {
	pu.mutation.SetDescription(s)
	return pu
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (pu *PaymentUpdate) SetNillableDescription(s *string) *PaymentUpdate {
	if s != nil {
		pu.SetDescription(*s)
	}
	return pu
}

// SetStatus sets the "status" field.
func (pu *PaymentUpdate) SetStatus(pa payment.Status) *PaymentUpdate {
	pu.mutation.SetStatus(pa)
	return pu
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (pu *PaymentUpdate) SetNillableStatus(pa *payment.Status) *PaymentUpdate {
	if pa != nil {
		pu.SetStatus(*pa)
	}
	return pu
}

// SetPaidAt sets the "paid_at" field.
func (pu *PaymentUpdate) SetPaidAt(t time.Time) *PaymentUpdate {
	pu.mutation.SetPaidAt(t)
	return pu
}

// SetNillablePaidAt sets the "paid_at" field if the given value is not nil.
func (pu *PaymentUpdate) SetNillablePaidAt(t *time.Time) *PaymentUpdate {
	if t != nil {
		pu.SetPaidAt(*t)
	}
	return pu
}

// ClearPaidAt clears the value of the "paid_at" field.
func (pu *PaymentUpdate) ClearPaidAt() *PaymentUpdate {
	pu.mutation.ClearPaidAt()
	return pu
}

// SetPaymentType sets the "payment_type" field.
func (pu *PaymentUpdate) SetPaymentType(pt payment.PaymentType) *PaymentUpdate {
	pu.mutation.SetPaymentType(pt)
	return pu
}

// SetNillablePaymentType sets the "payment_type" field if the given value is not nil.
func (pu *PaymentUpdate) SetNillablePaymentType(pt *payment.PaymentType) *PaymentUpdate {
	if pt != nil {
		pu.SetPaymentType(*pt)
	}
	return pu
}

// SetWechatPlatform sets the "wechat_platform" field.
func (pu *PaymentUpdate) SetWechatPlatform(s string) *PaymentUpdate {
	pu.mutation.SetWechatPlatform(s)
	return pu
}

// SetNillableWechatPlatform sets the "wechat_platform" field if the given value is not nil.
func (pu *PaymentUpdate) SetNillableWechatPlatform(s *string) *PaymentUpdate {
	if s != nil {
		pu.SetWechatPlatform(*s)
	}
	return pu
}

// ClearWechatPlatform clears the value of the "wechat_platform" field.
func (pu *PaymentUpdate) ClearWechatPlatform() *PaymentUpdate {
	pu.mutation.ClearWechatPlatform()
	return pu
}

// SetWechatOpenID sets the "wechat_open_id" field.
func (pu *PaymentUpdate) SetWechatOpenID(s string) *PaymentUpdate {
	pu.mutation.SetWechatOpenID(s)
	return pu
}

// SetNillableWechatOpenID sets the "wechat_open_id" field if the given value is not nil.
func (pu *PaymentUpdate) SetNillableWechatOpenID(s *string) *PaymentUpdate {
	if s != nil {
		pu.SetWechatOpenID(*s)
	}
	return pu
}

// ClearWechatOpenID clears the value of the "wechat_open_id" field.
func (pu *PaymentUpdate) ClearWechatOpenID() *PaymentUpdate {
	pu.mutation.ClearWechatOpenID()
	return pu
}

// SetWechatTransactionID sets the "wechat_transaction_id" field.
func (pu *PaymentUpdate) SetWechatTransactionID(s string) *PaymentUpdate {
	pu.mutation.SetWechatTransactionID(s)
	return pu
}

// SetNillableWechatTransactionID sets the "wechat_transaction_id" field if the given value is not nil.
func (pu *PaymentUpdate) SetNillableWechatTransactionID(s *string) *PaymentUpdate {
	if s != nil {
		pu.SetWechatTransactionID(*s)
	}
	return pu
}

// ClearWechatTransactionID clears the value of the "wechat_transaction_id" field.
func (pu *PaymentUpdate) ClearWechatTransactionID() *PaymentUpdate {
	pu.mutation.ClearWechatTransactionID()
	return pu
}

// SetStripeSubscriptionID sets the "stripe_subscription_id" field.
func (pu *PaymentUpdate) SetStripeSubscriptionID(s string) *PaymentUpdate {
	pu.mutation.SetStripeSubscriptionID(s)
	return pu
}

// SetNillableStripeSubscriptionID sets the "stripe_subscription_id" field if the given value is not nil.
func (pu *PaymentUpdate) SetNillableStripeSubscriptionID(s *string) *PaymentUpdate {
	if s != nil {
		pu.SetStripeSubscriptionID(*s)
	}
	return pu
}

// ClearStripeSubscriptionID clears the value of the "stripe_subscription_id" field.
func (pu *PaymentUpdate) ClearStripeSubscriptionID() *PaymentUpdate {
	pu.mutation.ClearStripeSubscriptionID()
	return pu
}

// SetStripeSubscriptionStatus sets the "stripe_subscription_status" field.
func (pu *PaymentUpdate) SetStripeSubscriptionStatus(s string) *PaymentUpdate {
	pu.mutation.SetStripeSubscriptionStatus(s)
	return pu
}

// SetNillableStripeSubscriptionStatus sets the "stripe_subscription_status" field if the given value is not nil.
func (pu *PaymentUpdate) SetNillableStripeSubscriptionStatus(s *string) *PaymentUpdate {
	if s != nil {
		pu.SetStripeSubscriptionStatus(*s)
	}
	return pu
}

// ClearStripeSubscriptionStatus clears the value of the "stripe_subscription_status" field.
func (pu *PaymentUpdate) ClearStripeSubscriptionStatus() *PaymentUpdate {
	pu.mutation.ClearStripeSubscriptionStatus()
	return pu
}

// SetStripeInterval sets the "stripe_interval" field.
func (pu *PaymentUpdate) SetStripeInterval(s string) *PaymentUpdate {
	pu.mutation.SetStripeInterval(s)
	return pu
}

// SetNillableStripeInterval sets the "stripe_interval" field if the given value is not nil.
func (pu *PaymentUpdate) SetNillableStripeInterval(s *string) *PaymentUpdate {
	if s != nil {
		pu.SetStripeInterval(*s)
	}
	return pu
}

// ClearStripeInterval clears the value of the "stripe_interval" field.
func (pu *PaymentUpdate) ClearStripeInterval() *PaymentUpdate {
	pu.mutation.ClearStripeInterval()
	return pu
}

// SetStripeCurrentPeriodStart sets the "stripe_current_period_start" field.
func (pu *PaymentUpdate) SetStripeCurrentPeriodStart(t time.Time) *PaymentUpdate {
	pu.mutation.SetStripeCurrentPeriodStart(t)
	return pu
}

// SetNillableStripeCurrentPeriodStart sets the "stripe_current_period_start" field if the given value is not nil.
func (pu *PaymentUpdate) SetNillableStripeCurrentPeriodStart(t *time.Time) *PaymentUpdate {
	if t != nil {
		pu.SetStripeCurrentPeriodStart(*t)
	}
	return pu
}

// ClearStripeCurrentPeriodStart clears the value of the "stripe_current_period_start" field.
func (pu *PaymentUpdate) ClearStripeCurrentPeriodStart() *PaymentUpdate {
	pu.mutation.ClearStripeCurrentPeriodStart()
	return pu
}

// SetStripeCurrentPeriodEnd sets the "stripe_current_period_end" field.
func (pu *PaymentUpdate) SetStripeCurrentPeriodEnd(t time.Time) *PaymentUpdate {
	pu.mutation.SetStripeCurrentPeriodEnd(t)
	return pu
}

// SetNillableStripeCurrentPeriodEnd sets the "stripe_current_period_end" field if the given value is not nil.
func (pu *PaymentUpdate) SetNillableStripeCurrentPeriodEnd(t *time.Time) *PaymentUpdate {
	if t != nil {
		pu.SetStripeCurrentPeriodEnd(*t)
	}
	return pu
}

// ClearStripeCurrentPeriodEnd clears the value of the "stripe_current_period_end" field.
func (pu *PaymentUpdate) ClearStripeCurrentPeriodEnd() *PaymentUpdate {
	pu.mutation.ClearStripeCurrentPeriodEnd()
	return pu
}

// SetStripeCustomerID sets the "stripe_customer_id" field.
func (pu *PaymentUpdate) SetStripeCustomerID(s string) *PaymentUpdate {
	pu.mutation.SetStripeCustomerID(s)
	return pu
}

// SetNillableStripeCustomerID sets the "stripe_customer_id" field if the given value is not nil.
func (pu *PaymentUpdate) SetNillableStripeCustomerID(s *string) *PaymentUpdate {
	if s != nil {
		pu.SetStripeCustomerID(*s)
	}
	return pu
}

// ClearStripeCustomerID clears the value of the "stripe_customer_id" field.
func (pu *PaymentUpdate) ClearStripeCustomerID() *PaymentUpdate {
	pu.mutation.ClearStripeCustomerID()
	return pu
}

// SetStripeCustomerEmail sets the "stripe_customer_email" field.
func (pu *PaymentUpdate) SetStripeCustomerEmail(s string) *PaymentUpdate {
	pu.mutation.SetStripeCustomerEmail(s)
	return pu
}

// SetNillableStripeCustomerEmail sets the "stripe_customer_email" field if the given value is not nil.
func (pu *PaymentUpdate) SetNillableStripeCustomerEmail(s *string) *PaymentUpdate {
	if s != nil {
		pu.SetStripeCustomerEmail(*s)
	}
	return pu
}

// ClearStripeCustomerEmail clears the value of the "stripe_customer_email" field.
func (pu *PaymentUpdate) ClearStripeCustomerEmail() *PaymentUpdate {
	pu.mutation.ClearStripeCustomerEmail()
	return pu
}

// SetStripeCheckoutSessionID sets the "stripe_checkout_session_id" field.
func (pu *PaymentUpdate) SetStripeCheckoutSessionID(s string) *PaymentUpdate {
	pu.mutation.SetStripeCheckoutSessionID(s)
	return pu
}

// SetNillableStripeCheckoutSessionID sets the "stripe_checkout_session_id" field if the given value is not nil.
func (pu *PaymentUpdate) SetNillableStripeCheckoutSessionID(s *string) *PaymentUpdate {
	if s != nil {
		pu.SetStripeCheckoutSessionID(*s)
	}
	return pu
}

// ClearStripeCheckoutSessionID clears the value of the "stripe_checkout_session_id" field.
func (pu *PaymentUpdate) ClearStripeCheckoutSessionID() *PaymentUpdate {
	pu.mutation.ClearStripeCheckoutSessionID()
	return pu
}

// SetStripeInvoiceID sets the "stripe_invoice_id" field.
func (pu *PaymentUpdate) SetStripeInvoiceID(s string) *PaymentUpdate {
	pu.mutation.SetStripeInvoiceID(s)
	return pu
}

// SetNillableStripeInvoiceID sets the "stripe_invoice_id" field if the given value is not nil.
func (pu *PaymentUpdate) SetNillableStripeInvoiceID(s *string) *PaymentUpdate {
	if s != nil {
		pu.SetStripeInvoiceID(*s)
	}
	return pu
}

// ClearStripeInvoiceID clears the value of the "stripe_invoice_id" field.
func (pu *PaymentUpdate) ClearStripeInvoiceID() *PaymentUpdate {
	pu.mutation.ClearStripeInvoiceID()
	return pu
}

// SetUser sets the "user" edge to the User entity.
func (pu *PaymentUpdate) SetUser(u *User) *PaymentUpdate {
	return pu.SetUserID(u.ID)
}

// Mutation returns the PaymentMutation object of the builder.
func (pu *PaymentUpdate) Mutation() *PaymentMutation {
	return pu.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (pu *PaymentUpdate) ClearUser() *PaymentUpdate {
	pu.mutation.ClearUser()
	return pu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (pu *PaymentUpdate) Save(ctx context.Context) (int, error) {
	pu.defaults()
	return withHooks(ctx, pu.sqlSave, pu.mutation, pu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (pu *PaymentUpdate) SaveX(ctx context.Context) int {
	affected, err := pu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (pu *PaymentUpdate) Exec(ctx context.Context) error {
	_, err := pu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pu *PaymentUpdate) ExecX(ctx context.Context) {
	if err := pu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (pu *PaymentUpdate) defaults() {
	if _, ok := pu.mutation.UpdatedAt(); !ok {
		v := payment.UpdateDefaultUpdatedAt()
		pu.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (pu *PaymentUpdate) check() error {
	if v, ok := pu.mutation.OutTradeNo(); ok {
		if err := payment.OutTradeNoValidator(v); err != nil {
			return &ValidationError{Name: "out_trade_no", err: fmt.Errorf(`ent: validator failed for field "Payment.out_trade_no": %w`, err)}
		}
	}
	if v, ok := pu.mutation.UserID(); ok {
		if err := payment.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "Payment.user_id": %w`, err)}
		}
	}
	if v, ok := pu.mutation.Channel(); ok {
		if err := payment.ChannelValidator(v); err != nil {
			return &ValidationError{Name: "channel", err: fmt.Errorf(`ent: validator failed for field "Payment.channel": %w`, err)}
		}
	}
	if v, ok := pu.mutation.Service(); ok {
		if err := payment.ServiceValidator(v); err != nil {
			return &ValidationError{Name: "service", err: fmt.Errorf(`ent: validator failed for field "Payment.service": %w`, err)}
		}
	}
	if v, ok := pu.mutation.Amount(); ok {
		if err := payment.AmountValidator(v); err != nil {
			return &ValidationError{Name: "amount", err: fmt.Errorf(`ent: validator failed for field "Payment.amount": %w`, err)}
		}
	}
	if v, ok := pu.mutation.Currency(); ok {
		if err := payment.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "Payment.currency": %w`, err)}
		}
	}
	if v, ok := pu.mutation.Description(); ok {
		if err := payment.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "Payment.description": %w`, err)}
		}
	}
	if v, ok := pu.mutation.Status(); ok {
		if err := payment.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Payment.status": %w`, err)}
		}
	}
	if v, ok := pu.mutation.PaymentType(); ok {
		if err := payment.PaymentTypeValidator(v); err != nil {
			return &ValidationError{Name: "payment_type", err: fmt.Errorf(`ent: validator failed for field "Payment.payment_type": %w`, err)}
		}
	}
	if pu.mutation.UserCleared() && len(pu.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Payment.user"`)
	}
	return nil
}

func (pu *PaymentUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := pu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(payment.Table, payment.Columns, sqlgraph.NewFieldSpec(payment.FieldID, field.TypeInt))
	if ps := pu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := pu.mutation.UpdatedAt(); ok {
		_spec.SetField(payment.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := pu.mutation.OutTradeNo(); ok {
		_spec.SetField(payment.FieldOutTradeNo, field.TypeString, value)
	}
	if value, ok := pu.mutation.Channel(); ok {
		_spec.SetField(payment.FieldChannel, field.TypeEnum, value)
	}
	if value, ok := pu.mutation.Service(); ok {
		_spec.SetField(payment.FieldService, field.TypeString, value)
	}
	if value, ok := pu.mutation.Amount(); ok {
		_spec.SetField(payment.FieldAmount, field.TypeInt, value)
	}
	if value, ok := pu.mutation.AddedAmount(); ok {
		_spec.AddField(payment.FieldAmount, field.TypeInt, value)
	}
	if value, ok := pu.mutation.Currency(); ok {
		_spec.SetField(payment.FieldCurrency, field.TypeString, value)
	}
	if value, ok := pu.mutation.Description(); ok {
		_spec.SetField(payment.FieldDescription, field.TypeString, value)
	}
	if value, ok := pu.mutation.Status(); ok {
		_spec.SetField(payment.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := pu.mutation.PaidAt(); ok {
		_spec.SetField(payment.FieldPaidAt, field.TypeTime, value)
	}
	if pu.mutation.PaidAtCleared() {
		_spec.ClearField(payment.FieldPaidAt, field.TypeTime)
	}
	if value, ok := pu.mutation.PaymentType(); ok {
		_spec.SetField(payment.FieldPaymentType, field.TypeEnum, value)
	}
	if value, ok := pu.mutation.WechatPlatform(); ok {
		_spec.SetField(payment.FieldWechatPlatform, field.TypeString, value)
	}
	if pu.mutation.WechatPlatformCleared() {
		_spec.ClearField(payment.FieldWechatPlatform, field.TypeString)
	}
	if value, ok := pu.mutation.WechatOpenID(); ok {
		_spec.SetField(payment.FieldWechatOpenID, field.TypeString, value)
	}
	if pu.mutation.WechatOpenIDCleared() {
		_spec.ClearField(payment.FieldWechatOpenID, field.TypeString)
	}
	if value, ok := pu.mutation.WechatTransactionID(); ok {
		_spec.SetField(payment.FieldWechatTransactionID, field.TypeString, value)
	}
	if pu.mutation.WechatTransactionIDCleared() {
		_spec.ClearField(payment.FieldWechatTransactionID, field.TypeString)
	}
	if value, ok := pu.mutation.StripeSubscriptionID(); ok {
		_spec.SetField(payment.FieldStripeSubscriptionID, field.TypeString, value)
	}
	if pu.mutation.StripeSubscriptionIDCleared() {
		_spec.ClearField(payment.FieldStripeSubscriptionID, field.TypeString)
	}
	if value, ok := pu.mutation.StripeSubscriptionStatus(); ok {
		_spec.SetField(payment.FieldStripeSubscriptionStatus, field.TypeString, value)
	}
	if pu.mutation.StripeSubscriptionStatusCleared() {
		_spec.ClearField(payment.FieldStripeSubscriptionStatus, field.TypeString)
	}
	if value, ok := pu.mutation.StripeInterval(); ok {
		_spec.SetField(payment.FieldStripeInterval, field.TypeString, value)
	}
	if pu.mutation.StripeIntervalCleared() {
		_spec.ClearField(payment.FieldStripeInterval, field.TypeString)
	}
	if value, ok := pu.mutation.StripeCurrentPeriodStart(); ok {
		_spec.SetField(payment.FieldStripeCurrentPeriodStart, field.TypeTime, value)
	}
	if pu.mutation.StripeCurrentPeriodStartCleared() {
		_spec.ClearField(payment.FieldStripeCurrentPeriodStart, field.TypeTime)
	}
	if value, ok := pu.mutation.StripeCurrentPeriodEnd(); ok {
		_spec.SetField(payment.FieldStripeCurrentPeriodEnd, field.TypeTime, value)
	}
	if pu.mutation.StripeCurrentPeriodEndCleared() {
		_spec.ClearField(payment.FieldStripeCurrentPeriodEnd, field.TypeTime)
	}
	if value, ok := pu.mutation.StripeCustomerID(); ok {
		_spec.SetField(payment.FieldStripeCustomerID, field.TypeString, value)
	}
	if pu.mutation.StripeCustomerIDCleared() {
		_spec.ClearField(payment.FieldStripeCustomerID, field.TypeString)
	}
	if value, ok := pu.mutation.StripeCustomerEmail(); ok {
		_spec.SetField(payment.FieldStripeCustomerEmail, field.TypeString, value)
	}
	if pu.mutation.StripeCustomerEmailCleared() {
		_spec.ClearField(payment.FieldStripeCustomerEmail, field.TypeString)
	}
	if value, ok := pu.mutation.StripeCheckoutSessionID(); ok {
		_spec.SetField(payment.FieldStripeCheckoutSessionID, field.TypeString, value)
	}
	if pu.mutation.StripeCheckoutSessionIDCleared() {
		_spec.ClearField(payment.FieldStripeCheckoutSessionID, field.TypeString)
	}
	if value, ok := pu.mutation.StripeInvoiceID(); ok {
		_spec.SetField(payment.FieldStripeInvoiceID, field.TypeString, value)
	}
	if pu.mutation.StripeInvoiceIDCleared() {
		_spec.ClearField(payment.FieldStripeInvoiceID, field.TypeString)
	}
	if pu.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   payment.UserTable,
			Columns: []string{payment.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pu.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   payment.UserTable,
			Columns: []string{payment.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, pu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{payment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	pu.mutation.done = true
	return n, nil
}

// PaymentUpdateOne is the builder for updating a single Payment entity.
type PaymentUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PaymentMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (puo *PaymentUpdateOne) SetUpdatedAt(t time.Time) *PaymentUpdateOne {
	puo.mutation.SetUpdatedAt(t)
	return puo
}

// SetOutTradeNo sets the "out_trade_no" field.
func (puo *PaymentUpdateOne) SetOutTradeNo(s string) *PaymentUpdateOne {
	puo.mutation.SetOutTradeNo(s)
	return puo
}

// SetNillableOutTradeNo sets the "out_trade_no" field if the given value is not nil.
func (puo *PaymentUpdateOne) SetNillableOutTradeNo(s *string) *PaymentUpdateOne {
	if s != nil {
		puo.SetOutTradeNo(*s)
	}
	return puo
}

// SetUserID sets the "user_id" field.
func (puo *PaymentUpdateOne) SetUserID(s string) *PaymentUpdateOne {
	puo.mutation.SetUserID(s)
	return puo
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (puo *PaymentUpdateOne) SetNillableUserID(s *string) *PaymentUpdateOne {
	if s != nil {
		puo.SetUserID(*s)
	}
	return puo
}

// SetChannel sets the "channel" field.
func (puo *PaymentUpdateOne) SetChannel(pa payment.Channel) *PaymentUpdateOne {
	puo.mutation.SetChannel(pa)
	return puo
}

// SetNillableChannel sets the "channel" field if the given value is not nil.
func (puo *PaymentUpdateOne) SetNillableChannel(pa *payment.Channel) *PaymentUpdateOne {
	if pa != nil {
		puo.SetChannel(*pa)
	}
	return puo
}

// SetService sets the "service" field.
func (puo *PaymentUpdateOne) SetService(s string) *PaymentUpdateOne {
	puo.mutation.SetService(s)
	return puo
}

// SetNillableService sets the "service" field if the given value is not nil.
func (puo *PaymentUpdateOne) SetNillableService(s *string) *PaymentUpdateOne {
	if s != nil {
		puo.SetService(*s)
	}
	return puo
}

// SetAmount sets the "amount" field.
func (puo *PaymentUpdateOne) SetAmount(i int) *PaymentUpdateOne {
	puo.mutation.ResetAmount()
	puo.mutation.SetAmount(i)
	return puo
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (puo *PaymentUpdateOne) SetNillableAmount(i *int) *PaymentUpdateOne {
	if i != nil {
		puo.SetAmount(*i)
	}
	return puo
}

// AddAmount adds i to the "amount" field.
func (puo *PaymentUpdateOne) AddAmount(i int) *PaymentUpdateOne {
	puo.mutation.AddAmount(i)
	return puo
}

// SetCurrency sets the "currency" field.
func (puo *PaymentUpdateOne) SetCurrency(s string) *PaymentUpdateOne {
	puo.mutation.SetCurrency(s)
	return puo
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (puo *PaymentUpdateOne) SetNillableCurrency(s *string) *PaymentUpdateOne {
	if s != nil {
		puo.SetCurrency(*s)
	}
	return puo
}

// SetDescription sets the "description" field.
func (puo *PaymentUpdateOne) SetDescription(s string) *PaymentUpdateOne {
	puo.mutation.SetDescription(s)
	return puo
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (puo *PaymentUpdateOne) SetNillableDescription(s *string) *PaymentUpdateOne {
	if s != nil {
		puo.SetDescription(*s)
	}
	return puo
}

// SetStatus sets the "status" field.
func (puo *PaymentUpdateOne) SetStatus(pa payment.Status) *PaymentUpdateOne {
	puo.mutation.SetStatus(pa)
	return puo
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (puo *PaymentUpdateOne) SetNillableStatus(pa *payment.Status) *PaymentUpdateOne {
	if pa != nil {
		puo.SetStatus(*pa)
	}
	return puo
}

// SetPaidAt sets the "paid_at" field.
func (puo *PaymentUpdateOne) SetPaidAt(t time.Time) *PaymentUpdateOne {
	puo.mutation.SetPaidAt(t)
	return puo
}

// SetNillablePaidAt sets the "paid_at" field if the given value is not nil.
func (puo *PaymentUpdateOne) SetNillablePaidAt(t *time.Time) *PaymentUpdateOne {
	if t != nil {
		puo.SetPaidAt(*t)
	}
	return puo
}

// ClearPaidAt clears the value of the "paid_at" field.
func (puo *PaymentUpdateOne) ClearPaidAt() *PaymentUpdateOne {
	puo.mutation.ClearPaidAt()
	return puo
}

// SetPaymentType sets the "payment_type" field.
func (puo *PaymentUpdateOne) SetPaymentType(pt payment.PaymentType) *PaymentUpdateOne {
	puo.mutation.SetPaymentType(pt)
	return puo
}

// SetNillablePaymentType sets the "payment_type" field if the given value is not nil.
func (puo *PaymentUpdateOne) SetNillablePaymentType(pt *payment.PaymentType) *PaymentUpdateOne {
	if pt != nil {
		puo.SetPaymentType(*pt)
	}
	return puo
}

// SetWechatPlatform sets the "wechat_platform" field.
func (puo *PaymentUpdateOne) SetWechatPlatform(s string) *PaymentUpdateOne {
	puo.mutation.SetWechatPlatform(s)
	return puo
}

// SetNillableWechatPlatform sets the "wechat_platform" field if the given value is not nil.
func (puo *PaymentUpdateOne) SetNillableWechatPlatform(s *string) *PaymentUpdateOne {
	if s != nil {
		puo.SetWechatPlatform(*s)
	}
	return puo
}

// ClearWechatPlatform clears the value of the "wechat_platform" field.
func (puo *PaymentUpdateOne) ClearWechatPlatform() *PaymentUpdateOne {
	puo.mutation.ClearWechatPlatform()
	return puo
}

// SetWechatOpenID sets the "wechat_open_id" field.
func (puo *PaymentUpdateOne) SetWechatOpenID(s string) *PaymentUpdateOne {
	puo.mutation.SetWechatOpenID(s)
	return puo
}

// SetNillableWechatOpenID sets the "wechat_open_id" field if the given value is not nil.
func (puo *PaymentUpdateOne) SetNillableWechatOpenID(s *string) *PaymentUpdateOne {
	if s != nil {
		puo.SetWechatOpenID(*s)
	}
	return puo
}

// ClearWechatOpenID clears the value of the "wechat_open_id" field.
func (puo *PaymentUpdateOne) ClearWechatOpenID() *PaymentUpdateOne {
	puo.mutation.ClearWechatOpenID()
	return puo
}

// SetWechatTransactionID sets the "wechat_transaction_id" field.
func (puo *PaymentUpdateOne) SetWechatTransactionID(s string) *PaymentUpdateOne {
	puo.mutation.SetWechatTransactionID(s)
	return puo
}

// SetNillableWechatTransactionID sets the "wechat_transaction_id" field if the given value is not nil.
func (puo *PaymentUpdateOne) SetNillableWechatTransactionID(s *string) *PaymentUpdateOne {
	if s != nil {
		puo.SetWechatTransactionID(*s)
	}
	return puo
}

// ClearWechatTransactionID clears the value of the "wechat_transaction_id" field.
func (puo *PaymentUpdateOne) ClearWechatTransactionID() *PaymentUpdateOne {
	puo.mutation.ClearWechatTransactionID()
	return puo
}

// SetStripeSubscriptionID sets the "stripe_subscription_id" field.
func (puo *PaymentUpdateOne) SetStripeSubscriptionID(s string) *PaymentUpdateOne {
	puo.mutation.SetStripeSubscriptionID(s)
	return puo
}

// SetNillableStripeSubscriptionID sets the "stripe_subscription_id" field if the given value is not nil.
func (puo *PaymentUpdateOne) SetNillableStripeSubscriptionID(s *string) *PaymentUpdateOne {
	if s != nil {
		puo.SetStripeSubscriptionID(*s)
	}
	return puo
}

// ClearStripeSubscriptionID clears the value of the "stripe_subscription_id" field.
func (puo *PaymentUpdateOne) ClearStripeSubscriptionID() *PaymentUpdateOne {
	puo.mutation.ClearStripeSubscriptionID()
	return puo
}

// SetStripeSubscriptionStatus sets the "stripe_subscription_status" field.
func (puo *PaymentUpdateOne) SetStripeSubscriptionStatus(s string) *PaymentUpdateOne {
	puo.mutation.SetStripeSubscriptionStatus(s)
	return puo
}

// SetNillableStripeSubscriptionStatus sets the "stripe_subscription_status" field if the given value is not nil.
func (puo *PaymentUpdateOne) SetNillableStripeSubscriptionStatus(s *string) *PaymentUpdateOne {
	if s != nil {
		puo.SetStripeSubscriptionStatus(*s)
	}
	return puo
}

// ClearStripeSubscriptionStatus clears the value of the "stripe_subscription_status" field.
func (puo *PaymentUpdateOne) ClearStripeSubscriptionStatus() *PaymentUpdateOne {
	puo.mutation.ClearStripeSubscriptionStatus()
	return puo
}

// SetStripeInterval sets the "stripe_interval" field.
func (puo *PaymentUpdateOne) SetStripeInterval(s string) *PaymentUpdateOne {
	puo.mutation.SetStripeInterval(s)
	return puo
}

// SetNillableStripeInterval sets the "stripe_interval" field if the given value is not nil.
func (puo *PaymentUpdateOne) SetNillableStripeInterval(s *string) *PaymentUpdateOne {
	if s != nil {
		puo.SetStripeInterval(*s)
	}
	return puo
}

// ClearStripeInterval clears the value of the "stripe_interval" field.
func (puo *PaymentUpdateOne) ClearStripeInterval() *PaymentUpdateOne {
	puo.mutation.ClearStripeInterval()
	return puo
}

// SetStripeCurrentPeriodStart sets the "stripe_current_period_start" field.
func (puo *PaymentUpdateOne) SetStripeCurrentPeriodStart(t time.Time) *PaymentUpdateOne {
	puo.mutation.SetStripeCurrentPeriodStart(t)
	return puo
}

// SetNillableStripeCurrentPeriodStart sets the "stripe_current_period_start" field if the given value is not nil.
func (puo *PaymentUpdateOne) SetNillableStripeCurrentPeriodStart(t *time.Time) *PaymentUpdateOne {
	if t != nil {
		puo.SetStripeCurrentPeriodStart(*t)
	}
	return puo
}

// ClearStripeCurrentPeriodStart clears the value of the "stripe_current_period_start" field.
func (puo *PaymentUpdateOne) ClearStripeCurrentPeriodStart() *PaymentUpdateOne {
	puo.mutation.ClearStripeCurrentPeriodStart()
	return puo
}

// SetStripeCurrentPeriodEnd sets the "stripe_current_period_end" field.
func (puo *PaymentUpdateOne) SetStripeCurrentPeriodEnd(t time.Time) *PaymentUpdateOne {
	puo.mutation.SetStripeCurrentPeriodEnd(t)
	return puo
}

// SetNillableStripeCurrentPeriodEnd sets the "stripe_current_period_end" field if the given value is not nil.
func (puo *PaymentUpdateOne) SetNillableStripeCurrentPeriodEnd(t *time.Time) *PaymentUpdateOne {
	if t != nil {
		puo.SetStripeCurrentPeriodEnd(*t)
	}
	return puo
}

// ClearStripeCurrentPeriodEnd clears the value of the "stripe_current_period_end" field.
func (puo *PaymentUpdateOne) ClearStripeCurrentPeriodEnd() *PaymentUpdateOne {
	puo.mutation.ClearStripeCurrentPeriodEnd()
	return puo
}

// SetStripeCustomerID sets the "stripe_customer_id" field.
func (puo *PaymentUpdateOne) SetStripeCustomerID(s string) *PaymentUpdateOne {
	puo.mutation.SetStripeCustomerID(s)
	return puo
}

// SetNillableStripeCustomerID sets the "stripe_customer_id" field if the given value is not nil.
func (puo *PaymentUpdateOne) SetNillableStripeCustomerID(s *string) *PaymentUpdateOne {
	if s != nil {
		puo.SetStripeCustomerID(*s)
	}
	return puo
}

// ClearStripeCustomerID clears the value of the "stripe_customer_id" field.
func (puo *PaymentUpdateOne) ClearStripeCustomerID() *PaymentUpdateOne {
	puo.mutation.ClearStripeCustomerID()
	return puo
}

// SetStripeCustomerEmail sets the "stripe_customer_email" field.
func (puo *PaymentUpdateOne) SetStripeCustomerEmail(s string) *PaymentUpdateOne {
	puo.mutation.SetStripeCustomerEmail(s)
	return puo
}

// SetNillableStripeCustomerEmail sets the "stripe_customer_email" field if the given value is not nil.
func (puo *PaymentUpdateOne) SetNillableStripeCustomerEmail(s *string) *PaymentUpdateOne {
	if s != nil {
		puo.SetStripeCustomerEmail(*s)
	}
	return puo
}

// ClearStripeCustomerEmail clears the value of the "stripe_customer_email" field.
func (puo *PaymentUpdateOne) ClearStripeCustomerEmail() *PaymentUpdateOne {
	puo.mutation.ClearStripeCustomerEmail()
	return puo
}

// SetStripeCheckoutSessionID sets the "stripe_checkout_session_id" field.
func (puo *PaymentUpdateOne) SetStripeCheckoutSessionID(s string) *PaymentUpdateOne {
	puo.mutation.SetStripeCheckoutSessionID(s)
	return puo
}

// SetNillableStripeCheckoutSessionID sets the "stripe_checkout_session_id" field if the given value is not nil.
func (puo *PaymentUpdateOne) SetNillableStripeCheckoutSessionID(s *string) *PaymentUpdateOne {
	if s != nil {
		puo.SetStripeCheckoutSessionID(*s)
	}
	return puo
}

// ClearStripeCheckoutSessionID clears the value of the "stripe_checkout_session_id" field.
func (puo *PaymentUpdateOne) ClearStripeCheckoutSessionID() *PaymentUpdateOne {
	puo.mutation.ClearStripeCheckoutSessionID()
	return puo
}

// SetStripeInvoiceID sets the "stripe_invoice_id" field.
func (puo *PaymentUpdateOne) SetStripeInvoiceID(s string) *PaymentUpdateOne {
	puo.mutation.SetStripeInvoiceID(s)
	return puo
}

// SetNillableStripeInvoiceID sets the "stripe_invoice_id" field if the given value is not nil.
func (puo *PaymentUpdateOne) SetNillableStripeInvoiceID(s *string) *PaymentUpdateOne {
	if s != nil {
		puo.SetStripeInvoiceID(*s)
	}
	return puo
}

// ClearStripeInvoiceID clears the value of the "stripe_invoice_id" field.
func (puo *PaymentUpdateOne) ClearStripeInvoiceID() *PaymentUpdateOne {
	puo.mutation.ClearStripeInvoiceID()
	return puo
}

// SetUser sets the "user" edge to the User entity.
func (puo *PaymentUpdateOne) SetUser(u *User) *PaymentUpdateOne {
	return puo.SetUserID(u.ID)
}

// Mutation returns the PaymentMutation object of the builder.
func (puo *PaymentUpdateOne) Mutation() *PaymentMutation {
	return puo.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (puo *PaymentUpdateOne) ClearUser() *PaymentUpdateOne {
	puo.mutation.ClearUser()
	return puo
}

// Where appends a list predicates to the PaymentUpdate builder.
func (puo *PaymentUpdateOne) Where(ps ...predicate.Payment) *PaymentUpdateOne {
	puo.mutation.Where(ps...)
	return puo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (puo *PaymentUpdateOne) Select(field string, fields ...string) *PaymentUpdateOne {
	puo.fields = append([]string{field}, fields...)
	return puo
}

// Save executes the query and returns the updated Payment entity.
func (puo *PaymentUpdateOne) Save(ctx context.Context) (*Payment, error) {
	puo.defaults()
	return withHooks(ctx, puo.sqlSave, puo.mutation, puo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (puo *PaymentUpdateOne) SaveX(ctx context.Context) *Payment {
	node, err := puo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (puo *PaymentUpdateOne) Exec(ctx context.Context) error {
	_, err := puo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (puo *PaymentUpdateOne) ExecX(ctx context.Context) {
	if err := puo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (puo *PaymentUpdateOne) defaults() {
	if _, ok := puo.mutation.UpdatedAt(); !ok {
		v := payment.UpdateDefaultUpdatedAt()
		puo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (puo *PaymentUpdateOne) check() error {
	if v, ok := puo.mutation.OutTradeNo(); ok {
		if err := payment.OutTradeNoValidator(v); err != nil {
			return &ValidationError{Name: "out_trade_no", err: fmt.Errorf(`ent: validator failed for field "Payment.out_trade_no": %w`, err)}
		}
	}
	if v, ok := puo.mutation.UserID(); ok {
		if err := payment.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "Payment.user_id": %w`, err)}
		}
	}
	if v, ok := puo.mutation.Channel(); ok {
		if err := payment.ChannelValidator(v); err != nil {
			return &ValidationError{Name: "channel", err: fmt.Errorf(`ent: validator failed for field "Payment.channel": %w`, err)}
		}
	}
	if v, ok := puo.mutation.Service(); ok {
		if err := payment.ServiceValidator(v); err != nil {
			return &ValidationError{Name: "service", err: fmt.Errorf(`ent: validator failed for field "Payment.service": %w`, err)}
		}
	}
	if v, ok := puo.mutation.Amount(); ok {
		if err := payment.AmountValidator(v); err != nil {
			return &ValidationError{Name: "amount", err: fmt.Errorf(`ent: validator failed for field "Payment.amount": %w`, err)}
		}
	}
	if v, ok := puo.mutation.Currency(); ok {
		if err := payment.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "Payment.currency": %w`, err)}
		}
	}
	if v, ok := puo.mutation.Description(); ok {
		if err := payment.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "Payment.description": %w`, err)}
		}
	}
	if v, ok := puo.mutation.Status(); ok {
		if err := payment.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Payment.status": %w`, err)}
		}
	}
	if v, ok := puo.mutation.PaymentType(); ok {
		if err := payment.PaymentTypeValidator(v); err != nil {
			return &ValidationError{Name: "payment_type", err: fmt.Errorf(`ent: validator failed for field "Payment.payment_type": %w`, err)}
		}
	}
	if puo.mutation.UserCleared() && len(puo.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Payment.user"`)
	}
	return nil
}

func (puo *PaymentUpdateOne) sqlSave(ctx context.Context) (_node *Payment, err error) {
	if err := puo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(payment.Table, payment.Columns, sqlgraph.NewFieldSpec(payment.FieldID, field.TypeInt))
	id, ok := puo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Payment.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := puo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, payment.FieldID)
		for _, f := range fields {
			if !payment.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != payment.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := puo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := puo.mutation.UpdatedAt(); ok {
		_spec.SetField(payment.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := puo.mutation.OutTradeNo(); ok {
		_spec.SetField(payment.FieldOutTradeNo, field.TypeString, value)
	}
	if value, ok := puo.mutation.Channel(); ok {
		_spec.SetField(payment.FieldChannel, field.TypeEnum, value)
	}
	if value, ok := puo.mutation.Service(); ok {
		_spec.SetField(payment.FieldService, field.TypeString, value)
	}
	if value, ok := puo.mutation.Amount(); ok {
		_spec.SetField(payment.FieldAmount, field.TypeInt, value)
	}
	if value, ok := puo.mutation.AddedAmount(); ok {
		_spec.AddField(payment.FieldAmount, field.TypeInt, value)
	}
	if value, ok := puo.mutation.Currency(); ok {
		_spec.SetField(payment.FieldCurrency, field.TypeString, value)
	}
	if value, ok := puo.mutation.Description(); ok {
		_spec.SetField(payment.FieldDescription, field.TypeString, value)
	}
	if value, ok := puo.mutation.Status(); ok {
		_spec.SetField(payment.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := puo.mutation.PaidAt(); ok {
		_spec.SetField(payment.FieldPaidAt, field.TypeTime, value)
	}
	if puo.mutation.PaidAtCleared() {
		_spec.ClearField(payment.FieldPaidAt, field.TypeTime)
	}
	if value, ok := puo.mutation.PaymentType(); ok {
		_spec.SetField(payment.FieldPaymentType, field.TypeEnum, value)
	}
	if value, ok := puo.mutation.WechatPlatform(); ok {
		_spec.SetField(payment.FieldWechatPlatform, field.TypeString, value)
	}
	if puo.mutation.WechatPlatformCleared() {
		_spec.ClearField(payment.FieldWechatPlatform, field.TypeString)
	}
	if value, ok := puo.mutation.WechatOpenID(); ok {
		_spec.SetField(payment.FieldWechatOpenID, field.TypeString, value)
	}
	if puo.mutation.WechatOpenIDCleared() {
		_spec.ClearField(payment.FieldWechatOpenID, field.TypeString)
	}
	if value, ok := puo.mutation.WechatTransactionID(); ok {
		_spec.SetField(payment.FieldWechatTransactionID, field.TypeString, value)
	}
	if puo.mutation.WechatTransactionIDCleared() {
		_spec.ClearField(payment.FieldWechatTransactionID, field.TypeString)
	}
	if value, ok := puo.mutation.StripeSubscriptionID(); ok {
		_spec.SetField(payment.FieldStripeSubscriptionID, field.TypeString, value)
	}
	if puo.mutation.StripeSubscriptionIDCleared() {
		_spec.ClearField(payment.FieldStripeSubscriptionID, field.TypeString)
	}
	if value, ok := puo.mutation.StripeSubscriptionStatus(); ok {
		_spec.SetField(payment.FieldStripeSubscriptionStatus, field.TypeString, value)
	}
	if puo.mutation.StripeSubscriptionStatusCleared() {
		_spec.ClearField(payment.FieldStripeSubscriptionStatus, field.TypeString)
	}
	if value, ok := puo.mutation.StripeInterval(); ok {
		_spec.SetField(payment.FieldStripeInterval, field.TypeString, value)
	}
	if puo.mutation.StripeIntervalCleared() {
		_spec.ClearField(payment.FieldStripeInterval, field.TypeString)
	}
	if value, ok := puo.mutation.StripeCurrentPeriodStart(); ok {
		_spec.SetField(payment.FieldStripeCurrentPeriodStart, field.TypeTime, value)
	}
	if puo.mutation.StripeCurrentPeriodStartCleared() {
		_spec.ClearField(payment.FieldStripeCurrentPeriodStart, field.TypeTime)
	}
	if value, ok := puo.mutation.StripeCurrentPeriodEnd(); ok {
		_spec.SetField(payment.FieldStripeCurrentPeriodEnd, field.TypeTime, value)
	}
	if puo.mutation.StripeCurrentPeriodEndCleared() {
		_spec.ClearField(payment.FieldStripeCurrentPeriodEnd, field.TypeTime)
	}
	if value, ok := puo.mutation.StripeCustomerID(); ok {
		_spec.SetField(payment.FieldStripeCustomerID, field.TypeString, value)
	}
	if puo.mutation.StripeCustomerIDCleared() {
		_spec.ClearField(payment.FieldStripeCustomerID, field.TypeString)
	}
	if value, ok := puo.mutation.StripeCustomerEmail(); ok {
		_spec.SetField(payment.FieldStripeCustomerEmail, field.TypeString, value)
	}
	if puo.mutation.StripeCustomerEmailCleared() {
		_spec.ClearField(payment.FieldStripeCustomerEmail, field.TypeString)
	}
	if value, ok := puo.mutation.StripeCheckoutSessionID(); ok {
		_spec.SetField(payment.FieldStripeCheckoutSessionID, field.TypeString, value)
	}
	if puo.mutation.StripeCheckoutSessionIDCleared() {
		_spec.ClearField(payment.FieldStripeCheckoutSessionID, field.TypeString)
	}
	if value, ok := puo.mutation.StripeInvoiceID(); ok {
		_spec.SetField(payment.FieldStripeInvoiceID, field.TypeString, value)
	}
	if puo.mutation.StripeInvoiceIDCleared() {
		_spec.ClearField(payment.FieldStripeInvoiceID, field.TypeString)
	}
	if puo.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   payment.UserTable,
			Columns: []string{payment.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := puo.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   payment.UserTable,
			Columns: []string{payment.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Payment{config: puo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, puo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{payment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	puo.mutation.done = true
	return _node, nil
}
