// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"kiwi-user/internal/infrastructure/repository/ent/payment"
	"kiwi-user/internal/infrastructure/repository/ent/user"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PaymentCreate is the builder for creating a Payment entity.
type PaymentCreate struct {
	config
	mutation *PaymentMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (pc *PaymentCreate) SetCreatedAt(t time.Time) *PaymentCreate {
	pc.mutation.SetCreatedAt(t)
	return pc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (pc *PaymentCreate) SetNillableCreatedAt(t *time.Time) *PaymentCreate {
	if t != nil {
		pc.SetCreatedAt(*t)
	}
	return pc
}

// SetUpdatedAt sets the "updated_at" field.
func (pc *PaymentCreate) SetUpdatedAt(t time.Time) *PaymentCreate {
	pc.mutation.SetUpdatedAt(t)
	return pc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (pc *PaymentCreate) SetNillableUpdatedAt(t *time.Time) *PaymentCreate {
	if t != nil {
		pc.SetUpdatedAt(*t)
	}
	return pc
}

// SetOutTradeNo sets the "out_trade_no" field.
func (pc *PaymentCreate) SetOutTradeNo(s string) *PaymentCreate {
	pc.mutation.SetOutTradeNo(s)
	return pc
}

// SetUserID sets the "user_id" field.
func (pc *PaymentCreate) SetUserID(s string) *PaymentCreate {
	pc.mutation.SetUserID(s)
	return pc
}

// SetChannel sets the "channel" field.
func (pc *PaymentCreate) SetChannel(pa payment.Channel) *PaymentCreate {
	pc.mutation.SetChannel(pa)
	return pc
}

// SetService sets the "service" field.
func (pc *PaymentCreate) SetService(s string) *PaymentCreate {
	pc.mutation.SetService(s)
	return pc
}

// SetAmount sets the "amount" field.
func (pc *PaymentCreate) SetAmount(i int) *PaymentCreate {
	pc.mutation.SetAmount(i)
	return pc
}

// SetCurrency sets the "currency" field.
func (pc *PaymentCreate) SetCurrency(s string) *PaymentCreate {
	pc.mutation.SetCurrency(s)
	return pc
}

// SetDescription sets the "description" field.
func (pc *PaymentCreate) SetDescription(s string) *PaymentCreate {
	pc.mutation.SetDescription(s)
	return pc
}

// SetStatus sets the "status" field.
func (pc *PaymentCreate) SetStatus(pa payment.Status) *PaymentCreate {
	pc.mutation.SetStatus(pa)
	return pc
}

// SetPaidAt sets the "paid_at" field.
func (pc *PaymentCreate) SetPaidAt(t time.Time) *PaymentCreate {
	pc.mutation.SetPaidAt(t)
	return pc
}

// SetNillablePaidAt sets the "paid_at" field if the given value is not nil.
func (pc *PaymentCreate) SetNillablePaidAt(t *time.Time) *PaymentCreate {
	if t != nil {
		pc.SetPaidAt(*t)
	}
	return pc
}

// SetPaymentType sets the "payment_type" field.
func (pc *PaymentCreate) SetPaymentType(pt payment.PaymentType) *PaymentCreate {
	pc.mutation.SetPaymentType(pt)
	return pc
}

// SetNillablePaymentType sets the "payment_type" field if the given value is not nil.
func (pc *PaymentCreate) SetNillablePaymentType(pt *payment.PaymentType) *PaymentCreate {
	if pt != nil {
		pc.SetPaymentType(*pt)
	}
	return pc
}

// SetWechatPlatform sets the "wechat_platform" field.
func (pc *PaymentCreate) SetWechatPlatform(s string) *PaymentCreate {
	pc.mutation.SetWechatPlatform(s)
	return pc
}

// SetNillableWechatPlatform sets the "wechat_platform" field if the given value is not nil.
func (pc *PaymentCreate) SetNillableWechatPlatform(s *string) *PaymentCreate {
	if s != nil {
		pc.SetWechatPlatform(*s)
	}
	return pc
}

// SetWechatOpenID sets the "wechat_open_id" field.
func (pc *PaymentCreate) SetWechatOpenID(s string) *PaymentCreate {
	pc.mutation.SetWechatOpenID(s)
	return pc
}

// SetNillableWechatOpenID sets the "wechat_open_id" field if the given value is not nil.
func (pc *PaymentCreate) SetNillableWechatOpenID(s *string) *PaymentCreate {
	if s != nil {
		pc.SetWechatOpenID(*s)
	}
	return pc
}

// SetWechatTransactionID sets the "wechat_transaction_id" field.
func (pc *PaymentCreate) SetWechatTransactionID(s string) *PaymentCreate {
	pc.mutation.SetWechatTransactionID(s)
	return pc
}

// SetNillableWechatTransactionID sets the "wechat_transaction_id" field if the given value is not nil.
func (pc *PaymentCreate) SetNillableWechatTransactionID(s *string) *PaymentCreate {
	if s != nil {
		pc.SetWechatTransactionID(*s)
	}
	return pc
}

// SetStripeSubscriptionID sets the "stripe_subscription_id" field.
func (pc *PaymentCreate) SetStripeSubscriptionID(s string) *PaymentCreate {
	pc.mutation.SetStripeSubscriptionID(s)
	return pc
}

// SetNillableStripeSubscriptionID sets the "stripe_subscription_id" field if the given value is not nil.
func (pc *PaymentCreate) SetNillableStripeSubscriptionID(s *string) *PaymentCreate {
	if s != nil {
		pc.SetStripeSubscriptionID(*s)
	}
	return pc
}

// SetStripeSubscriptionStatus sets the "stripe_subscription_status" field.
func (pc *PaymentCreate) SetStripeSubscriptionStatus(s string) *PaymentCreate {
	pc.mutation.SetStripeSubscriptionStatus(s)
	return pc
}

// SetNillableStripeSubscriptionStatus sets the "stripe_subscription_status" field if the given value is not nil.
func (pc *PaymentCreate) SetNillableStripeSubscriptionStatus(s *string) *PaymentCreate {
	if s != nil {
		pc.SetStripeSubscriptionStatus(*s)
	}
	return pc
}

// SetStripeInterval sets the "stripe_interval" field.
func (pc *PaymentCreate) SetStripeInterval(s string) *PaymentCreate {
	pc.mutation.SetStripeInterval(s)
	return pc
}

// SetNillableStripeInterval sets the "stripe_interval" field if the given value is not nil.
func (pc *PaymentCreate) SetNillableStripeInterval(s *string) *PaymentCreate {
	if s != nil {
		pc.SetStripeInterval(*s)
	}
	return pc
}

// SetStripeCancelAtPeriodEnd sets the "stripe_cancel_at_period_end" field.
func (pc *PaymentCreate) SetStripeCancelAtPeriodEnd(b bool) *PaymentCreate {
	pc.mutation.SetStripeCancelAtPeriodEnd(b)
	return pc
}

// SetNillableStripeCancelAtPeriodEnd sets the "stripe_cancel_at_period_end" field if the given value is not nil.
func (pc *PaymentCreate) SetNillableStripeCancelAtPeriodEnd(b *bool) *PaymentCreate {
	if b != nil {
		pc.SetStripeCancelAtPeriodEnd(*b)
	}
	return pc
}

// SetStripeCurrentPeriodStart sets the "stripe_current_period_start" field.
func (pc *PaymentCreate) SetStripeCurrentPeriodStart(t time.Time) *PaymentCreate {
	pc.mutation.SetStripeCurrentPeriodStart(t)
	return pc
}

// SetNillableStripeCurrentPeriodStart sets the "stripe_current_period_start" field if the given value is not nil.
func (pc *PaymentCreate) SetNillableStripeCurrentPeriodStart(t *time.Time) *PaymentCreate {
	if t != nil {
		pc.SetStripeCurrentPeriodStart(*t)
	}
	return pc
}

// SetStripeCurrentPeriodEnd sets the "stripe_current_period_end" field.
func (pc *PaymentCreate) SetStripeCurrentPeriodEnd(t time.Time) *PaymentCreate {
	pc.mutation.SetStripeCurrentPeriodEnd(t)
	return pc
}

// SetNillableStripeCurrentPeriodEnd sets the "stripe_current_period_end" field if the given value is not nil.
func (pc *PaymentCreate) SetNillableStripeCurrentPeriodEnd(t *time.Time) *PaymentCreate {
	if t != nil {
		pc.SetStripeCurrentPeriodEnd(*t)
	}
	return pc
}

// SetStripeCustomerID sets the "stripe_customer_id" field.
func (pc *PaymentCreate) SetStripeCustomerID(s string) *PaymentCreate {
	pc.mutation.SetStripeCustomerID(s)
	return pc
}

// SetNillableStripeCustomerID sets the "stripe_customer_id" field if the given value is not nil.
func (pc *PaymentCreate) SetNillableStripeCustomerID(s *string) *PaymentCreate {
	if s != nil {
		pc.SetStripeCustomerID(*s)
	}
	return pc
}

// SetStripeCustomerEmail sets the "stripe_customer_email" field.
func (pc *PaymentCreate) SetStripeCustomerEmail(s string) *PaymentCreate {
	pc.mutation.SetStripeCustomerEmail(s)
	return pc
}

// SetNillableStripeCustomerEmail sets the "stripe_customer_email" field if the given value is not nil.
func (pc *PaymentCreate) SetNillableStripeCustomerEmail(s *string) *PaymentCreate {
	if s != nil {
		pc.SetStripeCustomerEmail(*s)
	}
	return pc
}

// SetStripeCheckoutSessionID sets the "stripe_checkout_session_id" field.
func (pc *PaymentCreate) SetStripeCheckoutSessionID(s string) *PaymentCreate {
	pc.mutation.SetStripeCheckoutSessionID(s)
	return pc
}

// SetNillableStripeCheckoutSessionID sets the "stripe_checkout_session_id" field if the given value is not nil.
func (pc *PaymentCreate) SetNillableStripeCheckoutSessionID(s *string) *PaymentCreate {
	if s != nil {
		pc.SetStripeCheckoutSessionID(*s)
	}
	return pc
}

// SetStripeInvoiceID sets the "stripe_invoice_id" field.
func (pc *PaymentCreate) SetStripeInvoiceID(s string) *PaymentCreate {
	pc.mutation.SetStripeInvoiceID(s)
	return pc
}

// SetNillableStripeInvoiceID sets the "stripe_invoice_id" field if the given value is not nil.
func (pc *PaymentCreate) SetNillableStripeInvoiceID(s *string) *PaymentCreate {
	if s != nil {
		pc.SetStripeInvoiceID(*s)
	}
	return pc
}

// SetUser sets the "user" edge to the User entity.
func (pc *PaymentCreate) SetUser(u *User) *PaymentCreate {
	return pc.SetUserID(u.ID)
}

// Mutation returns the PaymentMutation object of the builder.
func (pc *PaymentCreate) Mutation() *PaymentMutation {
	return pc.mutation
}

// Save creates the Payment in the database.
func (pc *PaymentCreate) Save(ctx context.Context) (*Payment, error) {
	pc.defaults()
	return withHooks(ctx, pc.sqlSave, pc.mutation, pc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (pc *PaymentCreate) SaveX(ctx context.Context) *Payment {
	v, err := pc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pc *PaymentCreate) Exec(ctx context.Context) error {
	_, err := pc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pc *PaymentCreate) ExecX(ctx context.Context) {
	if err := pc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (pc *PaymentCreate) defaults() {
	if _, ok := pc.mutation.CreatedAt(); !ok {
		v := payment.DefaultCreatedAt()
		pc.mutation.SetCreatedAt(v)
	}
	if _, ok := pc.mutation.UpdatedAt(); !ok {
		v := payment.DefaultUpdatedAt()
		pc.mutation.SetUpdatedAt(v)
	}
	if _, ok := pc.mutation.PaymentType(); !ok {
		v := payment.DefaultPaymentType
		pc.mutation.SetPaymentType(v)
	}
	if _, ok := pc.mutation.StripeCancelAtPeriodEnd(); !ok {
		v := payment.DefaultStripeCancelAtPeriodEnd
		pc.mutation.SetStripeCancelAtPeriodEnd(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (pc *PaymentCreate) check() error {
	if _, ok := pc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Payment.created_at"`)}
	}
	if _, ok := pc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Payment.updated_at"`)}
	}
	if _, ok := pc.mutation.OutTradeNo(); !ok {
		return &ValidationError{Name: "out_trade_no", err: errors.New(`ent: missing required field "Payment.out_trade_no"`)}
	}
	if v, ok := pc.mutation.OutTradeNo(); ok {
		if err := payment.OutTradeNoValidator(v); err != nil {
			return &ValidationError{Name: "out_trade_no", err: fmt.Errorf(`ent: validator failed for field "Payment.out_trade_no": %w`, err)}
		}
	}
	if _, ok := pc.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "Payment.user_id"`)}
	}
	if v, ok := pc.mutation.UserID(); ok {
		if err := payment.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "Payment.user_id": %w`, err)}
		}
	}
	if _, ok := pc.mutation.Channel(); !ok {
		return &ValidationError{Name: "channel", err: errors.New(`ent: missing required field "Payment.channel"`)}
	}
	if v, ok := pc.mutation.Channel(); ok {
		if err := payment.ChannelValidator(v); err != nil {
			return &ValidationError{Name: "channel", err: fmt.Errorf(`ent: validator failed for field "Payment.channel": %w`, err)}
		}
	}
	if _, ok := pc.mutation.Service(); !ok {
		return &ValidationError{Name: "service", err: errors.New(`ent: missing required field "Payment.service"`)}
	}
	if v, ok := pc.mutation.Service(); ok {
		if err := payment.ServiceValidator(v); err != nil {
			return &ValidationError{Name: "service", err: fmt.Errorf(`ent: validator failed for field "Payment.service": %w`, err)}
		}
	}
	if _, ok := pc.mutation.Amount(); !ok {
		return &ValidationError{Name: "amount", err: errors.New(`ent: missing required field "Payment.amount"`)}
	}
	if v, ok := pc.mutation.Amount(); ok {
		if err := payment.AmountValidator(v); err != nil {
			return &ValidationError{Name: "amount", err: fmt.Errorf(`ent: validator failed for field "Payment.amount": %w`, err)}
		}
	}
	if _, ok := pc.mutation.Currency(); !ok {
		return &ValidationError{Name: "currency", err: errors.New(`ent: missing required field "Payment.currency"`)}
	}
	if v, ok := pc.mutation.Currency(); ok {
		if err := payment.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "Payment.currency": %w`, err)}
		}
	}
	if _, ok := pc.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "Payment.description"`)}
	}
	if v, ok := pc.mutation.Description(); ok {
		if err := payment.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "Payment.description": %w`, err)}
		}
	}
	if _, ok := pc.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Payment.status"`)}
	}
	if v, ok := pc.mutation.Status(); ok {
		if err := payment.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Payment.status": %w`, err)}
		}
	}
	if _, ok := pc.mutation.PaymentType(); !ok {
		return &ValidationError{Name: "payment_type", err: errors.New(`ent: missing required field "Payment.payment_type"`)}
	}
	if v, ok := pc.mutation.PaymentType(); ok {
		if err := payment.PaymentTypeValidator(v); err != nil {
			return &ValidationError{Name: "payment_type", err: fmt.Errorf(`ent: validator failed for field "Payment.payment_type": %w`, err)}
		}
	}
	if _, ok := pc.mutation.StripeCancelAtPeriodEnd(); !ok {
		return &ValidationError{Name: "stripe_cancel_at_period_end", err: errors.New(`ent: missing required field "Payment.stripe_cancel_at_period_end"`)}
	}
	if len(pc.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "Payment.user"`)}
	}
	return nil
}

func (pc *PaymentCreate) sqlSave(ctx context.Context) (*Payment, error) {
	if err := pc.check(); err != nil {
		return nil, err
	}
	_node, _spec := pc.createSpec()
	if err := sqlgraph.CreateNode(ctx, pc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	pc.mutation.id = &_node.ID
	pc.mutation.done = true
	return _node, nil
}

func (pc *PaymentCreate) createSpec() (*Payment, *sqlgraph.CreateSpec) {
	var (
		_node = &Payment{config: pc.config}
		_spec = sqlgraph.NewCreateSpec(payment.Table, sqlgraph.NewFieldSpec(payment.FieldID, field.TypeInt))
	)
	if value, ok := pc.mutation.CreatedAt(); ok {
		_spec.SetField(payment.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := pc.mutation.UpdatedAt(); ok {
		_spec.SetField(payment.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := pc.mutation.OutTradeNo(); ok {
		_spec.SetField(payment.FieldOutTradeNo, field.TypeString, value)
		_node.OutTradeNo = value
	}
	if value, ok := pc.mutation.Channel(); ok {
		_spec.SetField(payment.FieldChannel, field.TypeEnum, value)
		_node.Channel = value
	}
	if value, ok := pc.mutation.Service(); ok {
		_spec.SetField(payment.FieldService, field.TypeString, value)
		_node.Service = value
	}
	if value, ok := pc.mutation.Amount(); ok {
		_spec.SetField(payment.FieldAmount, field.TypeInt, value)
		_node.Amount = value
	}
	if value, ok := pc.mutation.Currency(); ok {
		_spec.SetField(payment.FieldCurrency, field.TypeString, value)
		_node.Currency = value
	}
	if value, ok := pc.mutation.Description(); ok {
		_spec.SetField(payment.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := pc.mutation.Status(); ok {
		_spec.SetField(payment.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := pc.mutation.PaidAt(); ok {
		_spec.SetField(payment.FieldPaidAt, field.TypeTime, value)
		_node.PaidAt = value
	}
	if value, ok := pc.mutation.PaymentType(); ok {
		_spec.SetField(payment.FieldPaymentType, field.TypeEnum, value)
		_node.PaymentType = value
	}
	if value, ok := pc.mutation.WechatPlatform(); ok {
		_spec.SetField(payment.FieldWechatPlatform, field.TypeString, value)
		_node.WechatPlatform = value
	}
	if value, ok := pc.mutation.WechatOpenID(); ok {
		_spec.SetField(payment.FieldWechatOpenID, field.TypeString, value)
		_node.WechatOpenID = value
	}
	if value, ok := pc.mutation.WechatTransactionID(); ok {
		_spec.SetField(payment.FieldWechatTransactionID, field.TypeString, value)
		_node.WechatTransactionID = value
	}
	if value, ok := pc.mutation.StripeSubscriptionID(); ok {
		_spec.SetField(payment.FieldStripeSubscriptionID, field.TypeString, value)
		_node.StripeSubscriptionID = value
	}
	if value, ok := pc.mutation.StripeSubscriptionStatus(); ok {
		_spec.SetField(payment.FieldStripeSubscriptionStatus, field.TypeString, value)
		_node.StripeSubscriptionStatus = value
	}
	if value, ok := pc.mutation.StripeInterval(); ok {
		_spec.SetField(payment.FieldStripeInterval, field.TypeString, value)
		_node.StripeInterval = value
	}
	if value, ok := pc.mutation.StripeCancelAtPeriodEnd(); ok {
		_spec.SetField(payment.FieldStripeCancelAtPeriodEnd, field.TypeBool, value)
		_node.StripeCancelAtPeriodEnd = value
	}
	if value, ok := pc.mutation.StripeCurrentPeriodStart(); ok {
		_spec.SetField(payment.FieldStripeCurrentPeriodStart, field.TypeTime, value)
		_node.StripeCurrentPeriodStart = value
	}
	if value, ok := pc.mutation.StripeCurrentPeriodEnd(); ok {
		_spec.SetField(payment.FieldStripeCurrentPeriodEnd, field.TypeTime, value)
		_node.StripeCurrentPeriodEnd = value
	}
	if value, ok := pc.mutation.StripeCustomerID(); ok {
		_spec.SetField(payment.FieldStripeCustomerID, field.TypeString, value)
		_node.StripeCustomerID = value
	}
	if value, ok := pc.mutation.StripeCustomerEmail(); ok {
		_spec.SetField(payment.FieldStripeCustomerEmail, field.TypeString, value)
		_node.StripeCustomerEmail = value
	}
	if value, ok := pc.mutation.StripeCheckoutSessionID(); ok {
		_spec.SetField(payment.FieldStripeCheckoutSessionID, field.TypeString, value)
		_node.StripeCheckoutSessionID = value
	}
	if value, ok := pc.mutation.StripeInvoiceID(); ok {
		_spec.SetField(payment.FieldStripeInvoiceID, field.TypeString, value)
		_node.StripeInvoiceID = value
	}
	if nodes := pc.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   payment.UserTable,
			Columns: []string{payment.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// PaymentCreateBulk is the builder for creating many Payment entities in bulk.
type PaymentCreateBulk struct {
	config
	err      error
	builders []*PaymentCreate
}

// Save creates the Payment entities in the database.
func (pcb *PaymentCreateBulk) Save(ctx context.Context) ([]*Payment, error) {
	if pcb.err != nil {
		return nil, pcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(pcb.builders))
	nodes := make([]*Payment, len(pcb.builders))
	mutators := make([]Mutator, len(pcb.builders))
	for i := range pcb.builders {
		func(i int, root context.Context) {
			builder := pcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PaymentMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, pcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, pcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, pcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (pcb *PaymentCreateBulk) SaveX(ctx context.Context) []*Payment {
	v, err := pcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pcb *PaymentCreateBulk) Exec(ctx context.Context) error {
	_, err := pcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pcb *PaymentCreateBulk) ExecX(ctx context.Context) {
	if err := pcb.Exec(ctx); err != nil {
		panic(err)
	}
}
