// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"kiwi-user/internal/infrastructure/repository/ent/qywechatuserid"
	"kiwi-user/internal/infrastructure/repository/ent/user"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// QyWechatUserIDCreate is the builder for creating a QyWechatUserID entity.
type QyWechatUserIDCreate struct {
	config
	mutation *QyWechatUserIDMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (qwuic *QyWechatUserIDCreate) SetCreatedAt(t time.Time) *QyWechatUserIDCreate {
	qwuic.mutation.SetCreatedAt(t)
	return qwuic
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (qwuic *QyWechatUserIDCreate) SetNillableCreatedAt(t *time.Time) *QyWechatUserIDCreate {
	if t != nil {
		qwuic.SetCreatedAt(*t)
	}
	return qwuic
}

// SetUpdatedAt sets the "updated_at" field.
func (qwuic *QyWechatUserIDCreate) SetUpdatedAt(t time.Time) *QyWechatUserIDCreate {
	qwuic.mutation.SetUpdatedAt(t)
	return qwuic
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (qwuic *QyWechatUserIDCreate) SetNillableUpdatedAt(t *time.Time) *QyWechatUserIDCreate {
	if t != nil {
		qwuic.SetUpdatedAt(*t)
	}
	return qwuic
}

// SetDeletedAt sets the "deleted_at" field.
func (qwuic *QyWechatUserIDCreate) SetDeletedAt(t time.Time) *QyWechatUserIDCreate {
	qwuic.mutation.SetDeletedAt(t)
	return qwuic
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (qwuic *QyWechatUserIDCreate) SetNillableDeletedAt(t *time.Time) *QyWechatUserIDCreate {
	if t != nil {
		qwuic.SetDeletedAt(*t)
	}
	return qwuic
}

// SetQyWechatUserID sets the "qy_wechat_user_id" field.
func (qwuic *QyWechatUserIDCreate) SetQyWechatUserID(s string) *QyWechatUserIDCreate {
	qwuic.mutation.SetQyWechatUserID(s)
	return qwuic
}

// SetNillableQyWechatUserID sets the "qy_wechat_user_id" field if the given value is not nil.
func (qwuic *QyWechatUserIDCreate) SetNillableQyWechatUserID(s *string) *QyWechatUserIDCreate {
	if s != nil {
		qwuic.SetQyWechatUserID(*s)
	}
	return qwuic
}

// SetUserID sets the "user_id" field.
func (qwuic *QyWechatUserIDCreate) SetUserID(s string) *QyWechatUserIDCreate {
	qwuic.mutation.SetUserID(s)
	return qwuic
}

// SetOpenID sets the "open_id" field.
func (qwuic *QyWechatUserIDCreate) SetOpenID(s string) *QyWechatUserIDCreate {
	qwuic.mutation.SetOpenID(s)
	return qwuic
}

// SetNillableOpenID sets the "open_id" field if the given value is not nil.
func (qwuic *QyWechatUserIDCreate) SetNillableOpenID(s *string) *QyWechatUserIDCreate {
	if s != nil {
		qwuic.SetOpenID(*s)
	}
	return qwuic
}

// SetID sets the "id" field.
func (qwuic *QyWechatUserIDCreate) SetID(u uuid.UUID) *QyWechatUserIDCreate {
	qwuic.mutation.SetID(u)
	return qwuic
}

// SetNillableID sets the "id" field if the given value is not nil.
func (qwuic *QyWechatUserIDCreate) SetNillableID(u *uuid.UUID) *QyWechatUserIDCreate {
	if u != nil {
		qwuic.SetID(*u)
	}
	return qwuic
}

// SetUser sets the "user" edge to the User entity.
func (qwuic *QyWechatUserIDCreate) SetUser(u *User) *QyWechatUserIDCreate {
	return qwuic.SetUserID(u.ID)
}

// Mutation returns the QyWechatUserIDMutation object of the builder.
func (qwuic *QyWechatUserIDCreate) Mutation() *QyWechatUserIDMutation {
	return qwuic.mutation
}

// Save creates the QyWechatUserID in the database.
func (qwuic *QyWechatUserIDCreate) Save(ctx context.Context) (*QyWechatUserID, error) {
	qwuic.defaults()
	return withHooks(ctx, qwuic.sqlSave, qwuic.mutation, qwuic.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (qwuic *QyWechatUserIDCreate) SaveX(ctx context.Context) *QyWechatUserID {
	v, err := qwuic.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (qwuic *QyWechatUserIDCreate) Exec(ctx context.Context) error {
	_, err := qwuic.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (qwuic *QyWechatUserIDCreate) ExecX(ctx context.Context) {
	if err := qwuic.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (qwuic *QyWechatUserIDCreate) defaults() {
	if _, ok := qwuic.mutation.CreatedAt(); !ok {
		v := qywechatuserid.DefaultCreatedAt()
		qwuic.mutation.SetCreatedAt(v)
	}
	if _, ok := qwuic.mutation.UpdatedAt(); !ok {
		v := qywechatuserid.DefaultUpdatedAt()
		qwuic.mutation.SetUpdatedAt(v)
	}
	if _, ok := qwuic.mutation.ID(); !ok {
		v := qywechatuserid.DefaultID()
		qwuic.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (qwuic *QyWechatUserIDCreate) check() error {
	if _, ok := qwuic.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "QyWechatUserID.created_at"`)}
	}
	if _, ok := qwuic.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "QyWechatUserID.updated_at"`)}
	}
	if _, ok := qwuic.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "QyWechatUserID.user_id"`)}
	}
	if v, ok := qwuic.mutation.UserID(); ok {
		if err := qywechatuserid.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "QyWechatUserID.user_id": %w`, err)}
		}
	}
	if len(qwuic.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "QyWechatUserID.user"`)}
	}
	return nil
}

func (qwuic *QyWechatUserIDCreate) sqlSave(ctx context.Context) (*QyWechatUserID, error) {
	if err := qwuic.check(); err != nil {
		return nil, err
	}
	_node, _spec := qwuic.createSpec()
	if err := sqlgraph.CreateNode(ctx, qwuic.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	qwuic.mutation.id = &_node.ID
	qwuic.mutation.done = true
	return _node, nil
}

func (qwuic *QyWechatUserIDCreate) createSpec() (*QyWechatUserID, *sqlgraph.CreateSpec) {
	var (
		_node = &QyWechatUserID{config: qwuic.config}
		_spec = sqlgraph.NewCreateSpec(qywechatuserid.Table, sqlgraph.NewFieldSpec(qywechatuserid.FieldID, field.TypeUUID))
	)
	if id, ok := qwuic.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := qwuic.mutation.CreatedAt(); ok {
		_spec.SetField(qywechatuserid.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := qwuic.mutation.UpdatedAt(); ok {
		_spec.SetField(qywechatuserid.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := qwuic.mutation.DeletedAt(); ok {
		_spec.SetField(qywechatuserid.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = value
	}
	if value, ok := qwuic.mutation.QyWechatUserID(); ok {
		_spec.SetField(qywechatuserid.FieldQyWechatUserID, field.TypeString, value)
		_node.QyWechatUserID = value
	}
	if value, ok := qwuic.mutation.OpenID(); ok {
		_spec.SetField(qywechatuserid.FieldOpenID, field.TypeString, value)
		_node.OpenID = value
	}
	if nodes := qwuic.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   qywechatuserid.UserTable,
			Columns: []string{qywechatuserid.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// QyWechatUserIDCreateBulk is the builder for creating many QyWechatUserID entities in bulk.
type QyWechatUserIDCreateBulk struct {
	config
	err      error
	builders []*QyWechatUserIDCreate
}

// Save creates the QyWechatUserID entities in the database.
func (qwuicb *QyWechatUserIDCreateBulk) Save(ctx context.Context) ([]*QyWechatUserID, error) {
	if qwuicb.err != nil {
		return nil, qwuicb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(qwuicb.builders))
	nodes := make([]*QyWechatUserID, len(qwuicb.builders))
	mutators := make([]Mutator, len(qwuicb.builders))
	for i := range qwuicb.builders {
		func(i int, root context.Context) {
			builder := qwuicb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*QyWechatUserIDMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, qwuicb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, qwuicb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, qwuicb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (qwuicb *QyWechatUserIDCreateBulk) SaveX(ctx context.Context) []*QyWechatUserID {
	v, err := qwuicb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (qwuicb *QyWechatUserIDCreateBulk) Exec(ctx context.Context) error {
	_, err := qwuicb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (qwuicb *QyWechatUserIDCreateBulk) ExecX(ctx context.Context) {
	if err := qwuicb.Exec(ctx); err != nil {
		panic(err)
	}
}
