// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"kiwi-user/internal/infrastructure/repository/ent/predicate"
	"kiwi-user/internal/infrastructure/repository/ent/role"
	"kiwi-user/internal/infrastructure/repository/ent/scope"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// ScopeUpdate is the builder for updating Scope entities.
type ScopeUpdate struct {
	config
	hooks    []Hook
	mutation *ScopeMutation
}

// Where appends a list predicates to the ScopeUpdate builder.
func (su *ScopeUpdate) Where(ps ...predicate.Scope) *ScopeUpdate {
	su.mutation.Where(ps...)
	return su
}

// SetUpdatedAt sets the "updated_at" field.
func (su *ScopeUpdate) SetUpdatedAt(t time.Time) *ScopeUpdate {
	su.mutation.SetUpdatedAt(t)
	return su
}

// SetDeletedAt sets the "deleted_at" field.
func (su *ScopeUpdate) SetDeletedAt(t time.Time) *ScopeUpdate {
	su.mutation.SetDeletedAt(t)
	return su
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (su *ScopeUpdate) SetNillableDeletedAt(t *time.Time) *ScopeUpdate {
	if t != nil {
		su.SetDeletedAt(*t)
	}
	return su
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (su *ScopeUpdate) ClearDeletedAt() *ScopeUpdate {
	su.mutation.ClearDeletedAt()
	return su
}

// SetRoleID sets the "role_id" field.
func (su *ScopeUpdate) SetRoleID(u uuid.UUID) *ScopeUpdate {
	su.mutation.SetRoleID(u)
	return su
}

// SetNillableRoleID sets the "role_id" field if the given value is not nil.
func (su *ScopeUpdate) SetNillableRoleID(u *uuid.UUID) *ScopeUpdate {
	if u != nil {
		su.SetRoleID(*u)
	}
	return su
}

// SetName sets the "name" field.
func (su *ScopeUpdate) SetName(s string) *ScopeUpdate {
	su.mutation.SetName(s)
	return su
}

// SetNillableName sets the "name" field if the given value is not nil.
func (su *ScopeUpdate) SetNillableName(s *string) *ScopeUpdate {
	if s != nil {
		su.SetName(*s)
	}
	return su
}

// SetHiddenInJwt sets the "hidden_in_jwt" field.
func (su *ScopeUpdate) SetHiddenInJwt(b bool) *ScopeUpdate {
	su.mutation.SetHiddenInJwt(b)
	return su
}

// SetNillableHiddenInJwt sets the "hidden_in_jwt" field if the given value is not nil.
func (su *ScopeUpdate) SetNillableHiddenInJwt(b *bool) *ScopeUpdate {
	if b != nil {
		su.SetHiddenInJwt(*b)
	}
	return su
}

// SetRole sets the "role" edge to the Role entity.
func (su *ScopeUpdate) SetRole(r *Role) *ScopeUpdate {
	return su.SetRoleID(r.ID)
}

// Mutation returns the ScopeMutation object of the builder.
func (su *ScopeUpdate) Mutation() *ScopeMutation {
	return su.mutation
}

// ClearRole clears the "role" edge to the Role entity.
func (su *ScopeUpdate) ClearRole() *ScopeUpdate {
	su.mutation.ClearRole()
	return su
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (su *ScopeUpdate) Save(ctx context.Context) (int, error) {
	su.defaults()
	return withHooks(ctx, su.sqlSave, su.mutation, su.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (su *ScopeUpdate) SaveX(ctx context.Context) int {
	affected, err := su.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (su *ScopeUpdate) Exec(ctx context.Context) error {
	_, err := su.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (su *ScopeUpdate) ExecX(ctx context.Context) {
	if err := su.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (su *ScopeUpdate) defaults() {
	if _, ok := su.mutation.UpdatedAt(); !ok {
		v := scope.UpdateDefaultUpdatedAt()
		su.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (su *ScopeUpdate) check() error {
	if v, ok := su.mutation.Name(); ok {
		if err := scope.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Scope.name": %w`, err)}
		}
	}
	if su.mutation.RoleCleared() && len(su.mutation.RoleIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Scope.role"`)
	}
	return nil
}

func (su *ScopeUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := su.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(scope.Table, scope.Columns, sqlgraph.NewFieldSpec(scope.FieldID, field.TypeUUID))
	if ps := su.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := su.mutation.UpdatedAt(); ok {
		_spec.SetField(scope.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := su.mutation.DeletedAt(); ok {
		_spec.SetField(scope.FieldDeletedAt, field.TypeTime, value)
	}
	if su.mutation.DeletedAtCleared() {
		_spec.ClearField(scope.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := su.mutation.Name(); ok {
		_spec.SetField(scope.FieldName, field.TypeString, value)
	}
	if value, ok := su.mutation.HiddenInJwt(); ok {
		_spec.SetField(scope.FieldHiddenInJwt, field.TypeBool, value)
	}
	if su.mutation.RoleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   scope.RoleTable,
			Columns: []string{scope.RoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.RoleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   scope.RoleTable,
			Columns: []string{scope.RoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, su.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{scope.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	su.mutation.done = true
	return n, nil
}

// ScopeUpdateOne is the builder for updating a single Scope entity.
type ScopeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ScopeMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (suo *ScopeUpdateOne) SetUpdatedAt(t time.Time) *ScopeUpdateOne {
	suo.mutation.SetUpdatedAt(t)
	return suo
}

// SetDeletedAt sets the "deleted_at" field.
func (suo *ScopeUpdateOne) SetDeletedAt(t time.Time) *ScopeUpdateOne {
	suo.mutation.SetDeletedAt(t)
	return suo
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (suo *ScopeUpdateOne) SetNillableDeletedAt(t *time.Time) *ScopeUpdateOne {
	if t != nil {
		suo.SetDeletedAt(*t)
	}
	return suo
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (suo *ScopeUpdateOne) ClearDeletedAt() *ScopeUpdateOne {
	suo.mutation.ClearDeletedAt()
	return suo
}

// SetRoleID sets the "role_id" field.
func (suo *ScopeUpdateOne) SetRoleID(u uuid.UUID) *ScopeUpdateOne {
	suo.mutation.SetRoleID(u)
	return suo
}

// SetNillableRoleID sets the "role_id" field if the given value is not nil.
func (suo *ScopeUpdateOne) SetNillableRoleID(u *uuid.UUID) *ScopeUpdateOne {
	if u != nil {
		suo.SetRoleID(*u)
	}
	return suo
}

// SetName sets the "name" field.
func (suo *ScopeUpdateOne) SetName(s string) *ScopeUpdateOne {
	suo.mutation.SetName(s)
	return suo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (suo *ScopeUpdateOne) SetNillableName(s *string) *ScopeUpdateOne {
	if s != nil {
		suo.SetName(*s)
	}
	return suo
}

// SetHiddenInJwt sets the "hidden_in_jwt" field.
func (suo *ScopeUpdateOne) SetHiddenInJwt(b bool) *ScopeUpdateOne {
	suo.mutation.SetHiddenInJwt(b)
	return suo
}

// SetNillableHiddenInJwt sets the "hidden_in_jwt" field if the given value is not nil.
func (suo *ScopeUpdateOne) SetNillableHiddenInJwt(b *bool) *ScopeUpdateOne {
	if b != nil {
		suo.SetHiddenInJwt(*b)
	}
	return suo
}

// SetRole sets the "role" edge to the Role entity.
func (suo *ScopeUpdateOne) SetRole(r *Role) *ScopeUpdateOne {
	return suo.SetRoleID(r.ID)
}

// Mutation returns the ScopeMutation object of the builder.
func (suo *ScopeUpdateOne) Mutation() *ScopeMutation {
	return suo.mutation
}

// ClearRole clears the "role" edge to the Role entity.
func (suo *ScopeUpdateOne) ClearRole() *ScopeUpdateOne {
	suo.mutation.ClearRole()
	return suo
}

// Where appends a list predicates to the ScopeUpdate builder.
func (suo *ScopeUpdateOne) Where(ps ...predicate.Scope) *ScopeUpdateOne {
	suo.mutation.Where(ps...)
	return suo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (suo *ScopeUpdateOne) Select(field string, fields ...string) *ScopeUpdateOne {
	suo.fields = append([]string{field}, fields...)
	return suo
}

// Save executes the query and returns the updated Scope entity.
func (suo *ScopeUpdateOne) Save(ctx context.Context) (*Scope, error) {
	suo.defaults()
	return withHooks(ctx, suo.sqlSave, suo.mutation, suo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (suo *ScopeUpdateOne) SaveX(ctx context.Context) *Scope {
	node, err := suo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (suo *ScopeUpdateOne) Exec(ctx context.Context) error {
	_, err := suo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (suo *ScopeUpdateOne) ExecX(ctx context.Context) {
	if err := suo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (suo *ScopeUpdateOne) defaults() {
	if _, ok := suo.mutation.UpdatedAt(); !ok {
		v := scope.UpdateDefaultUpdatedAt()
		suo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (suo *ScopeUpdateOne) check() error {
	if v, ok := suo.mutation.Name(); ok {
		if err := scope.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Scope.name": %w`, err)}
		}
	}
	if suo.mutation.RoleCleared() && len(suo.mutation.RoleIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Scope.role"`)
	}
	return nil
}

func (suo *ScopeUpdateOne) sqlSave(ctx context.Context) (_node *Scope, err error) {
	if err := suo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(scope.Table, scope.Columns, sqlgraph.NewFieldSpec(scope.FieldID, field.TypeUUID))
	id, ok := suo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Scope.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := suo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, scope.FieldID)
		for _, f := range fields {
			if !scope.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != scope.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := suo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := suo.mutation.UpdatedAt(); ok {
		_spec.SetField(scope.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := suo.mutation.DeletedAt(); ok {
		_spec.SetField(scope.FieldDeletedAt, field.TypeTime, value)
	}
	if suo.mutation.DeletedAtCleared() {
		_spec.ClearField(scope.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := suo.mutation.Name(); ok {
		_spec.SetField(scope.FieldName, field.TypeString, value)
	}
	if value, ok := suo.mutation.HiddenInJwt(); ok {
		_spec.SetField(scope.FieldHiddenInJwt, field.TypeBool, value)
	}
	if suo.mutation.RoleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   scope.RoleTable,
			Columns: []string{scope.RoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.RoleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   scope.RoleTable,
			Columns: []string{scope.RoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Scope{config: suo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, suo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{scope.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	suo.mutation.done = true
	return _node, nil
}
