// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"kiwi-user/internal/infrastructure/repository/ent/role"
	"kiwi-user/internal/infrastructure/repository/ent/scope"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// ScopeCreate is the builder for creating a Scope entity.
type ScopeCreate struct {
	config
	mutation *ScopeMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (sc *ScopeCreate) SetCreatedAt(t time.Time) *ScopeCreate {
	sc.mutation.SetCreatedAt(t)
	return sc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (sc *ScopeCreate) SetNillableCreatedAt(t *time.Time) *ScopeCreate {
	if t != nil {
		sc.SetCreatedAt(*t)
	}
	return sc
}

// SetUpdatedAt sets the "updated_at" field.
func (sc *ScopeCreate) SetUpdatedAt(t time.Time) *ScopeCreate {
	sc.mutation.SetUpdatedAt(t)
	return sc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (sc *ScopeCreate) SetNillableUpdatedAt(t *time.Time) *ScopeCreate {
	if t != nil {
		sc.SetUpdatedAt(*t)
	}
	return sc
}

// SetDeletedAt sets the "deleted_at" field.
func (sc *ScopeCreate) SetDeletedAt(t time.Time) *ScopeCreate {
	sc.mutation.SetDeletedAt(t)
	return sc
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (sc *ScopeCreate) SetNillableDeletedAt(t *time.Time) *ScopeCreate {
	if t != nil {
		sc.SetDeletedAt(*t)
	}
	return sc
}

// SetRoleID sets the "role_id" field.
func (sc *ScopeCreate) SetRoleID(u uuid.UUID) *ScopeCreate {
	sc.mutation.SetRoleID(u)
	return sc
}

// SetName sets the "name" field.
func (sc *ScopeCreate) SetName(s string) *ScopeCreate {
	sc.mutation.SetName(s)
	return sc
}

// SetHiddenInJwt sets the "hidden_in_jwt" field.
func (sc *ScopeCreate) SetHiddenInJwt(b bool) *ScopeCreate {
	sc.mutation.SetHiddenInJwt(b)
	return sc
}

// SetNillableHiddenInJwt sets the "hidden_in_jwt" field if the given value is not nil.
func (sc *ScopeCreate) SetNillableHiddenInJwt(b *bool) *ScopeCreate {
	if b != nil {
		sc.SetHiddenInJwt(*b)
	}
	return sc
}

// SetID sets the "id" field.
func (sc *ScopeCreate) SetID(u uuid.UUID) *ScopeCreate {
	sc.mutation.SetID(u)
	return sc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (sc *ScopeCreate) SetNillableID(u *uuid.UUID) *ScopeCreate {
	if u != nil {
		sc.SetID(*u)
	}
	return sc
}

// SetRole sets the "role" edge to the Role entity.
func (sc *ScopeCreate) SetRole(r *Role) *ScopeCreate {
	return sc.SetRoleID(r.ID)
}

// Mutation returns the ScopeMutation object of the builder.
func (sc *ScopeCreate) Mutation() *ScopeMutation {
	return sc.mutation
}

// Save creates the Scope in the database.
func (sc *ScopeCreate) Save(ctx context.Context) (*Scope, error) {
	sc.defaults()
	return withHooks(ctx, sc.sqlSave, sc.mutation, sc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (sc *ScopeCreate) SaveX(ctx context.Context) *Scope {
	v, err := sc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (sc *ScopeCreate) Exec(ctx context.Context) error {
	_, err := sc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sc *ScopeCreate) ExecX(ctx context.Context) {
	if err := sc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (sc *ScopeCreate) defaults() {
	if _, ok := sc.mutation.CreatedAt(); !ok {
		v := scope.DefaultCreatedAt()
		sc.mutation.SetCreatedAt(v)
	}
	if _, ok := sc.mutation.UpdatedAt(); !ok {
		v := scope.DefaultUpdatedAt()
		sc.mutation.SetUpdatedAt(v)
	}
	if _, ok := sc.mutation.HiddenInJwt(); !ok {
		v := scope.DefaultHiddenInJwt
		sc.mutation.SetHiddenInJwt(v)
	}
	if _, ok := sc.mutation.ID(); !ok {
		v := scope.DefaultID()
		sc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (sc *ScopeCreate) check() error {
	if _, ok := sc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Scope.created_at"`)}
	}
	if _, ok := sc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Scope.updated_at"`)}
	}
	if _, ok := sc.mutation.RoleID(); !ok {
		return &ValidationError{Name: "role_id", err: errors.New(`ent: missing required field "Scope.role_id"`)}
	}
	if _, ok := sc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Scope.name"`)}
	}
	if v, ok := sc.mutation.Name(); ok {
		if err := scope.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Scope.name": %w`, err)}
		}
	}
	if _, ok := sc.mutation.HiddenInJwt(); !ok {
		return &ValidationError{Name: "hidden_in_jwt", err: errors.New(`ent: missing required field "Scope.hidden_in_jwt"`)}
	}
	if len(sc.mutation.RoleIDs()) == 0 {
		return &ValidationError{Name: "role", err: errors.New(`ent: missing required edge "Scope.role"`)}
	}
	return nil
}

func (sc *ScopeCreate) sqlSave(ctx context.Context) (*Scope, error) {
	if err := sc.check(); err != nil {
		return nil, err
	}
	_node, _spec := sc.createSpec()
	if err := sqlgraph.CreateNode(ctx, sc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	sc.mutation.id = &_node.ID
	sc.mutation.done = true
	return _node, nil
}

func (sc *ScopeCreate) createSpec() (*Scope, *sqlgraph.CreateSpec) {
	var (
		_node = &Scope{config: sc.config}
		_spec = sqlgraph.NewCreateSpec(scope.Table, sqlgraph.NewFieldSpec(scope.FieldID, field.TypeUUID))
	)
	if id, ok := sc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := sc.mutation.CreatedAt(); ok {
		_spec.SetField(scope.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := sc.mutation.UpdatedAt(); ok {
		_spec.SetField(scope.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := sc.mutation.DeletedAt(); ok {
		_spec.SetField(scope.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = value
	}
	if value, ok := sc.mutation.Name(); ok {
		_spec.SetField(scope.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := sc.mutation.HiddenInJwt(); ok {
		_spec.SetField(scope.FieldHiddenInJwt, field.TypeBool, value)
		_node.HiddenInJwt = value
	}
	if nodes := sc.mutation.RoleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   scope.RoleTable,
			Columns: []string{scope.RoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.RoleID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ScopeCreateBulk is the builder for creating many Scope entities in bulk.
type ScopeCreateBulk struct {
	config
	err      error
	builders []*ScopeCreate
}

// Save creates the Scope entities in the database.
func (scb *ScopeCreateBulk) Save(ctx context.Context) ([]*Scope, error) {
	if scb.err != nil {
		return nil, scb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(scb.builders))
	nodes := make([]*Scope, len(scb.builders))
	mutators := make([]Mutator, len(scb.builders))
	for i := range scb.builders {
		func(i int, root context.Context) {
			builder := scb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ScopeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, scb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, scb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, scb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (scb *ScopeCreateBulk) SaveX(ctx context.Context) []*Scope {
	v, err := scb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (scb *ScopeCreateBulk) Exec(ctx context.Context) error {
	_, err := scb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (scb *ScopeCreateBulk) ExecX(ctx context.Context) {
	if err := scb.Exec(ctx); err != nil {
		panic(err)
	}
}
