// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"kiwi-user/internal/infrastructure/repository/ent/predicate"
	"kiwi-user/internal/infrastructure/repository/ent/stripeevent"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// StripeEventQuery is the builder for querying StripeEvent entities.
type StripeEventQuery struct {
	config
	ctx        *QueryContext
	order      []stripeevent.OrderOption
	inters     []Interceptor
	predicates []predicate.StripeEvent
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the StripeEventQuery builder.
func (seq *StripeEventQuery) Where(ps ...predicate.StripeEvent) *StripeEventQuery {
	seq.predicates = append(seq.predicates, ps...)
	return seq
}

// Limit the number of records to be returned by this query.
func (seq *StripeEventQuery) Limit(limit int) *StripeEventQuery {
	seq.ctx.Limit = &limit
	return seq
}

// Offset to start from.
func (seq *StripeEventQuery) Offset(offset int) *StripeEventQuery {
	seq.ctx.Offset = &offset
	return seq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (seq *StripeEventQuery) Unique(unique bool) *StripeEventQuery {
	seq.ctx.Unique = &unique
	return seq
}

// Order specifies how the records should be ordered.
func (seq *StripeEventQuery) Order(o ...stripeevent.OrderOption) *StripeEventQuery {
	seq.order = append(seq.order, o...)
	return seq
}

// First returns the first StripeEvent entity from the query.
// Returns a *NotFoundError when no StripeEvent was found.
func (seq *StripeEventQuery) First(ctx context.Context) (*StripeEvent, error) {
	nodes, err := seq.Limit(1).All(setContextOp(ctx, seq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{stripeevent.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (seq *StripeEventQuery) FirstX(ctx context.Context) *StripeEvent {
	node, err := seq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first StripeEvent ID from the query.
// Returns a *NotFoundError when no StripeEvent ID was found.
func (seq *StripeEventQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = seq.Limit(1).IDs(setContextOp(ctx, seq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{stripeevent.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (seq *StripeEventQuery) FirstIDX(ctx context.Context) int {
	id, err := seq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single StripeEvent entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one StripeEvent entity is found.
// Returns a *NotFoundError when no StripeEvent entities are found.
func (seq *StripeEventQuery) Only(ctx context.Context) (*StripeEvent, error) {
	nodes, err := seq.Limit(2).All(setContextOp(ctx, seq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{stripeevent.Label}
	default:
		return nil, &NotSingularError{stripeevent.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (seq *StripeEventQuery) OnlyX(ctx context.Context) *StripeEvent {
	node, err := seq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only StripeEvent ID in the query.
// Returns a *NotSingularError when more than one StripeEvent ID is found.
// Returns a *NotFoundError when no entities are found.
func (seq *StripeEventQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = seq.Limit(2).IDs(setContextOp(ctx, seq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{stripeevent.Label}
	default:
		err = &NotSingularError{stripeevent.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (seq *StripeEventQuery) OnlyIDX(ctx context.Context) int {
	id, err := seq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of StripeEvents.
func (seq *StripeEventQuery) All(ctx context.Context) ([]*StripeEvent, error) {
	ctx = setContextOp(ctx, seq.ctx, ent.OpQueryAll)
	if err := seq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*StripeEvent, *StripeEventQuery]()
	return withInterceptors[[]*StripeEvent](ctx, seq, qr, seq.inters)
}

// AllX is like All, but panics if an error occurs.
func (seq *StripeEventQuery) AllX(ctx context.Context) []*StripeEvent {
	nodes, err := seq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of StripeEvent IDs.
func (seq *StripeEventQuery) IDs(ctx context.Context) (ids []int, err error) {
	if seq.ctx.Unique == nil && seq.path != nil {
		seq.Unique(true)
	}
	ctx = setContextOp(ctx, seq.ctx, ent.OpQueryIDs)
	if err = seq.Select(stripeevent.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (seq *StripeEventQuery) IDsX(ctx context.Context) []int {
	ids, err := seq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (seq *StripeEventQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, seq.ctx, ent.OpQueryCount)
	if err := seq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, seq, querierCount[*StripeEventQuery](), seq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (seq *StripeEventQuery) CountX(ctx context.Context) int {
	count, err := seq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (seq *StripeEventQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, seq.ctx, ent.OpQueryExist)
	switch _, err := seq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (seq *StripeEventQuery) ExistX(ctx context.Context) bool {
	exist, err := seq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the StripeEventQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (seq *StripeEventQuery) Clone() *StripeEventQuery {
	if seq == nil {
		return nil
	}
	return &StripeEventQuery{
		config:     seq.config,
		ctx:        seq.ctx.Clone(),
		order:      append([]stripeevent.OrderOption{}, seq.order...),
		inters:     append([]Interceptor{}, seq.inters...),
		predicates: append([]predicate.StripeEvent{}, seq.predicates...),
		// clone intermediate query.
		sql:  seq.sql.Clone(),
		path: seq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.StripeEvent.Query().
//		GroupBy(stripeevent.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (seq *StripeEventQuery) GroupBy(field string, fields ...string) *StripeEventGroupBy {
	seq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &StripeEventGroupBy{build: seq}
	grbuild.flds = &seq.ctx.Fields
	grbuild.label = stripeevent.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.StripeEvent.Query().
//		Select(stripeevent.FieldCreatedAt).
//		Scan(ctx, &v)
func (seq *StripeEventQuery) Select(fields ...string) *StripeEventSelect {
	seq.ctx.Fields = append(seq.ctx.Fields, fields...)
	sbuild := &StripeEventSelect{StripeEventQuery: seq}
	sbuild.label = stripeevent.Label
	sbuild.flds, sbuild.scan = &seq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a StripeEventSelect configured with the given aggregations.
func (seq *StripeEventQuery) Aggregate(fns ...AggregateFunc) *StripeEventSelect {
	return seq.Select().Aggregate(fns...)
}

func (seq *StripeEventQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range seq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, seq); err != nil {
				return err
			}
		}
	}
	for _, f := range seq.ctx.Fields {
		if !stripeevent.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if seq.path != nil {
		prev, err := seq.path(ctx)
		if err != nil {
			return err
		}
		seq.sql = prev
	}
	return nil
}

func (seq *StripeEventQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*StripeEvent, error) {
	var (
		nodes = []*StripeEvent{}
		_spec = seq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*StripeEvent).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &StripeEvent{config: seq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	if len(seq.modifiers) > 0 {
		_spec.Modifiers = seq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, seq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (seq *StripeEventQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := seq.querySpec()
	if len(seq.modifiers) > 0 {
		_spec.Modifiers = seq.modifiers
	}
	_spec.Node.Columns = seq.ctx.Fields
	if len(seq.ctx.Fields) > 0 {
		_spec.Unique = seq.ctx.Unique != nil && *seq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, seq.driver, _spec)
}

func (seq *StripeEventQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(stripeevent.Table, stripeevent.Columns, sqlgraph.NewFieldSpec(stripeevent.FieldID, field.TypeInt))
	_spec.From = seq.sql
	if unique := seq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if seq.path != nil {
		_spec.Unique = true
	}
	if fields := seq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, stripeevent.FieldID)
		for i := range fields {
			if fields[i] != stripeevent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := seq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := seq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := seq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := seq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (seq *StripeEventQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(seq.driver.Dialect())
	t1 := builder.Table(stripeevent.Table)
	columns := seq.ctx.Fields
	if len(columns) == 0 {
		columns = stripeevent.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if seq.sql != nil {
		selector = seq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if seq.ctx.Unique != nil && *seq.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range seq.modifiers {
		m(selector)
	}
	for _, p := range seq.predicates {
		p(selector)
	}
	for _, p := range seq.order {
		p(selector)
	}
	if offset := seq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := seq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (seq *StripeEventQuery) ForUpdate(opts ...sql.LockOption) *StripeEventQuery {
	if seq.driver.Dialect() == dialect.Postgres {
		seq.Unique(false)
	}
	seq.modifiers = append(seq.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return seq
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (seq *StripeEventQuery) ForShare(opts ...sql.LockOption) *StripeEventQuery {
	if seq.driver.Dialect() == dialect.Postgres {
		seq.Unique(false)
	}
	seq.modifiers = append(seq.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return seq
}

// StripeEventGroupBy is the group-by builder for StripeEvent entities.
type StripeEventGroupBy struct {
	selector
	build *StripeEventQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (segb *StripeEventGroupBy) Aggregate(fns ...AggregateFunc) *StripeEventGroupBy {
	segb.fns = append(segb.fns, fns...)
	return segb
}

// Scan applies the selector query and scans the result into the given value.
func (segb *StripeEventGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, segb.build.ctx, ent.OpQueryGroupBy)
	if err := segb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*StripeEventQuery, *StripeEventGroupBy](ctx, segb.build, segb, segb.build.inters, v)
}

func (segb *StripeEventGroupBy) sqlScan(ctx context.Context, root *StripeEventQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(segb.fns))
	for _, fn := range segb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*segb.flds)+len(segb.fns))
		for _, f := range *segb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*segb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := segb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// StripeEventSelect is the builder for selecting fields of StripeEvent entities.
type StripeEventSelect struct {
	*StripeEventQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ses *StripeEventSelect) Aggregate(fns ...AggregateFunc) *StripeEventSelect {
	ses.fns = append(ses.fns, fns...)
	return ses
}

// Scan applies the selector query and scans the result into the given value.
func (ses *StripeEventSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ses.ctx, ent.OpQuerySelect)
	if err := ses.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*StripeEventQuery, *StripeEventSelect](ctx, ses.StripeEventQuery, ses, ses.inters, v)
}

func (ses *StripeEventSelect) sqlScan(ctx context.Context, root *StripeEventQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ses.fns))
	for _, fn := range ses.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ses.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ses.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
