// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Application is the predicate function for application builders.
type Application func(*sql.Selector)

// Binding is the predicate function for binding builders.
type Binding func(*sql.Selector)

// BindingVerify is the predicate function for bindingverify builders.
type BindingVerify func(*sql.Selector)

// Device is the predicate function for device builders.
type Device func(*sql.Selector)

// MailVertifyCode is the predicate function for mailvertifycode builders.
type MailVertifyCode func(*sql.Selector)

// Organization is the predicate function for organization builders.
type Organization func(*sql.Selector)

// OrganizationApplication is the predicate function for organizationapplication builders.
type OrganizationApplication func(*sql.Selector)

// OrganizationRequest is the predicate function for organizationrequest builders.
type OrganizationRequest func(*sql.Selector)

// OrganizationUser is the predicate function for organizationuser builders.
type OrganizationUser func(*sql.Selector)

// Payment is the predicate function for payment builders.
type Payment func(*sql.Selector)

// QyWechatUserID is the predicate function for qywechatuserid builders.
type QyWechatUserID func(*sql.Selector)

// Role is the predicate function for role builders.
type Role func(*sql.Selector)

// Scope is the predicate function for scope builders.
type Scope func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// WechatOpenID is the predicate function for wechatopenid builders.
type WechatOpenID func(*sql.Selector)
