// Code generated by ent, DO NOT EDIT.

package payment

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the payment type in the database.
	Label = "payment"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldOutTradeNo holds the string denoting the out_trade_no field in the database.
	FieldOutTradeNo = "out_trade_no"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldChannel holds the string denoting the channel field in the database.
	FieldChannel = "channel"
	// FieldService holds the string denoting the service field in the database.
	FieldService = "service"
	// FieldAmount holds the string denoting the amount field in the database.
	FieldAmount = "amount"
	// FieldCurrency holds the string denoting the currency field in the database.
	FieldCurrency = "currency"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldPaidAt holds the string denoting the paid_at field in the database.
	FieldPaidAt = "paid_at"
	// FieldPaymentType holds the string denoting the payment_type field in the database.
	FieldPaymentType = "payment_type"
	// FieldWechatPlatform holds the string denoting the wechat_platform field in the database.
	FieldWechatPlatform = "wechat_platform"
	// FieldWechatOpenID holds the string denoting the wechat_open_id field in the database.
	FieldWechatOpenID = "wechat_open_id"
	// FieldWechatTransactionID holds the string denoting the wechat_transaction_id field in the database.
	FieldWechatTransactionID = "wechat_transaction_id"
	// FieldStripeSubscriptionID holds the string denoting the stripe_subscription_id field in the database.
	FieldStripeSubscriptionID = "stripe_subscription_id"
	// FieldStripeSubscriptionStatus holds the string denoting the stripe_subscription_status field in the database.
	FieldStripeSubscriptionStatus = "stripe_subscription_status"
	// FieldStripeInterval holds the string denoting the stripe_interval field in the database.
	FieldStripeInterval = "stripe_interval"
	// FieldStripeCancelAtPeriodEnd holds the string denoting the stripe_cancel_at_period_end field in the database.
	FieldStripeCancelAtPeriodEnd = "stripe_cancel_at_period_end"
	// FieldStripeCurrentPeriodStart holds the string denoting the stripe_current_period_start field in the database.
	FieldStripeCurrentPeriodStart = "stripe_current_period_start"
	// FieldStripeCurrentPeriodEnd holds the string denoting the stripe_current_period_end field in the database.
	FieldStripeCurrentPeriodEnd = "stripe_current_period_end"
	// FieldStripeCustomerID holds the string denoting the stripe_customer_id field in the database.
	FieldStripeCustomerID = "stripe_customer_id"
	// FieldStripeCustomerEmail holds the string denoting the stripe_customer_email field in the database.
	FieldStripeCustomerEmail = "stripe_customer_email"
	// FieldStripeCheckoutSessionID holds the string denoting the stripe_checkout_session_id field in the database.
	FieldStripeCheckoutSessionID = "stripe_checkout_session_id"
	// FieldStripeInvoiceID holds the string denoting the stripe_invoice_id field in the database.
	FieldStripeInvoiceID = "stripe_invoice_id"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// Table holds the table name of the payment in the database.
	Table = "payments"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "payments"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
)

// Columns holds all SQL columns for payment fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldOutTradeNo,
	FieldUserID,
	FieldChannel,
	FieldService,
	FieldAmount,
	FieldCurrency,
	FieldDescription,
	FieldStatus,
	FieldPaidAt,
	FieldPaymentType,
	FieldWechatPlatform,
	FieldWechatOpenID,
	FieldWechatTransactionID,
	FieldStripeSubscriptionID,
	FieldStripeSubscriptionStatus,
	FieldStripeInterval,
	FieldStripeCancelAtPeriodEnd,
	FieldStripeCurrentPeriodStart,
	FieldStripeCurrentPeriodEnd,
	FieldStripeCustomerID,
	FieldStripeCustomerEmail,
	FieldStripeCheckoutSessionID,
	FieldStripeInvoiceID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// OutTradeNoValidator is a validator for the "out_trade_no" field. It is called by the builders before save.
	OutTradeNoValidator func(string) error
	// UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	UserIDValidator func(string) error
	// ServiceValidator is a validator for the "service" field. It is called by the builders before save.
	ServiceValidator func(string) error
	// AmountValidator is a validator for the "amount" field. It is called by the builders before save.
	AmountValidator func(int) error
	// CurrencyValidator is a validator for the "currency" field. It is called by the builders before save.
	CurrencyValidator func(string) error
	// DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	DescriptionValidator func(string) error
	// DefaultStripeCancelAtPeriodEnd holds the default value on creation for the "stripe_cancel_at_period_end" field.
	DefaultStripeCancelAtPeriodEnd bool
)

// Channel defines the type for the "channel" enum field.
type Channel string

// Channel values.
const (
	ChannelWechat Channel = "wechat"
	ChannelStripe Channel = "stripe"
)

func (c Channel) String() string {
	return string(c)
}

// ChannelValidator is a validator for the "channel" field enum values. It is called by the builders before save.
func ChannelValidator(c Channel) error {
	switch c {
	case ChannelWechat, ChannelStripe:
		return nil
	default:
		return fmt.Errorf("payment: invalid enum value for channel field: %q", c)
	}
}

// Status defines the type for the "status" enum field.
type Status string

// Status values.
const (
	StatusNOTPAY  Status = "NOTPAY"
	StatusSUCCESS Status = "SUCCESS"
	StatusCLOSED  Status = "CLOSED"
	StatusREFUND  Status = "REFUND"
	StatusFAILED  Status = "FAILED"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusNOTPAY, StatusSUCCESS, StatusCLOSED, StatusREFUND, StatusFAILED:
		return nil
	default:
		return fmt.Errorf("payment: invalid enum value for status field: %q", s)
	}
}

// PaymentType defines the type for the "payment_type" enum field.
type PaymentType string

// PaymentTypeOneTime is the default value of the PaymentType enum.
const DefaultPaymentType = PaymentTypeOneTime

// PaymentType values.
const (
	PaymentTypeOneTime      PaymentType = "one_time"
	PaymentTypeSubscription PaymentType = "subscription"
)

func (pt PaymentType) String() string {
	return string(pt)
}

// PaymentTypeValidator is a validator for the "payment_type" field enum values. It is called by the builders before save.
func PaymentTypeValidator(pt PaymentType) error {
	switch pt {
	case PaymentTypeOneTime, PaymentTypeSubscription:
		return nil
	default:
		return fmt.Errorf("payment: invalid enum value for payment_type field: %q", pt)
	}
}

// OrderOption defines the ordering options for the Payment queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByOutTradeNo orders the results by the out_trade_no field.
func ByOutTradeNo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOutTradeNo, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByChannel orders the results by the channel field.
func ByChannel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChannel, opts...).ToFunc()
}

// ByService orders the results by the service field.
func ByService(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldService, opts...).ToFunc()
}

// ByAmount orders the results by the amount field.
func ByAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAmount, opts...).ToFunc()
}

// ByCurrency orders the results by the currency field.
func ByCurrency(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCurrency, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByPaidAt orders the results by the paid_at field.
func ByPaidAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPaidAt, opts...).ToFunc()
}

// ByPaymentType orders the results by the payment_type field.
func ByPaymentType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPaymentType, opts...).ToFunc()
}

// ByWechatPlatform orders the results by the wechat_platform field.
func ByWechatPlatform(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWechatPlatform, opts...).ToFunc()
}

// ByWechatOpenID orders the results by the wechat_open_id field.
func ByWechatOpenID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWechatOpenID, opts...).ToFunc()
}

// ByWechatTransactionID orders the results by the wechat_transaction_id field.
func ByWechatTransactionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWechatTransactionID, opts...).ToFunc()
}

// ByStripeSubscriptionID orders the results by the stripe_subscription_id field.
func ByStripeSubscriptionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStripeSubscriptionID, opts...).ToFunc()
}

// ByStripeSubscriptionStatus orders the results by the stripe_subscription_status field.
func ByStripeSubscriptionStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStripeSubscriptionStatus, opts...).ToFunc()
}

// ByStripeInterval orders the results by the stripe_interval field.
func ByStripeInterval(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStripeInterval, opts...).ToFunc()
}

// ByStripeCancelAtPeriodEnd orders the results by the stripe_cancel_at_period_end field.
func ByStripeCancelAtPeriodEnd(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStripeCancelAtPeriodEnd, opts...).ToFunc()
}

// ByStripeCurrentPeriodStart orders the results by the stripe_current_period_start field.
func ByStripeCurrentPeriodStart(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStripeCurrentPeriodStart, opts...).ToFunc()
}

// ByStripeCurrentPeriodEnd orders the results by the stripe_current_period_end field.
func ByStripeCurrentPeriodEnd(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStripeCurrentPeriodEnd, opts...).ToFunc()
}

// ByStripeCustomerID orders the results by the stripe_customer_id field.
func ByStripeCustomerID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStripeCustomerID, opts...).ToFunc()
}

// ByStripeCustomerEmail orders the results by the stripe_customer_email field.
func ByStripeCustomerEmail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStripeCustomerEmail, opts...).ToFunc()
}

// ByStripeCheckoutSessionID orders the results by the stripe_checkout_session_id field.
func ByStripeCheckoutSessionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStripeCheckoutSessionID, opts...).ToFunc()
}

// ByStripeInvoiceID orders the results by the stripe_invoice_id field.
func ByStripeInvoiceID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStripeInvoiceID, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
